### ISSUE TITLE
Get rid of v-html directive

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#1031]
I would like to get rid of the usage of `v-html`. First of all, I don't like the warning message in the lint action 😉 (indeed, it sometimes hides important errors / warnings, since you have to scroll).

Also, although we `escapeHtml`, I think it would be better to use a white-list instead of a black-list approach and only render an allowed tag around a matched string, instead of escaping every possible HTML tag in our text.

There are multiple directives out there which realize this using vues render function, e.g. https://github.com/Astray-git/vue-highlight-words or https://github.com/AlbertLucianto/vue-text-highlight. I haven't tested them so far, but they seem to work and are relatively light-weight. They would also allow a bit more sophisticated stuff, such as multiple search terms, which we don't use.

The alternative would be to write a very simple directive on our own really only wrapping a match in a `strong`, using a render function.

What do you think? I would be up for writing the directive if we don't want to use an existing one.

**Comment by skjnldsv** [comment]
I'm not sure we should make our life more difficult :stuck_out_tongue: 
Aside from the warnings (that don't count as good reasons for me), do you see any benefits from moving to a different approach?

**Comment by raimund-schluessler** [comment]
I think it would be cleaner. Instead of doing it wrong (`v-html`) and then fixing it (`escapeHtml`), we would do it correctly in the first place (`render`). We would also get rid of the external dependency of `escapeHtml` which is only used here.

I will provide a PR, so we can see.

**Comment by skjnldsv** [comment]
Awesome! Thanks for this :)
