### ISSUE TITLE
Ability to add text next to icon in action button component

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#1055]
For the Forms app, we need to supply text next to an action button, namely "Add question", as otherwise it’s not really obvious what it does:
![form add question button](https://user-images.githubusercontent.com/925062/80215276-7b1ed780-863c-11ea-9e58-f0e796b66717.png)

We are using the Actions component here, but there seems to be no way to do that. https://nextcloud-vue-components.netlify.app/#/Components/Actions

**Comment by skjnldsv** [comment]
Probably not too complex, if you want to have a look :)
https://github.com/nextcloud/nextcloud-vue/blob/084f66fc8f39607c0866bfd3b2cbe89a35cc7ae7/src/components/Actions/Actions.vue#L86

**Comment by dartcafe** [comment]
If it helps. We have a custom sinple button component.
https://github.com/nextcloud/polls/blob/master/src/js/components/Base/ButtonDiv.vue
