### ISSUE TITLE
Close AppNavigation on click-outside and on navigate

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#1070]
Since on mobile the AppNavigation overlays the content now, it should be closed when you click outside of it and as well when you navigated to a different route (clicking an AppNavigationItem). This was briefly discussed in https://github.com/nextcloud/tasks/pull/965#issuecomment-623094316.

**Comment by PVince81** [comment]
not only on mobile. if you have the browser on half the horizontal width it also covers the chat window and is annoying.

**Comment by raimund-schluessler** [comment]
I just saw this was reported way earlier in #433 already.
