### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#1089]
In most places of the documentation importing a component is still advised with
```
import { Multiselect } from '@nextcloud/vue/dist/Components/Multiselect'
```

This needs to be changed, since it is no longer working. It should read
```
import Multiselect from '@nextcloud/vue/dist/Components/Multiselect'
```

**Comment by juliushaertl** [comment]
That is coming from https://github.com/nextcloud/nextcloud-vue/blob/master/styleguide.config.js#L26

**Comment by skjnldsv** [comment]
Fixed
