### ISSUE TITLE
Changes in v2.0.0?

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/nextcloud-vue#1129]
I noticed the major version bump, but couldn't find any information on which things changed, especially the breaking changes (assuming semver).

**Comment by juliushaertl** [comment]
The changelog is available for each version under the github release tags:

https://github.com/nextcloud/nextcloud-vue/releases/tag/v2.0.0

---

:warning: BREAKING
Please adjust your css styling to the new AppContent and AppNavigation. We're now independent from server styling by changing from:
- `#app-content` to `.app-content`
- `#app-navigation` to `.app-navigation`
- `#app-sidebar` to `.app-sidebar` 
- `#content` to `.content`

The layout is also now automatically reflowed with flex. See https://github.com/nextcloud/nextcloud-vue/pull/1026 https://github.com/nextcloud/nextcloud-vue/pull/989
