### ISSUE TITLE
Allow custom template in AppNavigationItem for editing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#120]

**Comment by skjnldsv** [comment]
Could you elaborate a bit more? :)
What kind of template are you thinking of?

**Comment by juliushaertl** [comment]
Right now when editing, only changing the text is allowed. For deck, e.g. we also have an element to change the color in there: 

![image](https://user-images.githubusercontent.com/3404133/49011108-98b0ee80-f175-11e8-8865-1028d546c2bc.png)

**Comment by weeman1337** [comment]
Could this work with the child components? https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppNavigation/AppNavigationItem.vue#L104

**Comment by skjnldsv** [comment]
@weeman1337 what do you mean? Yo umean, can we use this on child component as well?
The first layer of items and the subitems are the same component, everything that is possible on the main level is also available on the second :)

**Comment by weeman1337** [comment]
@skjnldsv argh - I only saw children but didn't look closer.

Anyway do you think it makes sense to pass custom components only for editing or should it be possible to hand in custom app navigation item components? They could be derived from the standard app navigation items.

**Comment by skjnldsv** [comment]
We're splitting things in #486 
I thing we should close this one.
The colour picker should go into another location: the action menu.
Adding one row of colour picker under the edit does not make sense to me (and it increase the height suddenly, making the ui move for editing, feels too crowded there)

Let's use the edit for editing like other platforms do (android, ios) and have a color picker somewhere else :)
