### ISSUE TITLE
Wrong positioning of ActionsMenu

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#1215]
However, while checking this I have found a small issue (latest Firefox):

![Share-Link-Menu-Out-Of-Bounds](https://user-images.githubusercontent.com/26858233/88099668-c6914500-cb9b-11ea-975c-a8afa685b8ba.png)

Since https://github.com/nextcloud/nextcloud-vue/commit/f3b223a54ca5c2b9dc5acb7c131c61d698ba7aaa the Actions menu is always shown to the top if there is enough room (before this was done only for centered menus, so it did not apply to the share menu due to being aligned to the right). However, as can be seen in this case there is not enough room, and yet the menu is still shown to the top (and a scroll bar is not shown either). I do not know if the problem is in the Vue component itself or in the way that it is used in the sharing tab.

_Originally posted by @danxuliu in https://github.com/nextcloud/server/pull/21867#issuecomment-662070930_

**Comment by nickvergessen** [comment]
Also while looking into this, Actions is stripping of the `boundariesElement` property of `VTooltip`. If that would be allowed to be accessed too, 
https://github.com/nextcloud/spreed/issues/3933

**Comment by raimund-schluessler** [comment]
Is this still an issue?

**Comment by nickvergessen** [comment]
The talk part is solved

**Comment by raimund-schluessler** [comment]
Very likely outdated, since we updated to a newer popover library.
