### ISSUE TITLE
Moment

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#13]
As discussed at https://github.com/nextcloud/vue-components/issues/9#issuecomment-415686834, I'd like to see a component for the moment.js integration, a.k.a. *x seconds/minutes/hours ago thingy*.

The existing Vue components suggested didn't work as expected, esp. in regards to l10n. Moreover, they wouldn't work with our [live timestamp update magic](https://github.com/nextcloud/server/pull/1215) (cc @nickvergessen). Hence, I've created my own component. This is what it looks like:

```js
<template>
	<span class="live-relative-timestamp"
		  :data-timestamp="timestamp"
		  :title=title>{{ formatted }}</span>
</template>

<script>
	import moment from 'moment';

	if (typeof OC !== 'undefined') {
		moment.locale(OC.getLocale());
	}

	export default {
		name: "Moment",
		props: [
			'timestamp',
			'format'
		],
		computed: {
			title () {
				return moment.unix(this.timestamp / 1000).format(this.format || 'LLL');
			},
			formatted () {
				return moment.unix(this.timestamp / 1000).fromNow();
			}
		}
	}
</script>
```

It works well and can be easily integrated. The live updating also seems to work with this.

## Caveats

* Pulls in moment.js (obviously) but also lots of translations. Webpack combines some stuff, but it's still rather big. We basically have the same problem in server, but we'd now load the locals twice.
* Depends on a global var. I've added a check for it's existence, though.

**Comment by ChristophWurst** [comment]
> How big is big? As we cache JS stuff pretty agressively.

~1/4 MB according to https://github.com/jmblog/how-to-optimize-momentjs-with-webpack#measurements.

**Comment by skjnldsv** [comment]
1/4 like 0.25 or 1-4MB? ^^

**Comment by ChristophWurst** [comment]
> 1/4 like 0.25

250kB :D

**Comment by skjnldsv** [comment]
For a component that only display a relative date, this is crazy ^^"
If we only display by units like `x sec ago` `x days ago` `x hours ago`, shouldn't this be universal across languages?

**Comment by skjnldsv** [comment]
Is there that many translations needed? I mean, it's like any other translation son our website?

**Comment by nickvergessen** [comment]
the thing is, this will be included like 10 times in the end?
activity, notifications, announcements, talk, ...

> Is there that many translations needed? I mean, it's like any other translation son our website?

Well Days in long and short (Mon. Monday), same for months (dec. december), etc.

**Comment by nickvergessen** [comment]
But yeah im fine with a huge bump at the moment and fixing it properly afterwards

**Comment by skjnldsv** [comment]
[Looking at the moment lib](https://raw.githubusercontent.com/jmblog/how-to-optimize-momentjs-with-webpack/master/source-map-explorer.png), I'm pretty sure we can ship this with a dynamic load of the locale. So moment (44KB) + locale (avg 1.5KB) we should be fine.
But we need a proper webpack dynamic loading setup :)

**Comment by skjnldsv** [comment]
Small references: alternative lib that does the same and is as supported: https://github.com/date-fns/date-fns/

And webpack reference for moment: https://webpack.js.org/plugins/ignore-plugin/#ignore-moment-locales

**Comment by skjnldsv** [comment]
On you entry file:
``` js
// CSP config for webpack dynamic chunk loading
// eslint-disable-next-line
__webpack_nonce__ = btoa(OC.requestToken)

// Correct the root of the app for chunk loading
// OC.linkTo matches the apps folders
// OC.generateUrl ensure the index.php (or not)
// eslint-disable-next-line
__webpack_public_path__ = OC.generateUrl(OC.linkTo('contacts', 'js/'))
```

Webpack config:
``` js
	output: {
		[...]
		chunkFilename: 'chunks/[name].js'
	},
	[...]
	plugins: [
		[...]
		new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
	],
```

Babel config
``` js
{
	[...]
	"plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```

Then just import
``` js
	import('moment/locale/' + this.locale)
		.then(e => {
			// success
		})
		.catch(e => {
			// failure
		})
```

**Comment by skjnldsv** [comment]
Correction: 

```
// We do not want the index.php since we're loading files
__webpack_public_path__ = OC.linkTo('contacts', 'js/')
```
