### ISSUE TITLE
Actions issues

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#1329]
- The popover doesn't automatically close when tabbing over the last item
- Opening for the first time doesn't auto-focus the first entry

Following #832

**Comment by nickvergessen** [comment]
Also for me in talk e.g. the share menu on the chat input does a full page refresh with this instead of opening the menu.
Might be talks fault though, as it e.g. works with the conversation menu and the participant menu

**Comment by skjnldsv** [comment]
> Also for me in talk e.g. the share menu on the chat input does a full page refresh with this instead of opening the menu.
> Might be talks fault though, as it e.g. works with the conversation menu and the participant menu

Can you show a screencast so I understand which area and show code? :)

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/0c638f39f84f9525398123899d02bcc2286987ab/src/components/NewMessageForm/NewMessageForm.vue#L38-L56

![Peek 2020-08-21 09-18](https://user-images.githubusercontent.com/213943/90863534-7e7a6380-e38f-11ea-8d83-a7b346370c67.gif)


It's master of talk with `npm link @nextcloud/vue` of master of this repo

**Comment by nickvergessen** [comment]
Networktab shows no POST request, just this in the console:
![Bildschirmfoto von 2020-08-24 16-06-42](https://user-images.githubusercontent.com/213943/91053939-de893800-e623-11ea-8b56-ad7019cf735f.png)

**Comment by nickvergessen** [comment]
`@submit.prevent` on the enclosing form fixes it.

**Comment by raimund-schluessler** [comment]
> * The popover doesn't automatically close when tabbing over the last item
> 
>     * Opening for the first time doesn't auto-focus the first entry
> 
> 
> Following #832

This works now.
