### ISSUE TITLE
Avatar from shares in sidebar are not themed

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/nextcloud-vue#1344]
![image](https://user-images.githubusercontent.com/5836855/91155970-d5e83e80-e6c3-11ea-9435-74b0cefbbfc4.png)

- set primary color to something else than default
- share a file via email/public share
- see that they are still using default blue

As all other icons (folders, checkmark in overflow menu, radio button) are tinted, this should also be tinted.

@nextcloud/designers

**Comment by skjnldsv** [comment]
cc @juliushaertl for the avatar component

**Comment by juliushaertl** [comment]
Seems like it is used with an empty string and therefore falls back to the avatar color in https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Avatar/Avatar.vue#L301-L302

**Comment by juliushaertl** [comment]
Seems to be fixed already.
