### ISSUE TITLE
[2.6] Header Menu in AppSidebar not positioned correctly

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#1345]
![34A7FED7-8F4A-405C-B860-7CDDEA044E17](https://user-images.githubusercontent.com/1250540/91163396-cc63d400-e6cd-11ea-8bbe-8f6854d1793a.png)

Tested on latest 2.6

**Comment by georgehrke** [comment]
@nickvergessen This is what you also mentioned in the call

**Comment by nickvergessen** [comment]
Okay, yeah in Talk it's the Actions menu in the participant list

**Comment by skjnldsv** [comment]
Please check again with master.
https://github.com/nextcloud/nextcloud-vue/tree/master/cypress/snapshots/base/components/AppSidebar/AppSidebar.visual.js

**Comment by raimund-schluessler** [comment]
I think this is fixed in master. For Tasks it looks like this now:

![Screenshot_2020-08-27 Tasks - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/91486331-641f1900-e8ac-11ea-9d3e-9d10085f854d.png)

It slightly overlaps the scrollbar, but I think this is alright.

**Comment by georgehrke** [comment]
![18D1D7E9-E11B-42A7-BD09-AE77FD12A23D](https://user-images.githubusercontent.com/1250540/92224537-39335700-eea2-11ea-9bcf-e9882d18dbc1.png)

Fixed in 2.6.4 👍
