### ISSUE TITLE
Provide color picker

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#138]
There should be a standardised color-picker in Nextcloud because it's needed in many places.
E.g.:
- calendar app
- mail app (cc @ChristophWurst)
- (Deck app? @juliushaertl)

This is the color-picker in the Calendar app (v1):
Safari, IE:
![55d7a0ab-ac58-4ea7-8ccd-70f6baa5a3cd](https://user-images.githubusercontent.com/1250540/49329644-6e4e9f00-f582-11e8-9cf1-517132488534.png)

Firefox, Chrome, Edge:
![cbcfbb97-beb7-4d25-a678-40c04ee397f3](https://user-images.githubusercontent.com/1250540/49329688-05b3f200-f583-11e8-83f3-5ef41acc34cc.png)

It provides a default set of colors plus a random color option in Safari, IE and a real color-picker for browsers that natively support it.
https://caniuse.com/#feat=input-color

The color-picker should also work inside the popover menu.

**Comment by georgehrke** [comment]
Just for reference: 
This is the color-picker from Google calendar
![212f8ef0-baba-4a6a-99e2-8872721da1ba](https://user-images.githubusercontent.com/1250540/49467092-eb3b7c00-f801-11e8-999b-747d646af64d.jpg)

**Comment by raimund-schluessler** [comment]
I wrote a colorpicker component for the Tasks app, see https://github.com/nextcloud/tasks/blob/vue/src/components/Colorpicker.vue. It is one of the first vue components I wrote, so it is probably badly written 🙈 I also reused some code from previous implementations.

But maybe it a first iteration to improve on.

**Comment by skjnldsv** [comment]
@raimund-schluessler I'm sure it'll be amazing! :D
Give yourself some credit!!!

Can we see some screenshots ? :tada:

**Comment by georgehrke** [comment]
ping @raimund-schluessler ^ :)

**Comment by ChristophWurst** [comment]
> We don't need one right now, but I like the idea of having a component for this +1

Well https://github.com/nextcloud/mail/issues/486 :man_shrugging:

**Comment by ma12-co** [comment]
I Like the google solution: easy enough for somebody that doesn't need to customize much, but also gives the option to pick a custom color. I made a mock up so we can discuss the design: https://www.figma.com/file/4th1eQVONZguVoDXMwnDJT/nextcloud-color-picker?node-id=0%3A1
@jancborchardt @skjnldsv

**Comment by jancborchardt** [comment]
Looking super good @ma12-co! The only thing I would change is to make the colors shown in circles instead of rounded squares. This is also what we already do in the Mail app e.g.

(Btw @georgehrke kinda related, the checkmark-to-activate interface in Google Calendar is very nice – we should probably do that too to be very obvious what is currently active.)

**Comment by ma12-co** [comment]
Thanks @jancborchardt!
> The only thing I would change is to make the colors shown in circles instead of rounded squares. 

I just updated it :)

**Comment by georgehrke** [comment]
> (Btw @georgehrke kinda related, the checkmark-to-activate interface in Google Calendar is very nice – we should probably do that too to be very obvious what is currently active.)

Absolutely! Should that be something that we put into vue components? (similar to the 
[AppNavigationIconBullet](https://github.com/nextcloud/nextcloud-vue/pull/486/files#diff-61f52899ca02462177d4695776bfd742)) Or is it too calendar-app-specific?

**Comment by ma12-co** [comment]
> (Btw @georgehrke kinda related, the checkmark-to-activate interface in Google Calendar is very nice – we should probably do that too to be very obvious what is currently active.)

Added to the mockup as well!

**Comment by georgehrke** [comment]
@ma12-co I think @jancborchardt talked about the checkbox in front of the calendar name :)

**Comment by skjnldsv** [comment]
@georgehrke I guess we can link an event to the bullet click, then you could do whatever you want. Thought it's not very discoverable. I'd put this into the menu.
And didn't you wanted an appNavCheckbox that could be coloured?

**Comment by ma12-co** [comment]
> @ma12-co I think @jancborchardt talked about the checkbox in front of the calendar name :)

Oh I get it, my bad!

**Comment by georgehrke** [comment]
@ma12-co Thank you for taking this up. Much appreciated! :)

**Comment by jancborchardt** [comment]
> @ma12-co I think @jancborchardt talked about the checkbox in front of the calendar name :)

Yup, but adding it to the active color to indicate is also good. :)
