### ISSUE TITLE
app-navigation-toggle is annoying

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#1414]
The toggle is placed right near the navigation and forces app developers find their own way to avoid visual issues.
Examples:
Polls: 
![grafik](https://user-images.githubusercontent.com/26707476/94204549-bbbb9f00-fec1-11ea-9ea1-9276c1e21375.png)
Calendar:
![grafik](https://user-images.githubusercontent.com/26707476/94204115-f07b2680-fec0-11ea-86ef-bc7b6ae14d44.png)
Talk:
![grafik](https://user-images.githubusercontent.com/26707476/94205524-c24b1600-fec3-11ea-8d70-bb0808508d97.png)
Deck:
![grafik](https://user-images.githubusercontent.com/26707476/94204432-87e07980-fec1-11ea-97d7-ee55631a0b76.png)

Proposal:
Give the navigation more space, move the toggle inside the navigation and leave 44px of the closed navigation visible:
Open state
![grafik](https://user-images.githubusercontent.com/26707476/94205074-c1fe4b00-fec2-11ea-8138-250509c9bd4c.png)
Closed state
![grafik](https://user-images.githubusercontent.com/26707476/94205053-bad73d00-fec2-11ea-93f0-4978e2b6ecbf.png)

In the result, It costs just 44px of the app container, but the app-container is again a fully usable square and the toggle is still usable. 

CSS changes for mockup:

```
.app-navigation {
	width: 344px !important;
	padding-right: 44px !important;
}

.app-navigation-toggle {
	margin-right: initial !important;
}

.app-navigation--close {
	margin-left: -300px  !important;
	transform: translateX(-300px)  !important;

	.app-navigation-entry {
		width: initial !important;
		margin-right: 44px;
	}
}
```

Comments? Opinions?

**Comment by jotoeri** [comment]
@jancborchardt Thats something that needs your opinion. ;)

I also thought about this annoying toggle sometimes...

**Comment by skjnldsv** [comment]
We have had this discussion already. 
See the full disclosure here https://github.com/nextcloud/server/issues/16934
