### ISSUE TITLE
Make user_status on avatar scale

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#1428]
We ran into serious issues in our conference due to the number of requests from the user_status feature.
E.g. in Talk we already have the information available, but there is no way to inject the information into the avatar, so each of the 500 avatars in the participant list will cause a request to the server.

**Comment by nickvergessen** [comment]
Another idea would be to return the information on the avatar itself, bu that would mean we can not cache it the way we do it at the moment (24h).

**Comment by PVince81** [comment]
Maybe a bulk query for avatars, debounced, or something... hmmm

Are we using the [RecycleScroller](https://github.com/Akryum/vue-virtual-scroller) ? I think it only renders the visible elements in DOM.

There might be other vue-based solutions where it only triggers element rendering when they become visible, like image loading, etc
