### ISSUE TITLE
Inconsistency between "multiLine" and "multiline"

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/nextcloud-vue#1483]
The second example for RichContenteditable [uses `multiline`](https://github.com/nextcloud/nextcloud-vue/blob/c8fbece53ed4e110332573218dd8ac9ea41211ea/src/components/RichContenteditable/RichContenteditable.vue#L46), but as [the property is defined as `multiLine`](https://github.com/nextcloud/nextcloud-vue/blob/c8fbece53ed4e110332573218dd8ac9ea41211ea/src/components/RichContenteditable/RichContenteditable.vue#L169) (note the capital L) it does not match and it appears as a default input.

I was just going to change the example to `multi-line`, but then I noticed that the CSS style uses `--multiline`. So I do not know if the right solution would be:
- Just use `multi-line` in the example
- Use `multi-line` in the example and `--multi-line` in the style
- Use `multiline` in the property
- Something else :-P

@skjnldsv

**Comment by skjnldsv** [comment]
Nice catch!
I wanted to use `multiline` so it looked similar as `contenteditable`.
Any preference?

**Comment by danxuliu** [comment]
> Any preference?

I would go with _Use `multiline` in the property_, as neither `multi line` nor `multi-line` can be found in [the HTML spec](https://html.spec.whatwg.org/), only `multiline`.
