### ISSUE TITLE
Move away from linkifyjs

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#1488]
Uses jQuery and is quite heavy for a simple string replacement
Let's move to https://bundlephobia.com/result?p=linkify-urls, highly supported and sindresorhus is an awesome dev with great libs! :)

**Comment by dartcafe** [comment]
Thanks for this hint. I changed from linkifyjs to linkify-urls@2 for polls. Seems that version 3 does not work in safari as mentioned on the github page.

**Comment by juliushaertl** [comment]
> Uses jQuery and is quite heavy for a simple string replacement

linkifyjs also works fine without jquery, but if linkify-urls is a sane replacement, of course saving those bytes makes sense :+1: 

https://bundlephobia.com/result?p=linkifyjs@2.1.9
https://bundlephobia.com/result?p=linkify-urls@3.1.1

**Comment by raimund-schluessler** [comment]
We only use `linkifyjs/string` and webpack is smart enough to not bundle the whole `linkifyjs` package. However, with linkifyjs@3, `linkify-string` moved to its own package, so absolutely no need for `linkifyjs` anymore.

And `linkify-string` is even smaller than `linkify-urls`: https://bundlephobia.com/package/linkify-string@3.0.2

So I think we can close this (at least as soon as https://github.com/nextcloud/nextcloud-vue/pull/2275 is in).
