### ISSUE TITLE
Plain text is not selectable in Modal component

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/nextcloud-vue#1505]
- Open the [Modal component documentation](https://nextcloud-vue-components.netlify.app/#/Components/Modal)*
- Show the modal dialog
- Try to select `Hello world`

`Hello world` is plain text and it can not be interacted with, so it should be selectable. And if it is not selectable for a reason then I think that it would be good to mention it in the documentation :-)

*It also happens when the Modal component is used in apps, but the documentation is the easiest place to check :-)

**Comment by skjnldsv** [comment]
This seems to come from the `user-select: none` that is applied inline.
My guess is that it's coming from the dragging lib

**Comment by susnux** [comment]
This is already fixed on master (version 8). It was fixed when we migrated from hammerJS to vueuse.
