### ISSUE TITLE
Tab wrapping inside of modal dialogs

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-vue#1591]
When a modal dialog is open, you can still tab out of it and access the elements behind it.

Also see focus management section in https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role and the part about wrapping.

Implementing this is rather tricky as it needs us to somehow disable all focussable controls outside of the modal.

There's a (future) way using the "inert" property, see https://github.com/WICG/inert
Need to check if browsers have caught up with this, or use this polyfill instead.

**Comment by PVince81** [comment]
might also be doable with https://github.com/posva/focus-trap-vue

**Comment by vanpertsch** [comment]
Solved with: https://github.com/nextcloud/nextcloud-vue/pull/2654
