### ISSUE TITLE
Settings modal padding and sizing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#1629]
Two issues which look a bit off in the settings modal, cc @ma12-co 
- [ ] `.app-settings` has padding which results in the content being cut off on the top and bottom as well as the scrollbar to float in the air
- [ ] The modal is just quite narrow, the width should be increased / adapted to look nice on desktop as well.

![](https://user-images.githubusercontent.com/925062/100621155-99119080-331f-11eb-9406-0f372dc445c3.png)

cc @GretaD for reference since you use it in the Mail app. :)

**Comment by GretaD** [comment]
@ma12-co will you work on this one? Should i take over?

**Comment by ma12-co** [comment]
I'll take care of this Greta!
