### ISSUE TITLE
Actions hover has wrong color

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#1665]
![Peek 2021-01-12 13-21](https://user-images.githubusercontent.com/213943/104314830-45779280-54da-11eb-8039-a17211b0a775.gif)

Top button is server css: (`#0E0E0E`)
https://github.com/nextcloud/server/blob/bfe87e501d83ff4dc9e5057c07464a598d951b4b/core/css/variables.scss#L39
Bottom button is Vue lib: `rgba(127, 127, 127, .25)`
https://github.com/nextcloud/nextcloud-vue/blob/6106e771f12a006c0b940db4ebc26aa6580b4ac6/src/assets/variables.scss#L47-L49

**Comment by raimund-schluessler** [comment]
Since `NcActions` uses `NcButton` internally, they look the same now. Legacy `button` elements might still differ though (and should probably simply be replaced by `NcButton`).
