### ISSUE TITLE
Replace linkifyjs with a smaller dep

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-vue#1679]
See https://github.com/nextcloud/nextcloud-vue/pull/1678#issuecomment-765902792.

It was reported that linkify-urls@2 works with Safari but the latest version 3.x breaks there.
linkify-urls takes less space than linkifyjs.

Maybe there's yet another library we could use instead ?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/nextcloud-vue/issues/1488

**Comment by PVince81** [comment]
Wow, ok. So it seems this Safari thing was known before but forgotten. And now remembered again.
