### ISSUE TITLE
[3.5.2] Popover - Trigger doesn't trigger anymore

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#1681]
When clicking on the trigger, nothing happens. 
`doesShowMenu` stays `false`. When setting to `true` via devTools, the popup appears.
See also: https://nextcloud-vue-components.netlify.app/#/Components/Popover

**Comment by PVince81** [comment]
I locally reverted the "popover-base-class" to "popover" and the popup now appears again.
But the weird thing is that despite displaying something, the "open" property isn't changing.
Hmm, I guess that property was added just to be able to open the popup externally (which is what I originally tested).

**Comment by PVince81** [comment]
using the `@appy-show` event fixes the issue, but nullifies the workarounds from https://github.com/nextcloud/nextcloud-vue/pull/831 that exist to prevent the popover to shake around before stabilizing around the trigger.

one hope would be to use the [onFirstUpdate hook](https://popper.js.org/docs/v2/lifecycle/#hook-into-the-lifecycle) of popper to only display the popover after the first positioning has finished

**Comment by PVince81** [comment]
This timeout thing feels pointless now... while I managed to make the show logic work for both cases, with a timeout with less than 1000 ms the repositioning glitch is still happening sometimes.

Next up, trying to find a way to hook into popper js while using v-tooltip's directive.

**Comment by PVince81** [comment]
Now I've tried to revert everything to the previous state.

I noticed that in the Talk app when the avatar menu is opening the first time, a scrollbar appears! This might explain the weird shifting of the popover. This means we might not need any workaround at all.

**Comment by PVince81** [comment]
Ah, forgot to mention that I managed to capture Popper's "onUpdate", but updating doShowMenu at that moment failed to make the popup appear. Maybe it happens too late, or the offscreen workflow is disturbing position calculation... Somehow it feels like this approach is a dead end.

Next I'll look into the scrollbar thing.

**Comment by PVince81** [comment]
Ohhhh... it seems before the initial show the tooltip just gets appended without position: absolute, and this is causing the scrollbars:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/277525/105837372-e8e2a000-5fce-11eb-8595-1b0adf3f4e59.png">

**Comment by PVince81** [comment]
I tried adding "overflow: hidden" on the body. While it makes the scrollbars disappear, it doesn't fix the repositioning glitch.
So it seems there are two glitches then and the popper/tooltip position gets updated three times:

1) First it appears in the body and causes the scrollbars
2) Then it appears somewhere around the trigger, but not at the correct position
3) Then it updates its position again, this time at the correct position

And all this only happens during the first time it's displayed.
Subsequent shows do not cause this weird dance.

**Comment by PVince81** [comment]
I've now raised https://github.com/nextcloud/nextcloud-vue/issues/1683 to continue trying to fix the glitch...

Here's a PR to revert the workaround which also fixes the regression so that the popover works like before: https://github.com/nextcloud/nextcloud-vue/pull/1685

**Comment by dartcafe** [comment]
@PVince81 Thanks for the fast reaction! 👍

**Comment by PVince81** [comment]
> @PVince81 Thanks for the fast reaction! +1

Thanks for noticing so quickly and sorry for the inconvenience :sweat_smile:
