### ISSUE TITLE
Clicking on an IFrame causes error in v-click-outside middleware

### ISSUE THREAD

**Issue by sam-19** [nextcloud/nextcloud-vue#1689]
## Description

The v-click-outside middleware in `@nextcloud/vue/dist/Mixins/excludeClickOutsideClasses.js` throws an error when clicking an embedded IFrame. The error message in browser console is
```
Uncaught TypeError: Cannot read property 'contains' of undefined
    at a.hasNodeOrAnyParentClass (excludeClickOutsideClasses.js:22)
    at a.clickOutsideMiddleware (excludeClickOutsideClasses.js:22)
    at r (v-click-outside.umd.js:1)
    at v-click-outside.umd.js:1
```
and the culprit seems to be this line in the source
https://github.com/nextcloud/nextcloud-vue/blob/4b9218a53378aa287fa750adc8525b5ed87f23d7/src/mixins/excludeClickOutsideClasses/index.js#L64

## Suggestion

The middleware method should first check if `node` has the property `classList` before calling `node.classList.contains()`.

**Comment by skjnldsv** [comment]
Damn, this is a high priority.
Let me fix asap

**Comment by u451f** [comment]
FYI this also affects OnlyOffice using the Community Server. Some documents cannot be opened even if they were created on the instance. Thanks for fixing it! Looking forward to the update :)

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by muhyal** [comment]
Hi, 

Any workarounds?

Thanks.
