### ISSUE TITLE
Multiselect ActionInput glitches when adding new tag

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/nextcloud-vue#1742]
Multiselect as ActionInput resets input for new tag when moving cursor away:

The first example in this video works as intended, the second example doesn't:

1. Place multiselect in an action dropdown
2. Enter the name of a new tag for creation
3. Move the mouse over the multiselect and out again
4. Result: entered tag name is gone

https://user-images.githubusercontent.com/75371007/110214023-9eade200-7edd-11eb-9600-dc40dbe9da51.mp4

Happens with v3.7.2

**Comment by marcelklehr** [comment]
Sorry, my initial bug report may not have been very helpful. Updated now.

**Comment by raimund-schluessler** [comment]
`NcActionInput` now uses the new `NcSelect` component for which this should work.
