### ISSUE TITLE
Item children icons/bubbles and indicator when hovering

### ISSUE THREAD

**Issue by weeman1337** [nextcloud/nextcloud-vue#179]
Have a look at this video:

![nav](https://user-images.githubusercontent.com/6216686/50537977-0f238080-0b68-11e9-8345-c35fa0adc290.gif)

I don't know if it's the intended behavior, but for me there is happening too much showing/hiding.  
I would change:
* Keep the icons/bubbles (black bubbles in the video) when hovering an item.
* When hovering a child item, keep the entire left side indicator (the blue bar).
  It actually only displays the one beside the child items.

I could do the changes. @skjnldsv what do you think?

**Comment by skjnldsv** [comment]
@weeman1337 seems like a good idea! Please open a pr and we'll see ;)
