### ISSUE TITLE
Compatibility with @nextcloud/capabilities@1.0.3

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/nextcloud-vue#1820]
Currently, the code seems incompatible with `@nextcloud/capabilities` in version `1.0.3` which is the most recent version. This manifests itself as a message similar to below

```
ERROR in ./node_modules/@nextcloud/vue/dist/Components/ActionInput.js
Module not found: Error: Can't resolve '@nextcloud/capabilities' in '/tmp/cb/node_modules/@nextcloud/vue/dist/Components'
 @ ./node_modules/@nextcloud/vue/dist/Components/ActionInput.js 235:80-114
 @ ./src/main2.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextcloud-cookbook@0.8.4 build: `node node_modules/webpack/bin/webpack.js --progress --config webpack.build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nextcloud-cookbook@0.8.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I tried to narrow down the problem and found it was related to a missing `package-lock.json` on our side due to a new checkout combined with the most recent version of `@nextcloud/capabilities` to be not detected as an (in)valid solution by `npm`.

This seems the same error as failing in the lining step of #1817. I open #1819 to have a quick workaround for now until this can be made compatible.

Honestly, I am unsure if this should be handled in the [upstream library](https://github.com/nextcloud/nextcloud-capabilities) or here. I can open another issue there if required/requested.

**Comment by juliushaertl** [comment]
1.0.3 seems to have missed the dist/ directory so I did a new release which should fix the incompatibility.
