### ISSUE TITLE
There is wide usage of the invalid tag autocomplete="nope"

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#1848]
We have many instances of `autocomplete="nope"` in our code, which is not valid HTML. Searching I could not find out where it’s coming from.

@nickvergessen mentioned that 'browsers are ignoring autocomplete="off"' (but probably also "nope"?) and "but nope looks like some 3rdparty tool".

The most helpful reference I could find to the reasons and a possibly better solution being proposed is at https://wordpress.org/support/topic/autocompletenope/#post-12647857 (and the included links).

Searching I could only find it in the compiled JS files:
![autocomplete nope](https://user-images.githubusercontent.com/925062/114854677-5db2c280-9de5-11eb-91ea-eed16a29101d.png)

**Comment by skjnldsv** [comment]
https://github.com/pluginkollektiv/antispam-bee/issues/280

**Comment by skjnldsv** [comment]
> It seems the new-password is the only working workaround for Chrome in the moment, at least according to a lengthy discussion here: bugs.chromium.org/p/chromium/issues/detail?id=914451

**Comment by Zodiac1978** [comment]
> I could not find out where it’s coming from.

It was part of this page:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

I do not know when it was changed, but back in 2017 it was there:
https://web.archive.org/web/20170127111604/https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

> In some cases, the browser will keep suggesting autocompletion values even if the autocomplete attribute is set to off. This unexpected behavior can be quite puzzling for developers. The trick to really forcing the no-autocompletion is to assign a random string to the attribute, for example: `autocomplete="nope"`

**Comment by ChristophWurst** [comment]
This does not seem to come from this repo, or it has been removed.
