### ISSUE TITLE
Avatar errors with username is null

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#1856]
The `usernameToColor` function in the `Avatar` component sometimes fails with this error in the Calendar app:

```
TypeError: username is null
    usernameToColor Avatar.js:3552
    avatarStyle Avatar.js:509
    VueJS 4
    render Avatar.js:2087
    VueJS 5
vue.runtime.esm.js:1888
    VueJS 96
    tasks calendars.js:376
    appendTasksToCalendar calendars.js:371
    wrappedMutationHandler vuex.esm.js:844
    commitIterator vuex.esm.js:466
    commit vuex.esm.js:465
    _withCommit vuex.esm.js:624
    commit vuex.esm.js:464
    boundCommit vuex.esm.js:409
    getTasksFromCalendar calendars.js:658
    wrappedActionHandler vuex.esm.js:851
    dispatch vuex.esm.js:516
    boundDispatch vuex.esm.js:406
    fetchTasks App.vue:98
    fetchTasks App.vue:98
    beforeMount App.vue:88
    VueJS 16
    <anonym> main.js:74
    <anonym> tasks-main.js:204201
    <anonym> tasks-main.js:204203
```

The `Avatar` component is used like this: https://github.com/nextcloud/calendar/blob/master/src/components/Shared/CalendarPickerOption.vue#L34-L41
It seems the avatars are rendered correctly in the end.

Happens with nextcloud-vue latest master 5653d194c4e8653b0f9f8b601359c47aa25899a2

**Comment by raimund-schluessler** [comment]
I turns out I was using it wrong. When no user was found, I set the `display-name` prop to `null`, but the `Avatar` component only checks for `undefined`.

When instead providing `undefined`, no error is thrown, see https://github.com/nextcloud/tasks/pull/1576. Hence, I close this issue.

However, I wonder whether the `Avatar` component should also check for `null` and treat it as `undefined`? @skjnldsv

**Comment by skjnldsv** [comment]
> However, I wonder whether the `Avatar` component should also check for `null` and treat it as `undefined`? @skjnldsv

Sure, I see no issues with that :thinking:
