### ISSUE TITLE
AppNavigation counter have wrong right margin

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#1868]
![image](https://user-images.githubusercontent.com/14975046/115358850-5eb96a80-a1be-11eb-9d8b-4f77dbfc837b.png)

**Comment by ma12-co** [comment]
I think that the wrapper (AppNavigationItem) should have some padding right in this case, because every use case needs slightly different tweaking and if we have margin to the counter, the moment we want to use this elsewhere we're going to have to v-deep to change the it.

**Comment by skjnldsv** [comment]
:shrug: I think it used to have a right padding at all time yes :)
