### ISSUE TITLE
Nextcloud Server compatibility range 

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#196]
Changes like https://github.com/nextcloud/nextcloud-vue/pull/193 bring up the concern that the library might only be compatible with Nextcloud 15+. Regardless of that being the case, we have to think about compatibility ranges so that devs know which Nextcloud version they can use this library for.

**Comment by ChristophWurst** [comment]
Communication and documentation. I don't think there's a technical way.

**Comment by skjnldsv** [comment]
@ChristophWurst fail hard after checking the nextcloud server version the app is running against?

**Comment by ChristophWurst** [comment]
Change the font to comic sans would have been my preference but I would also be fine with a "best effort" principle and not fail hard. If it works it works. If it breaks then the dev chose the wrong version of this library.

Just to be clear: When we change stuff in this lib I want to know what versions this should work with. Changes like #193 give the impression that we can't use the lib on Nextcloud 15 anymore. Which would be a bummer for me as I still have maintained apps that use it where I would like to push new versions.

I do not care much about devs using this lib for an incompatible version of Nextcloud.

All I want is a table in the readme where I can see the version of this lib and what range of Nextcloud this works with. Like 0.5.x would be 15 and 16 I assume. If we add breaking changes then 0.6 will be 16+ and so on. Does that make sense?

**Comment by skjnldsv** [comment]
For #193 the only issue is the font loading. Worst case scenario the 4 arrows will not be shown if the font is not loaded. So I'd say this is compatible with 15 (well 15.0.1, but hey, people will upgrade I assume)

I'm okay with just creating a table for the compatibility.

**Comment by ChristophWurst** [comment]
Yeah, that was just an example.

Let's document what we target (I assume that is 15 and 16 right now) and make sure all featues added to this library work with those :)
