### ISSUE TITLE
4.0.1 still requries a global appName

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#2040]
In the v4.0.1 from the npm registry this code shows: ``paneConfigKey:{type:String,default:appName}``. Therefore you still get a ``ReferenceError: appName is not defined`` if you don't have that special global variable.

@skjnldsv did you possible not build the lib before the `npm publish`? The code was definitely fixed in https://github.com/nextcloud/nextcloud-vue/pull/2028

**Comment by skjnldsv** [comment]
I didn't tag it, Marco did.

**Comment by skjnldsv** [comment]
Let's tag 4.0.2

**Comment by ChristophWurst** [comment]
Works :rocket: :shipit:
