### ISSUE TITLE
Add a timezone aware date time picker

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#2088]
Henlo friends,

I'm working on a feature in Mail where I need to kind of "mimic" the new event dialog from Calendar. In theory it's just a text input and two date pickers. But in reality there is some hidden complexity with picking the right timezone for the event to be created.

Long story short I would like to bring the timezone aware picker to this shared library. Essentially this means I will make the existing component from Calendar a bit more reusable, move it over, import it there again and also use it in Mail.

Would this be acceptable? If not I'll have to branch off into a small calendar vue component lib. If possible I'd try to avoid that but no hard feelings :)

The following code would move here
* [x] #2094
* [x] #2096

https://github.com/nextcloud/calendar/blob/master/src/components/Shared/DatePicker.vue (but hopefully simplified) or an integration into our existing datepicker

**Comment by dartcafe** [comment]
Maybe we could also improve it to the way, it works in polls.  The code is here: https://github.com/nextcloud/polls/blob/master/src/js/components/Options/OptionsDateAdd.vue

This took a lot of tweeks to get it working this way. And maybe there is a more elegant way. 
![picker](https://user-images.githubusercontent.com/26707476/124797414-8369e680-df52-11eb-9cff-fca7e19ffb82.gif)

**Comment by ChristophWurst** [comment]
it's done :shipit:
