### ISSUE TITLE
Improve Moment.vue, e.g. to get short timestamps

### ISSUE THREAD

**Issue by GretaD** [nextcloud/nextcloud-vue#2089]
To show the time in different apps, we use Moment.vue, which we create "locally" for a certain app. We dont have a general component for that. Would be nice if we have a nc/vue component and also to improve a bit the way we show the time/year.

Considering other clients out there, we do it a bit differently. We show minutes, hours, years as a full word.

Would be nice if we only show m for minutes, and then hours as _h_, maybe up to 5h or 10h and then we show the exact time instead of counting 24h. For the previews day, we show date and month (i.e Jul 6) and for year ( 11/04/2020 )

**Comment by jancborchardt** [comment]
@marcoambrosini this is what we talked about regarding timestamps. :)

**Comment by marcoambrosini** [comment]
Moment is deprecated but we could definitely have our own component for this or find some other library and create our own wrapper.

**Comment by susnux** [comment]
Sounds like #13 ?
