### ISSUE TITLE
Emoji picker not localized

### ISSUE THREAD

**Issue by ensag-dev** [nextcloud/nextcloud-vue#2093]
## Steps to reproduce
1. Open a conversation with Talk
2. Open the Emoji picker
3. All the texts are in English

### Expected behaviour
The screen texts should be localized and localizable on Transifex

### Actual behaviour
It's all in English

## Browser

Firefox

**Comment by Mejans** [comment]
You might use Mastodon's translations:
https://github.com/tootsuite/mastodon/

**Comment by Pytal** [comment]
@ensag-dev I can't seem to reproduce this, I get correct translations in the picker

![image](https://user-images.githubusercontent.com/24800714/124989003-8b2d9780-dff3-11eb-88ec-819400ec8cf4.png)

Could you add more details to your reproduction steps?

**Comment by ensag-dev** [comment]
I don't have it showing in Occitan =/
Maybe the main project has to be translated?

**Comment by Pytal** [comment]
@ensag-dev that's correct, we don't yet have translations for these but if you'd like to you could contribute translations by following these instructions https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations :)

**Comment by ensag-dev** [comment]
yes but I didn't find the component for the emoji picker on Transifex

**Comment by Pytal** [comment]
> yes but I didn't find the component for the emoji picker on Transifex

You can find the strings that need to be translated (e.g. "Frequently used") at this link https://www.transifex.com/nextcloud/nextcloud-vue/viewstrings/#oc/l10n-messages-pot--master/194579905

**Comment by ensag-dev** [comment]
Thanks @Pytal !
I can close it now
