### ISSUE TITLE
Dialog component

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#210]
Now that we have @juliushaertl's awesome new modal design in https://github.com/nextcloud/firstrunwizard

![peek 2019-01-09 14-14](https://user-images.githubusercontent.com/3404133/50903609-8a195080-141e-11e9-9c91-baa0394d2c05.gif)

I think we should have this one here.
That way I can use the same design for the universal preview app :)

@ChristophWurst @juliushaertl thoughts?
What shall we have on this component? Arrows that trigger a method provided by the app? a function that return an element like we want to do with the sidebar?

**Comment by juliushaertl** [comment]
We could also just have a list of components passed to the dialog, then we could let vue do its magic with https://vuejs.org/v2/guide/transitions.html#Transitioning-Between-Components

**Comment by skjnldsv** [comment]
@juliushaertl shall we have this on the component or on the app that uses the component?
I would go for the app to keep this simple I think.
We could just have a slot in the modal and let the app do the rest?

**Comment by juliushaertl** [comment]
> I would go for the app to keep this simple I think.
> We could just have a slot in the modal and let the app do the rest?

Sounds fine to me. Yes, let's not overcomplicate things that are already complex enough :wink:
