### ISSUE TITLE
fetchUserStatus is called even if userId is null

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#2155]
The Avatar component creates requests to the server like this one:
```
/nextcloud/ocs/v2.php/apps/user_status/api/v1/statuses/{userId}
```
which obviously fail since userId is not replaced. I guess this can happen when userId is actually null (need to check).

**Comment by Pytal** [comment]
We've got multiple checks in place already https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Avatar/Avatar.vue#L420-L422 🤔

**Comment by raimund-schluessler** [comment]
> 
> 
> We've got multiple checks in place already https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Avatar/Avatar.vue#L420-L422 🤔

Sorry, I was wrong. It is not the `Avatar` component, but the `ListItemIcon` component which causes this (I get this error when searching for users to share to in Calendar or Tasks). In `ListItemIcon` the check if `this.user` has a value is missing:
https://github.com/nextcloud/nextcloud-vue/blob/1194bd8970ec6a9434279034e7ced89ed4c687da/src/components/ListItemIcon/ListItemIcon.vue#L224-L226

I think it would be good to check for a valid `userId` in the `userStatus` mixin:
https://github.com/nextcloud/nextcloud-vue/blob/dc19014f78cdeb67b3fbfc512c05470a0d89681c/src/mixins/userStatus.js#L45

So we don't have to do it in every function using `fetchUserStatus`.

**Comment by Pytal** [comment]
@raimund-schluessler agreed :)
