### ISSUE TITLE
Highlight duplicates characters

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#2191]
When using the following example, the highlight component would actually duplicate the matched search string and printing `oooo` instead of `ooo`:

```
<Highlight text="ooo" search="oo" />
```

![image](https://user-images.githubusercontent.com/3404133/131112490-57a48b5b-7886-4357-b315-dacfdcb11c1e.png)

Seems like quite an edge case where the range would match both the first and last two occurences of "oo" in https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Highlight/Highlight.vue#L122

**Comment by raimund-schluessler** [comment]
I think the problem lies here:
https://github.com/nextcloud/nextcloud-vue/blob/13ff43dc8f0088ecac631267d4963a94985cc34a/src/utils/FindRanges.js#L41

We only increment `index` by one, instead of by the length of the `search` string. That way the same string can be matched multiple times which does not make sense, I guess.

**Comment by raimund-schluessler** [comment]
The question is how should we highlight such cases. E.g. you have the text `ananas` (pineapple in every other language than English :wink) and you search for `ana`, would you expect it to be highlighted
- ***ana***nas
- an***ana***s
- or ***anana***s ?

@nextcloud/designers 🙈

**Comment by nimisha-vijay** [comment]
Honestly I think just the first match is enough. an***ana***s looks strange because it looks like it's deliberately skipping the first match and ***anana***s looks like it's matching ***anana*** and not ***ana***.

**Comment by raimund-schluessler** [comment]
Yes, an***ana***s was not really an option, mainly showed for the sake of completeness 🙂

I also prefer the first option.
