### ISSUE TITLE
Problem to print the value from Multiselect component

### ISSUE THREAD

**Issue by zak39** [nextcloud/nextcloud-vue#2192]
Hi :slightly_smiling_face: 

I am using the Multiselect component in an app project for one customer.

My customer use Firefox ESR and we have found a bug with this component.

From Firefox ESR, when I selected one option, the value is updated in back-end side and not front-end side.

First, here is a part of my code :

```javascript
<Multiselect
	class="quota-select"
	:disabled="$root.$data.isUserGeneralAdmin === 'false'"
	:placeholder="t('workspace', 'Set quota')"
	:taggable="true"
	:value="$store.state.spaces[$route.params.space].quota"
	:options="['1GB', '5GB', '10GB', 'unlimited']"
	@change="setSpaceQuota"
	@tag="setSpaceQuota" />
```

And there is the result from Firefox ESR 78.13 :

![pb-set-quota-esr](https://user-images.githubusercontent.com/28636549/131138992-e152809d-1bc7-4810-bec5-1ed5f6c5c06d.gif)

Then, the result from Firefox 91.01 :

![set-quota-no-esr](https://user-images.githubusercontent.com/28636549/131139022-cf8c7115-9b7d-460e-8276-086c679844d3.gif)

I don't know where is the problem... :thinking:

**Comment by susnux** [comment]
Multiselect was removed. Can not reproduce with NcSelect.
