### ISSUE TITLE
Make modal fullscreen on mobile

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/nextcloud-vue#2215]
as agreed upon in the design reviews, modals should span the whole width and height if the screen is narrow.
Let's talk about the specifics / breakpoints

cc @jancborchardt @nimisha-vijay @skjnldsv  @szaimen

**Comment by szaimen** [comment]
I think this is already implemented in nextcloud-vue 5.0.0 :)
You can check out the different sizes in the docs:
https://nextcloud-vue-components.netlify.app/#:~:text=show%20modal
(just modify the code below to one of the available sizes and you can see the result by changing the window size...

**Comment by szaimen** [comment]
See 
https://github.com/nextcloud/nextcloud-vue/pull/2126
https://github.com/nextcloud/nextcloud-vue/pull/2170
https://github.com/nextcloud/nextcloud-vue/pull/2197

**Comment by marcoambrosini** [comment]
This is from the docs

<img width="429" alt="Screenshot 2021-09-07 at 14 37 02" src="https://user-images.githubusercontent.com/26852655/132345635-49e7e0eb-b191-4311-bbd1-e72bc5f0914d.png">

**Comment by szaimen** [comment]
> This is from the docs

jep, prompt is meant for popups that shall be small. Any other size from medium to full will be full screen on mobile

**Comment by szaimen** [comment]
See https://github.com/nextcloud/nextcloud-vue/pull/2170#issuecomment-900687792 for some examples.

**Comment by szaimen** [comment]
Citing the docs:
```
		/**
		 * Defines the modal size
		 * Default is 'normal'
		 * Available are 'prompt', 'small', 'medium', 'normal', 'large' and 'full'
		 * All sizes except 'prompt' and 'small' change automatically to full-screen on mobile
		 */
```

**Comment by marcoambrosini** [comment]
🤐 😅
