### ISSUE TITLE
AppContent: "loading" in app-navigation

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-vue#227]
As far as I can see, there is no easy way to add the `loading` CSS class (loading animation) for the whole app-navigation when using the component `AppContent`.

Maybe, we should add a new parameter for passing CSS class names for app-navigation? Or is there another way to realize this with means of Vue?

Edit: same applies to template slot `content`.

**Comment by skjnldsv** [comment]
I agree! I had the same discussion with @ChristophWurst
