### ISSUE TITLE
Version 4.2.0 breaks CI (and builds)

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#2302]
See https://github.com/nextcloud/polls/pull/1999/checks?check_run_id=3762418281
Problem on my side??? 

```
ERROR in ./node_modules/linkify-string/index.js 1:0-56
Module not found: Error: Can't resolve 'linkifyjs/lib/linkify-string' in '/home/runner/work/polls/polls/node_modules/linkify-string'
resolve 'linkifyjs/lib/linkify-string' in '/home/runner/work/polls/polls/node_modules/linkify-string'
  Parsed request is a module
  using description file: /home/runner/work/polls/polls/node_modules/linkify-string/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/runner/work/polls/polls/node_modules/linkify-string/node_modules doesn't exist or is not a directory
      /home/runner/work/polls/polls/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/runner/work/polls/polls/node_modules
        /home/runner/work/polls/polls/node_modules/linkifyjs doesn't exist
      /home/runner/work/polls/node_modules doesn't exist or is not a directory
      /home/runner/work/node_modules doesn't exist or is not a directory
      /home/runner/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./node_modules/@nextcloud/vue/dist/ncvuecomponents.js 150:408-433
 @ ./src/js/main.js 34:0-41 53:25-32
```

**Comment by dartcafe** [comment]
Yes, saw this, but I was sure we are not affected, since we don't use inkifyjs. Do the other project use it as an own dependency?

**Comment by raimund-schluessler** [comment]
> 
> 
> Do the other project use it as an own dependency?

Some do still use it (e.g. Calendar) some don't (e.g. Tasks). The update to 4.2.0 works in both cases.

**Comment by juliushaertl** [comment]
I had the same case in the bump on richdocuments where node12/npm6 was still in use in the CI. 

@dartcafe It seems you are using node 14 but still npm 6 on polls, so maybe you could try to bump npm as well.

`@nextcloud/vue` marks all node modules as externals and iirc npm7 changed the way that peer dependencies would be installed now automatically.

**Comment by raimund-schluessler** [comment]
Might be a good time to move to the shared webpack config https://github.com/nextcloud/webpack-vue-config and the common github actions https://github.com/nextcloud/.github for polls as well.

**Comment by dartcafe** [comment]
> @dartcafe It seems you are using node 14 but still npm 6 on polls, so maybe you could try to bump npm to 7 as well.

Yep. It seems, that node14 is using npm6 by default, node16 uses npm7. I forced the action to use npm 7; seems to work...
