### ISSUE TITLE
Should we initialise the emoji picker frequently used emojis differently?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#2360]
So I always wondered why my favorite emojis beasically never show up, when picking an emoji for the status.
Now after I took the time to analyze the problem, I saw that I do in fact have some emojis in the list, but they basically never make it to the top.

The problem is the way the empty state is initialized:
https://github.com/serebrov/emoji-mart-vue/blob/master/src/utils/frequently.js#L3-L20
https://github.com/serebrov/emoji-mart-vue/blob/master/src/utils/frequently.js#L44-L56

This let's you start with the following list:
```json
{
  "+1": 16,
  "grinning": 15,
  "kissing_heart": 14,
  "heart_eyes": 13,
  "laughing": 12,
  "stuck_out_tongue_winking_eye": 11,
  "sweat_smile": 10,
  "joy": 9,
  "scream": 8,
  "disappointed": 7,
  "unamused": 6,
  "weary": 5,
  "sob": 4,
  "sunglasses": 3,
  "heart": 2,
  "poop": 1,
}
```

The frequently shown list is 20 long by default, so basically until you have more than 4 emojis picked more than 4 times, the list will be the default emojis first and then your stuff. For your favorite emoji to reach the top, you have to pick it 16+ times.

After all this time with status on our company instance the values are for me:
```json
{
    "+1": 16,
    "grinning": 16,
    "kissing_heart": 14,
    "heart_eyes": 14,
    "laughing": 12,
    "stuck_out_tongue_winking_eye": 11,
    "sweat_smile": 10,
    "joy": 9,
    "scream": 9,
    "disappointed": 8,
    "unamused": 6,
    "weary": 6,
    "lacrosse": 6,
    "bridge_at_night": 6,
    "running_shirt_with_sash": 6,
    "musical_note": 6,
    "sob": 5,
    "woozy_face": 5,
    "dragon_face": 5,
    "robot_face": 5,
    "calling": 4,
    "tophat": 4,
    "…146 emojis in total with": "<=3"
}
```
From those emojis the top 12 are still default, all of them with a maximum of 1 additional usage to the default values from above:
```json
{
    "+1": 16, // 16
    "grinning": 16, // 15
    "kissing_heart": 14, // 14
    "heart_eyes": 14, // 13
    "laughing": 12, // 12
    "stuck_out_tongue_winking_eye": 11, // 11
    "sweat_smile": 10, // 10
    "joy": 9, // 9
    "scream": 9, // 8
    "disappointed": 8, // 7
    "unamused": 6, // 6
    "weary": 6, // 5
 …
}
```

In total I used 327 emojis since the last time the website data was purged, but 136 points are from the default list.

I would therefor vote to manually populate the default list in the local store when opening the emoji picker with something that is a bit more sane and does not take years to get replaced, e.g.:

```json
{
  "+1": 4,
  "grinning": 4,
  "kissing_heart": 4,
  "heart_eyes": 4,
  "laughing": 3,
  "stuck_out_tongue_winking_eye": 3,
  "sweat_smile": 3,
  "joy": 3,
  "scream": 2,
  "disappointed": 2,
  "unamused": 2,
  "weary": 2,
  "sob": 1,
  "sunglasses": 1,
  "heart": 1,
  "poop": 1,
}
```

We could also ask @serebrov if a patch for that would be accepted upstream.

**Comment by serebrov** [comment]
I agree, it makes sense to lower counts for the `DEFAULTS` list.

The [frequently code](https://github.com/missive/emoji-mart/blob/master/src/utils/frequently.js) looks almost the same in the original React component and I guess the reason for `DEFAULTS` was to demo the feature of the component while in practise it makes the feature less useful.

An alternative might be to start without the default list and just accumule what the user selects (we could still have an option to pass a default list via `Picker` options).

**Comment by nickvergessen** [comment]
Send a PR with my proposal in https://github.com/serebrov/emoji-mart-vue/pull/141

**Comment by serebrov** [comment]
@nickvergessen Thanks! I merged it and published version `10.1.0`.

**Comment by nickvergessen** [comment]
Oh, we are still on 7.0.7
Let me check if there were bigger issues with the update or if it is fast forward

**Comment by nickvergessen** [comment]
PR is in https://github.com/nextcloud/nextcloud-vue/pull/2366 but it breaks due to some global css from server.
Issue is being discussed here: https://github.com/nextcloud/server/issues/29591 but prevents merging until then

**Comment by Valdnet** [comment]
The choice of Emoji from the list should also be changed.

Now it is like this: When selecting an Emoji the window automatically closes, which means that in order to select a second Emoji you have to reopen the Emoi window and select it again. This makes it difficult for the user to input several of the same or different Emoji on one line.

The Emoji window should close only after clicking next to the window or clicking the "Close" button.

Or is it a spam filter (joke) 😁?

**Comment by Valdnet** [comment]
If changes are made, the text string `Frequently used` should also be changed to `Recently used`.

https://github.com/nextcloud/nextcloud-vue/blob/551e5562a8c23b88dd177655562afacbc9861e42/src/components/EmojiPicker/EmojiPicker.vue#L180

**Comment by nickvergessen** [comment]
No, it's still frequently used, as we just limit the default frequencies basically.
But if you use one emoji 100 times and then 20 others, the 100-used emoji will still be top in frequent, although it's not used in the 20 recent. so that is correct

**Comment by Valdnet** [comment]
> so that is correct

Now yes, but if we make the changes you describe above that Emoji should display the ones that were last selected (I think I understand correctly), then it won't be the correct text string anymore.

**Comment by nickvergessen** [comment]
We don't make it recently, we just change(d) the numbers, so they don't start with 16 usages by default, but a maximum of 5

**Comment by Valdnet** [comment]
So the text string is fine 👍. Consider closing the Emoji window. Currently it is a bit of a discouragement for the user to use them due to the fact that the Emoji window has to be opened multiple times to use more than one Emoji 😉.
