### ISSUE TITLE
"Download and enable" button font color

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/nextcloud-vue#2371]
Steps:

1. Select "Apps" from the menu.
2. Search for an application to install.

The color of the font for the button in the sidebar is not visible. Change the color from white to black.

![obraz](https://user-images.githubusercontent.com/47037905/142465394-35a20078-917f-47cd-9a6b-9a2220413868.png)

App:
Nextcloud 22.2.3 and 23.0.0 RC2

**Comment by Valdnet** [comment]
@marcoambrosini Can you fix it?

The problem may be with this code:

https://github.com/nextcloud/nextcloud-vue/blob/89161d45b2c57ef0feb03ea692eb8d363f4f197d/styleguide/assets/server.css#L1506-L1513

**Comment by Valdnet** [comment]
After removing `:not(.button-vue)`, appearance is back to normal.

@marcoambrosini Will changing this code affect other buttons that should be displayed differently?

**Comment by susnux** [comment]
Fixed with https://github.com/nextcloud/server/pull/29905
