### ISSUE TITLE
App sidebar tab content height does not let it's child to fill the content

### ISSUE THREAD

**Issue by kiranparajuli589** [nextcloud/nextcloud-vue#2430]
## Problem Description
Currently the app sidebar tab content has height defined as:
```css
.app-sidebar__tab {
	...
	min-height: 100%; // fill available height
	max-height: 100%; // scroll inside
        ...
}
```
https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppSidebarTab/AppSidebarTab.vue#L89-L90

The CSS definition likewise contains nice comments, but, in reality, this limits the inner child to fill the tab's content _(section)_ height.

## Actual Behaviour
![problem](https://user-images.githubusercontent.com/39373750/147904649-6b6f2503-d04c-4607-b5f6-a219858c90ac.gif "Problem Definition")

If we have to show some empty messages like this or have to center elements within the tab section, we've to add a hard-coded margin or padding to the element which is really not cool in terms of responsiveness.

Even if we try with display flex for the `section.app-sidebar__tab` child, the content is not fit with the `section` height.

## Expected Behaviour
If we just set the height of the sidebar__tab to `100%` everything just works fine and now we can fill the content inside the child elements.
![Peek 2022-01-03 12-18](https://user-images.githubusercontent.com/39373750/147904743-7b02de7c-ed66-4f0e-8b94-8dba4e38eebb.gif "The Solution")

Even the scrolling works just as fine:

![scrolling](https://user-images.githubusercontent.com/39373750/147904807-9b516301-be02-43b0-8642-319af76ee082.gif "Scrolling inside the sidebar tab content")

**Comment by raimund-schluessler** [comment]
As a workaround you can just set `height: 100%;` in your app like so:
https://github.com/nextcloud/tasks/blob/master/src/views/AppSidebar.vue#L975-L979

**Comment by kiranparajuli589** [comment]
> As a workaround you can just set `height: 100%;` in your app like so: https://github.com/nextcloud/tasks/blob/master/src/views/AppSidebar.vue#L975-L979

hmmm...overwriting the sidebar CSS from the app! thank you for the tip!
