### ISSUE TITLE
Allow using a different icon than the Cog in `AppNavigationSettings`

### ISSUE THREAD

**Issue by azul** [nextcloud/nextcloud-vue#2452]
In collectives we would like to use the `AppNavigationSettings` component for a trash of deleted collectives:
![using settings for trash](https://gitlab.com/collectivecloud/collectives/uploads/de221f36c3339a014f0853c9834059af/recording.gif)

Right now this requires a hack to display another icon.

Let's move the icon into a slot so it's easy to replace.

**Comment by mejo-** [comment]
To my knowledge there's several other apps that could utilize this, at least Calendar, Tasks and Files also have their trash down there.

**Comment by raimund-schluessler** [comment]
> To my knowledge there's several other apps that could utilize this, at least Calendar, Tasks and Files also have their trash down there.

But these apps show their trash bin in a separate view (a modal for Calendar and Tasks, directly in the files view for Files) and not embedded in the AppNavigation sidebar. They won't profit from being able to replace this icon.

So I wonder if it is a good decision to show deleted collectives there. I guess @nextcloud/designers should comment here.

**Comment by skjnldsv** [comment]
> In collectives we would like to use the `AppNavigationSettings` component for a trash of deleted collectives:

Why not use the AppNavigationItem pinned at the bottom?

**Comment by mejo-** [comment]
> Why not use the AppNavigationItem pinned at the bottom?

The thing is that we need the Collectives settings to be expandable. It currently only has one setting (the folder where to mount your collectives) and a modal would be overkill for this, no?

> We could also think about combining Settings and deleted items in the modal, but not sure if we find any wording which makes the "Deleted items" discoverable enough. So maybe clicking on either could just open the same modal, but go to a different # link.

That could be an option.

Anyway, feel free to close this issue if you think it's not the right approach :wink:

**Comment by jancborchardt** [comment]
I’d say if we go with the approach of 1 modal for both in Collectives, then we don’t need the custom icon. :)
