### ISSUE TITLE
Expose v-tooltip as component

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#248]
Right now if an app uses v-tooltip the source is actually contained twice in the bundle, one time in the nextcloud vue-components and one time for the actual use inside of the app bundle.

Maybe it would make sense to just expose the tooltip lib we use in the components, so apps can use that as well.

**Comment by juliushaertl** [comment]
Not sure if enabling tree shaking would help with that, but right now it seems that the v-tooltip version from the components and the app are not properly deduplicated.

**Comment by skjnldsv** [comment]
Do we have a theme for the tooltips?

**Comment by juliushaertl** [comment]
I think it currently uses the server shipped styles.

**Comment by skjnldsv** [comment]
Ah yes, I added the style last year: https://github.com/nextcloud/server/commit/f0586b2eb15651e358b6ebf47b230bc7965dde35#diff-c3f946c8e6c04477a1300e2025f7c3bd

**Comment by juliushaertl** [comment]
Done with #259
