### ISSUE TITLE
Update splitpanes package to 2.3.8

### ISSUE THREAD

**Issue by zak39** [nextcloud/nextcloud-vue#2489]
Hi everyone :slightly_smiling_face: 

I read your package.json file : https://github.com/nextcloud/nextcloud-vue/blob/6c7ef0b5e5122888753ecc2cfbdfd56e57852ff4/package.json#L55

And I noted your dependency splitpanes is to 2.3.6 version. Hovewer, the version 2.3.8 is available here :point_right: https://www.npmjs.com/package/splitpanes/v/2.3.8

But, your dependabot has already updated : https://github.com/nextcloud/nextcloud-vue/issues/new?permalink=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fnextcloud-vue%2Fblob%2F6c7ef0b5e5122888753ecc2cfbdfd56e57852ff4%2Fpackage.json%23L55

It's very strange :thinking:

**Comment by raimund-schluessler** [comment]
Take a look at `package-lock.json`. There the current version is installed:
```
		"splitpanes": {
			"version": "2.3.8",
			"resolved": "https://registry.npmjs.org/splitpanes/-/splitpanes-2.3.8.tgz",
			"integrity": "sha512-eM/qZ1v7U5BMV8FQR7oeqVlllz3sTGTm0//g/eJMa0hZ4s+A1VK68j26FWzcaVlw2P5+dCXk7/X6ZRjjwcbrgw=="
		},
```

The `^2.3.6` just means it will install the latest minor version, see https://docs.npmjs.com/about-semantic-versioning
