### ISSUE TITLE
[BITV/A11Y] EmptyContent accessibility

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-vue#2500]
* ~Fix empty h2 in Dashboard widgets with EmptyContent view (an opportunity to test the warning below)~ h2 elements now render conditionally only when a title is passed
* ~Image should not have `role="img"`, but ideally be an img with `alt=""`~ Only accessible icons from https://github.com/robcresswell/vue-material-design-icons are accepted

**Comment by Pytal** [comment]
### Requires

- [ ] https://github.com/nextcloud/nextcloud-vue/pull/2867

**Comment by Pytal** [comment]
Since a title is required for the EmptyContent component, how would the first checkbox be fixed @juliushaertl

**Comment by Pytal** [comment]
Since a title is required for the EmptyContent component but is not added in dashboard widgets as designed probably, how would the first checkbox be fixed @juliushaertl

**Comment by juliushaertl** [comment]
I'd say we can just not render the h2 in the EmptyContent if the slot is empty.
