### ISSUE TITLE
Enable tree shaking

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#251]
The size of the vue components bundle is pretty big already, mainly caused by those three libraries:

| Library | Stat size | Parsed size |
|---|---|---
| v-tooltip | 184KB | 55KB |
| vue-multiselect | 44KB | 44KB |
| datepicker | 40KB | 40KB |

We should look into enabling [webpack tree shaking](https://webpack.js.org/guides/tree-shaking/) to allow apps to just include the code that is actually used. So if an app doesn't use the multiselect or datepicker this could save us quite some KBs.

Bundle size treemap:
![image](https://user-images.githubusercontent.com/3404133/52773268-d74e9a80-303a-11e9-98ac-2d7dba6945fd.png)

I tried to get this working a bit, but couldn't come up with something unforunately. @skjnldsv @ChristophWurst

**Comment by skjnldsv** [comment]
@juliushaertl I think it is actually enabled by default on production?

since we already support the individual import with `import { xxx } from ` the app's webpack config should already do the trick?
Let me try

**Comment by juliushaertl** [comment]
At least for me the ncvuecomponents.js size was always the full in apps.

**Comment by skjnldsv** [comment]
@juliushaertl I saw various libraries also outputting individual js files per component and allowing the import like so: `import { PopoverMenu } from 'nextcloud-vue/dist/components'`

**Comment by juliushaertl** [comment]
Yeah unfortuantely none of them seems to use webpack, so we cannot easily compare what they are doing :wink:

**Comment by skjnldsv** [comment]
https://github.com/vuematerial/vue-material/blob/dev/build/lib/webpack.js ?

**Comment by juliushaertl** [comment]
> I saw various libraries also outputting individual js files per component and allowing the import like so: `import { PopoverMenu } from 'nextcloud-vue/dist/components'`

I looked a bit more into how those libraries are doing that, but it seems they all create individual entry points for each component, so there is one all-in-one bundle as well as one for each component.

**Comment by skjnldsv** [comment]
@juliushaertl yes exactly! Would that be an issue? Nothing come to my mind :thinking:

**Comment by juliushaertl** [comment]
Ok, I digged a bit more into that. In general it seems that webpack would need to provide a way to export proper es modules, which is currently not supported: https://github.com/webpack/webpack/issues/2933

The general recommendation is to use rollup for bundling libraries (https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html) but not sure if we can move that over easily.

**Comment by skjnldsv** [comment]
Shall we close?

**Comment by juliushaertl** [comment]
Yep should be fine now
