### ISSUE TITLE
Modal close button missing after 5.x

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#2529]
This seems to occur in viewer as well as on the documentation examples:

https://nextcloud-vue-components.netlify.app/#/Components/Modal

For some reason the single entry item for rendering the ActionButton seems to be missing:

![Screenshot 2022-03-01 at 18 54 29](https://user-images.githubusercontent.com/3404133/156222477-4dd6f00f-e055-4366-a8dc-625d3be87474.png)
l

**Comment by juliushaertl** [comment]
![Screenshot 2022-03-01 at 19 35 10](https://user-images.githubusercontent.com/3404133/156228500-0b5d8344-aa59-4fad-b371-8170cfbf0eef.png)

**Comment by juliushaertl** [comment]
@skjnldsv Any idea why that could happen? Found this when guiding @vinicius73 a bit through our frontend development stack.

Seems to come from https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Actions/Actions.vue#L463 but I cannot really explain why this only happens in the modal, while the same combination of a single ActionButton works fine outside. 

Further this was introduced somewhere between 4.4.0 and 5.0.0.

**Comment by vinicius73** [comment]
It is related to the last release of Vue
https://github.com/vuejs/vue/pull/12104
https://github.com/vuejs/vue/issues/12102

Probably the slots are not yet available in the `created` life cycle, because of that the reactivity of `Actions.vue` does not detect the icon slot.

**Comment by skjnldsv** [comment]
> It is related to the last release of Vue
> [vuejs/vue#12104](https://github.com/vuejs/vue/pull/12104)

seems to be fixed with 2.6.14 which we are using :thinking:

**Comment by juliushaertl** [comment]
Bisecting showed https://github.com/nextcloud/nextcloud-vue/pull/2385 as the commit causing the regression. Might be that the upstream change from functional to regular components now causes the rendering to happen earlier when the slot details are not fully available
