### ISSUE TITLE
The secondary button is pretty broken with dark mode

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/nextcloud-vue#2538]
The secondary button is pretty broken with dark mode:

Theme | Button | Normal | Hover
---|---|---|---
`#082321` | Component | ![Bildschirmfoto von 2022-01-26 14-03-47](https://user-images.githubusercontent.com/213943/151168222-40b45f47-09fc-4967-aa78-9cf4b0745c67.png) | ![Bildschirmfoto von 2022-01-26 14-03-52](https://user-images.githubusercontent.com/213943/151168226-c7e523f9-d8f7-48f1-bbe5-e369df5ae25c.png)
`#082321` |  html  | ![Bildschirmfoto von 2022-01-26 14-10-54](https://user-images.githubusercontent.com/213943/151168940-1b59d155-7dd0-467b-9546-68ede465f809.png) | ![Bildschirmfoto von 2022-01-26 14-10-57](https://user-images.githubusercontent.com/213943/151168945-edffcfb4-d626-4258-94dd-db753f7a0bca.png)
`#C3E2E3` | Component | ![Bildschirmfoto von 2022-01-26 14-04-27](https://user-images.githubusercontent.com/213943/151168330-c02defad-d561-4bff-a730-7c472f23064a.png) | ![Bildschirmfoto von 2022-01-26 14-04-31](https://user-images.githubusercontent.com/213943/151168340-b3544c50-cfef-4ba6-9213-38ceb3760e61.png)
`#C3E2E3` | Component | ![Bildschirmfoto von 2022-01-26 14-05-00](https://user-images.githubusercontent.com/213943/151168553-7efd7d5b-b61a-4bd5-8308-3293e67a385d.png) | ![Bildschirmfoto von 2022-01-26 14-05-06](https://user-images.githubusercontent.com/213943/151168561-dfabb1c3-d32d-4e7b-b335-c910244b2b59.png)
`#C3E2E3` | html | ![Bildschirmfoto von 2022-01-26 14-10-26](https://user-images.githubusercontent.com/213943/151169067-d20324b1-92a2-407f-bc91-fe77ccaec4e8.png) | In the old version there was at least a border making it a bit more clear it's a clickable area:

---

This is not good enough for the most important button on Talk.

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/6834#issuecomment-1022186112_

**Comment by jancborchardt** [comment]
These things were covered in the initial mockup, it seems?
![image](https://user-images.githubusercontent.com/925062/157228724-d62dace1-fa4f-4f49-a3d6-02d4410e5374.png)

- [ ] In dark theme, the text on the button should probably always be white or light for readability
- [ ] With very light and very dark primary colors we need grey-ish fallbacks, see on the bottom

**Comment by marcoambrosini** [comment]
Ok, I think we're missing the fallbacks and their hover states entirely, I'll look into this

**Comment by nickvergessen** [comment]
So the one thing I think needs fixing in the button component is the font color of the secondary button should depend on the background color not the primary color:
```diff
diff --git a/src/components/Button/Button.vue b/src/components/Button/Button.vue
index ac07aa38..2334375a 100644
--- a/src/components/Button/Button.vue
+++ b/src/components/Button/Button.vue
@@ -543,6 +543,14 @@ export default {
                }
        }
 
+       // Secondary
+       &--vue-secondary {
+               body.theme--dark & {
+                       // Fix dark mode
+                       color: var(--color-main-text);
+               }
+       }
+
        // Tertiary
        &--vue-tertiary {
                color: var(--color-text-lighter);
```

**Comment by nickvergessen** [comment]
But after this there is a lot of work necessary to fix the element colors in the server:
```diff
diff --git a/apps/theming/css/theming.scss b/apps/theming/css/theming.scss
index 52337d2105..3b84b5e52b 100644
--- a/apps/theming/css/theming.scss
+++ b/apps/theming/css/theming.scss
@@ -264,7 +264,7 @@ input.primary {
 /** Handle primary buttons for bright colors */
 @if (luma($color-primary) > 0.8) {
        :root {
-               --color-primary-light-text: var(--color-primary-text);
+               --color-primary-light-text: var(--color-primary-element);
        }
        select,
        button, .button,
diff --git a/core/css/variables.scss b/core/css/variables.scss
index 87ef3fdcb1..55ea20344e 100644
--- a/core/css/variables.scss
+++ b/core/css/variables.scss
@@ -45,19 +45,19 @@ $color-placeholder-dark: nc-darken($color-main-background, 20%) !default;
 
 $color-primary: #0082c9 !default;
 $color-primary-hover: mix($color-primary, $color-main-background, 80%) !default;
-
-$color-primary-light: mix($color-primary, $color-main-background, 10%) !default;
-$color-primary-light-text: $color-primary !default;
-$color-primary-light-hover: mix($color-primary-light, $color-main-text, 95%) !default;
-
 $color-primary-text: #ffffff !default;
+
 // do not use nc-darken/lighten in case of overriding because
 // primary-text is independent of color-main-text
 $color-primary-text-dark: darken($color-primary-text, 7%) !default;
 $color-primary-element: $color-primary !default;
 $color-primary-element-hover: mix($color-primary-element, $color-main-background, 80%) !default;
 $color-primary-element-light: lighten($color-primary-element, 15%) !default;
-$color-primary-element-lighter: mix($color-primary-element, $color-main-background, 15%) !default;
+$color-primary-element-lighter: mix(lighten($color-primary-element, 15%), $color-main-background, 15%) !default;
+
+$color-primary-light: mix($color-primary, $color-main-background, 10%) !default;
+$color-primary-light-text: $color-primary-element !default;
+$color-primary-light-hover: mix($color-primary-light, $color-main-text, 95%) !default;
 
 $color-error: #e9322d;
 $color-error-hover: mix($color-error, $color-main-background, 80%) !default;
```

This fixes most of the problems with bright colors. But dark primary on dark mode needs some more fixing:
![Bildschirmfoto von 2022-03-09 12-36-10](https://user-images.githubusercontent.com/213943/157434297-fcd6e9a5-eaab-47a9-a269-a3c68ab949a4.png)

**Comment by nickvergessen** [comment]
So I created a testing grid with different colors in dark and bright
![Bildschirmfoto von 2022-03-09 13-56-22](https://user-images.githubusercontent.com/213943/157446556-74789091-ad28-4795-887b-1ed8441f8e8c.png)

I thought we always had a white and a black threshhold. But seems it's only available for white.
So maybe that is the last missing bit.

**Comment by nickvergessen** [comment]
So the problem is actually that the thresholding we have:
https://github.com/nextcloud/server/blob/e3a12b348206adcfbfb0fbc8435ba91240ac2b0a/apps/theming/lib/Util.php#L82-L96

Is missing from:
https://github.com/nextcloud/server/blob/760db78dbac8ac81f58dd0f2797b7d76fb0af239/apps/theming/lib/ThemingDefaults.php#L342

I mean it is there, but it falls back to "bright mode" as the dark theme parameter is not set with the user's setting. Also all colors that are recalculated on top of it:
https://github.com/nextcloud/server/blob/ac2bc2384efe3c15ff987b87a7432bc60d545c67/core/css/variables.scss#L57-L60

need to be reparsed/calculated?
