### ISSUE TITLE
Support multiple inline actions if there is space

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/nextcloud-vue#2541]
The restriction to only show action buttons inline if there are exactly one of them seems very restrictive to me. If there is space to show two buttons inline, why not do it? [I have even seen apps put multiple `<Actions>` beside each other to get this effect](https://github.com/nextcloud/tasks/blob/master/src%2Fcomponents%2FTaskBody.vue#L86), but this isn't responsive.

My proposal is to add a new component `<ResponsiveActions>` or to add an option for the existing `<Actions>` to show many inline action buttons if there is sufficient space. I could be done similarly to `<Breadcrumbs>` where the space of the container is compared to the total space of all the children, and if the children are bigger, show the menu.

The reason I am asking is for [an issue I am working on for nextcloud/cookbook](https://github.com/nextcloud/cookbook/issues/896). I want this layout on small screens:
![image](https://user-images.githubusercontent.com/8503756/157496120-ea342258-e21a-4e4f-82ed-25661a1e7f28.png)
and this layout on larger screens:
![image](https://user-images.githubusercontent.com/8503756/157496276-9093b563-5d8b-453c-9f15-cfeb8338fa66.png)

It may also be nice to show the button text if there is space to avoid [mystery meat navigation](https://en.wikipedia.org/wiki/Mystery_meat_navigation).
![image](https://user-images.githubusercontent.com/8503756/157496693-724424f2-ebca-4884-ad2a-b4fcec491ef0.png)

I think it is a better user experience to have all buttons immediately available. As a user of Nextcloud, I have found myself clicking many expanding menus until I find the hidden button I am looking for. Is there any reason I am missing not to show all these buttons?

**Comment by raimund-schluessler** [comment]
Implemented with #3060.
