### ISSUE TITLE
AppNavigationItem `add xxx` design changes

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#2543]
Small adjustment after call with @nimishavijay:
- Whole "Add calendar" row is clickable
- Menu has the 3 entries, and is centered below the click area
- "+" is an icon on the left
![image](https://user-images.githubusercontent.com/925062/155309216-b9fbd785-2bdb-4015-8b09-15702724ae44.png)

Does that work @ChristophWurst? This was also the originally intended design for the "New calendar" section in the first place, but then for some reason (component limitation?) the action menu on the right was used.

_Originally posted by @jancborchardt in https://github.com/nextcloud/calendar/issues/3965#issuecomment-1048681112_

**Comment by raimund-schluessler** [comment]
Closing as per https://github.com/nextcloud/nextcloud-vue/pull/2555#issuecomment-1084295809.
