### ISSUE TITLE
Add a "link" option to Button component

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#2581]
In previous Nextcloud versions it was possible to make a `<a href>` and apply the button class and it looked identical to a button but allowed to right click open in a new tab and more stuff (e.g. used in notifications - when being added to a room).

Now this seems to not be possible and one has to copy all the CSS manually.

Would be nice if the button component would have a link/url prop which then automatically makes it a `<a href>` with the given style

**Comment by raimund-schluessler** [comment]
This was implemented.
