### ISSUE TITLE
Multiselect: long names not displayed properly

### ISSUE THREAD

**Issue by rullzer** [nextcloud/nextcloud-vue#261]
When you have very long group names they just get cut off at the end. We should show them properly (scrolling?).

CC: @skjnldsv

**Comment by skjnldsv** [comment]
@jancborchardt any idea on the dropdown width?
Ellipsis on the middle?

![nc-groups-long-names-2](https://user-images.githubusercontent.com/14975046/56128921-46843480-5f81-11e9-9f10-33fea43df111.png)

**Comment by jancborchardt** [comment]
> Ellipsis on the middle?

That seems to be the best way to go here. We have to curb the width of the dropdown at some point anyway, and having same width as the input field just looks best.

**Comment by skjnldsv** [comment]
I'm disappointed, I was still secretly hoping for the return of markee!

**Comment by skjnldsv** [comment]
Fix in #352
