### ISSUE TITLE
Rename Vue components to multi word components

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#2643]
According to https://eslint.vuejs.org/rules/multi-word-component-names.html the component names should not be named with a single word to avoid conflicts with current or future html tags.

An example is the Button component, which could cause conflicts with the html tag button. 

Affected components: 
* Actions
* Avatar
* Breadcrump
* Breadcrumps
* Button
* Content
* Highlight
* Modal
* Popover

Maybe the vue3 migration could be a good point to optimize this.

**Comment by vinicius73** [comment]
I believe we can use a prefix in all components.

- `NCActions`
- `NCAvatar`
- `NCButton`
- `NCContent`
- ...

It will prevent possible [collisions](https://v2.vuejs.org/v2/style-guide/?redirect=true#Multi-word-component-names-essential) and make clear whom components are from `@nextcloud/vue`

**Comment by vinicius73** [comment]
I guess we can try something about this in v6 or #2959

**Comment by korelstar** [comment]
This is getting critical due to the changes in `@nextcloud/eslint-config` v8.1.2. When updating an app's dependency, you cannot use single-worded components anymore, e.g. `Content` or `Button`. Hence, this issue has to be fixed in order to be able to use `@nextcloud/eslint-config` v8.1.2 in apps.
