### ISSUE TITLE
Ensure visibility of buttons and radio/checkbox for dark primary color in dark theme just like we do for light primary color in default light theme

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#2661]
As a follow-up to https://github.com/nextcloud/nextcloud-vue/pull/2622 by @skjnldsv. We need a fallback for the case of dark primary color in dark theme just like we do for bright primary color in light theme.

### Light theme + bright primary colour
This looks good – here we offer a fallback to a grey tone so there is enough contrast with the background, and the primary button looks more present than the secondary one:
![Peek 08-04-2022 10-19](https://user-images.githubusercontent.com/14975046/162395250-b9351401-5630-45c0-bd9d-77b2dea4bba8.gif)

### Dark theme + black primary colour
Here the radio buttons and checkboxes are barely visible, and the primary button is way less visible than the secondary one:
![Peek 08-04-2022 10-16](https://user-images.githubusercontent.com/14975046/162394938-5c6c196c-bb45-4879-a962-684a70e9c6c4.gif)

**Comment by jancborchardt** [comment]
The only variable which comes close is text-maxcontrast but that would be misusing it.

I guess we need color-primary-element-dark in addition? Or can color-primary-element know if it needs to be triggered for dark themes?

**Comment by skjnldsv** [comment]
> I guess we need color-primary-element-dark in addition? Or can color-primary-element know if it needs to be triggered for dark themes?

It could. We just have to define clear expectations so I know what I can put :)

**Comment by susnux** [comment]
Fixed by @szaimen in #4067 

On this screen recording the primary color was set to black:

https://github.com/nextcloud/nextcloud-vue/assets/1855448/868de17f-2419-4411-a648-9e14433cd4f7
