### ISSUE TITLE
Allow start/create/add button on empty content

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#2687]
https://github.com/nextcloud/spreed/blob/3cd27ed7e1add9f67083327d8a0c829e76a3d450/src/views/Dashboard.vue#L50-L55

**Comment by raimund-schluessler** [comment]
`NcEmptyContent` got an action slot for buttons with #3106:
https://github.com/nextcloud/nextcloud-vue/blob/e65bd9247874264aa1d57d59d79f53391e31faa1/src/components/NcEmptyContent/NcEmptyContent.vue#L90-L91
