### ISSUE TITLE
l10n: Context needed 

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/nextcloud-vue#2702]
https://github.com/nextcloud/nextcloud-vue/blob/581b7b660e50018601ee360aa3a4128f358638e7/src/components/DashboardWidget/DashboardWidget.vue#L319

@raimund-schluessler You changed this line and translators at Transifex want to know more about this {what} variable.

**Comment by rakekniven** [comment]
Please enlight us 😄

**Comment by raimund-schluessler** [comment]
Well, I just copied the component over from https://github.com/nextcloud/nextcloud-vue-dashboard where it resided before. The `{what}` placeholder was introduced by @eneiluj in https://github.com/nextcloud/nextcloud-vue-dashboard/commit/f2d5a6bdf94b8564be2ac4ac80b705e2d8248af0.

The default for `what` is `items`, which can be overwritten by the user of the component. It refers to the items shown in the dashboard component, hence, can be `events`, `tasks`, `notes` or whatever.

I don't find this solution ideal either, but I guess it was done like this to enforce the `More` at the beginning to have it uniformly across different dashboard widgets.

**Comment by rakekniven** [comment]
Ok, understood. At the moment there is no way to provide any comments in the source for the translators (for vue files).
Can we change the namen `what` to  something like `content` ?

**Comment by raimund-schluessler** [comment]
> Can we change the namen `what` to something like `content` ?

Fine with me. Maybe `dashboardItemType` would be even more helpful?

**Comment by rakekniven** [comment]
Yes, sounds good. Will provide PR and ask you for review?

**Comment by rakekniven** [comment]
@raimund-schluessler Can you please review it?

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler Can you please review it?

I did already a few days ago. But another review is necessary.

**Comment by rakekniven** [comment]
Oh, must be a monday 😄 . Looked at the issue instead of PR 🙈 .
