### ISSUE TITLE
Emoji 14 🫡

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#2714]
I was wondering if/when we can have support for https://emojipedia.org/emoji-14.0/

Using Talk without them is kind of 🫠

**Comment by ChristophWurst** [comment]
This is possibly a limitation of https://github.com/serebrov/emoji-mart-vue, but I can also not find a ticket upstream.

**Comment by nickvergessen** [comment]
Ref of the 13 update: https://github.com/serebrov/emoji-mart-vue/pull/108

**Comment by ChristophWurst** [comment]
https://github.com/serebrov/emoji-mart-vue/issues/203 there is a ticket now

**Comment by max-nextcloud** [comment]
I've seen melting faces in the emoji picker and the upstream issue is closed. So i assume this is done. Please reopen if i am confusing things.
