### ISSUE TITLE
Ship new library release built with 2.6.7

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#273]
It seems that vue 2.6.7 has a breaking change so that libraries with scoped slots (multiselect) bundled with 2.5 (as the 0.7 release is right now) don't work together anymore. 

@skjnldsv Can you do a new release with 2.6.7 as dependency? Seems package-lock is already properly set but package.json still has 2.5.

Reference issue https://github.com/vuejs/vue/issues/9545

**Comment by skjnldsv** [comment]
@juliushaertl if the lock file as it, then it's fine. ^2.5.4 means any minor from 2.x.x :)
So any new release shall do it? :thinking:

**Comment by skjnldsv** [comment]
Fixed in 95cb70e
