### ISSUE TITLE
Allow to disable modal primary button styling

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#275]
In the viewer the next button should just be a regular one instead of one with primary color.

**Comment by skjnldsv** [comment]
@juliushaertl any particular reason? I kinda like the dual tone on this one :)
@jancborchardt shall we go for the same button design as default?

**Comment by juliushaertl** [comment]
> @juliushaertl any particular reason? I kinda like the dual tone on this one :)

No real reason, it just looked a bit odd to me when testing ;)

**Comment by skjnldsv** [comment]
Should we set the primary style on hover/focus? :)

**Comment by skjnldsv** [comment]
:bellhop_bell: 
@ChristophWurst any opinions? :)

**Comment by ChristophWurst** [comment]
Nope :man_shrugging:

**Comment by jancborchardt** [comment]
The primary button styling should only be there in the first run wizard, so an optional styling.

For the picture viewer, "Next" is not necessarily the more important action, and also it takes way too much attention away from the actual content. In picture viewers, all the actions are usually monochrome.

**Comment by skjnldsv** [comment]
Let's do it! :muscle:

**Comment by skjnldsv** [comment]
Closed as this is disabled by default.
