### ISSUE TITLE
Make a toast message readable for the screenreaders

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/nextcloud-vue#2761]
Making sure that status messages are read when appropriate by screen readers is a vital part in making a service such as this accessible for screen reader users.

There is a visual status message, but it needs to be communicated to screen reader users.

![image](https://user-images.githubusercontent.com/6078378/173391433-4410526a-1564-4eed-824a-d1f305627c32.png)

![image](https://user-images.githubusercontent.com/6078378/173391918-76fde9e2-1da3-4d44-8f94-8ba4d30c333a.png)

Suggestion for implementation: 
https://www.w3.org/WAI/GL/wiki/Using_ARIA_role_of_alert_for_Error_Feedback_in_Forms

**Comment by PVince81** [comment]
I think toastify is actually in https://github.com/nextcloud/nextcloud-dialogs

**Comment by PVince81** [comment]
ah, I had it already here: https://github.com/nextcloud/nextcloud-dialogs/issues/255

feel free to merge the ticketts

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/nextcloud-dialogs/issues/255 solved

Just need to bump `@nextcloud/dialogs` in this repo before doing a vue release
