### ISSUE TITLE
Modal not properly centered in IE11

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#279]
![image](https://user-images.githubusercontent.com/3404133/53503115-c462ae00-3aaf-11e9-838b-4d9eed64ccd3.png)

**Comment by skjnldsv** [comment]
Damn you IE :dagger:

**Comment by skjnldsv** [comment]
Centered on my side

![Capture d’écran_2019-04-15_13-18-15](https://user-images.githubusercontent.com/14975046/56128794-f0af8c80-5f80-11e9-8368-3e23351f5136.png)
