### ISSUE TITLE
Name of dialog needs to be communicated

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/nextcloud-vue#2810]
e.g. via `aria-labelledby` linked to the dialog title, which ideally is an h2 inside the dialog

**Comment by PVince81** [comment]
it's already there: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Modal/Modal.vue#L112 added in https://github.com/nextcloud/nextcloud-vue/pull/2924
