### ISSUE TITLE
On closing, focus has to move back to element used to open the dialog – show clear visible focus on that again

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/nextcloud-vue#2816]

**Comment by st3iny** [comment]
This is not done. I can still reproduce it.

**Comment by PVince81** [comment]
ref: base work was https://github.com/nextcloud/nextcloud-vue/pull/2654

**Comment by PVince81** [comment]
as far as I can see, the "focus-trap" library support returning, we need to set some options

**Comment by PVince81** [comment]
as far as I can see in a local test, the focus is already returning thanks to the "focus-trap" library that does it out of the box.

closing
