### ISSUE TITLE
Generic reusable and accessible text field

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-vue#2866]
@marcoambrosini 

ref https://github.com/nextcloud/spreed/pull/7491/commits/c2fbf29392e9e981bdc6dd55263ddbb4f8d75e12#diff-a01cbef4930a8836e52c21626ec035892c8348cd361d3bb0c0abac177eaff798R32

- label
- placeholder support
- accessible name
- include optional tick mark (see profile page how fields are verifiable)

**Comment by dartcafe** [comment]
Maybe this could be of use: https://github.com/nextcloud/polls/blob/master/src/js/components/Base/InputDiv.vue

**Comment by marcoambrosini** [comment]
Coming soon :)
