### ISSUE TITLE
`MultiselectTags` only displays 5 tags

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/nextcloud-vue#2884]
### Usecase

Currently i develop a new feature in my app (https://github.com/R0Wi/workflow_ocr/issues/88) where i'd like to use the `MultiselectTags` component to show **all** available tags to the user and let him/her choose **0-n** tags.

### Expected

`MultiselectTags` component should contain all tags from the current system.

### Actual
Because of the line
https://github.com/nextcloud/nextcloud-vue/blob/498364d197c5257d758a48853abf87f71ba1d8d2/src/components/MultiselectTags/MultiselectTags.vue#L69

only the first 5 tags are presented to the user which is quite confusing i think. According to the [docs](https://vue-multiselect.js.org/#sub-getting-started) the prop `options-limit` truncates the available options inside the multiselect dropdown.

**Comment by raimund-schluessler** [comment]
Implemented with #2973.
