### ISSUE TITLE
Multiselect not keyboard accessible when items are selected

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#2951]
Sample steps with the docs:
1. Open https://nextcloud-vue-components.netlify.app/#/Components/Multiselect?id=multiselect-1
2. Scroll to `Simple examples`
3. Click on the left select
4. Use `<tab>` to try to access the second Multiselect
5. ❌ See that `View code` is now "hovered"
6. Use the mouse and unselect the option in the right Multiselect
7. Click on the left select
8. Use `<tab>` to try to access the second Multiselect
9. ✅ You can now search in the Multiselect

![Peek 2022-08-05 14-54](https://user-images.githubusercontent.com/213943/183081551-67301a17-7c5f-41f1-aa6c-fbd7532128e8.gif)

**Comment by Pytal** [comment]
Fixed by NcSelect https://nextcloud-vue-components.netlify.app/#/Components/NcSelect?id=ncselect-1

**Comment by nickvergessen** [comment]
Oh, so that's cool and not at the same time. Cool as there is an accessible successor, not cool as the old one is still there and people have to realize themselves.
Can we add a console warn or something or officially deprecate the NCMultiSelect then so people get notified that they should move away?

**Comment by Pytal** [comment]
Deprecation badges were added to the docs
![image](https://user-images.githubusercontent.com/24800714/207674149-80badf7b-015f-4132-864c-826b44ee8727.png)
![image](https://user-images.githubusercontent.com/24800714/207674160-61bd7f52-3c04-45f2-9059-86d266c43f3f.png)
and keeping the old multiselect is necessary as we need this for `@nextcloud/vue` v7 for NC25 so it can't be breaking

Would adding a console warning additionally be the best way or something else?

**Comment by nickvergessen** [comment]
I don't know how Vue itself does it, but e.g. if you use `::v-deep` it shows a warning when compiling.
Maybe we can do something alike?

**Comment by nickvergessen** [comment]
Otherwise apps don't know that they are deprecated/not-accessible
