### ISSUE TITLE
`icon-class` support in `Actions` component broken

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3016]
After the change in #3006, the support for icon-classes is now broken for `Actions`.
A markup like 
```
<template>
	<Actions menuTitle="test" forceTitle>
		<ActionButton icon="icon-delete">
			Delete
		</ActionButton>
	</Actions>
</template>
```
will lead to this rendering:
![Screenshot 2022-08-12 at 09-56-41 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/184310783-bcf824ec-f74d-482a-8c3f-a90e46257ade.png)

This is because the `ButtonVue` component used for showing the `Actions` component trigger has no support for icon-classes and simply adding the icon-class as in #3006 will lead to trouble.

So in order to fix that, one needs to create a span element, apply the icon-class to it, and populate the icon slot of button with it. Not really nice, but apparently needed for server, as a migration to material design icons only is to much effort for now.

@PVince81 @nickvergessen for reference.

**Comment by PVince81** [comment]
since the Actions component is using a generated ButtonVue, it should be possible to create said span element inside it instead of passing the class directly ?

**Comment by raimund-schluessler** [comment]
> since the Actions component is using a generated ButtonVue, it should be possible to create said span element inside it instead of passing the class directly ?

Yes, working on a PR.

**Comment by raimund-schluessler** [comment]
PR is in #3017.
