### ISSUE TITLE
3️⃣2️⃣1️⃣ Colored app navigation counter

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#3054]
Get from 
![Bildschirmfoto vom 2022-08-17 14-55-34](https://user-images.githubusercontent.com/1374172/185137916-73f3d1a8-419d-4acc-9ceb-947501a7bb94.png)

to

![Bildschirmfoto vom 2022-08-17 14-55-56](https://user-images.githubusercontent.com/1374172/185138146-0d32684b-8953-41fa-b532-df05abc0b3de.png)

**Comment by GretaD** [comment]
@jancborchardt @ChristophWurst so the colour should be as the primary colour? Or blue-ish by default?

**Comment by ChristophWurst** [comment]
I assume it's based on the theme color

**Comment by jancborchardt** [comment]
Based on the theme color. :)
