### ISSUE TITLE
[BITV/A11Y] Nextcloud dialog title needs to be inside and focus goes on it first

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-vue#3088]
Steps:
1. Open https://nextcloud-vue-components.netlify.app/#/Components/NcModal
2. Scroll to "Modal with more properties" and click the button

What we need to check:
- [x] title must be inside the dialog (change the default?)
- [x] title must be a h2
- [x] dialog's aria-labelledby must point to the h2
- [x] if a field exists, set the tab there directly

=> test with a screen reader, it should already read the title before announcing the field

**Comment by JuliaKirschenheuter** [comment]
> * title must be inside the dialog (change the default?)

@PVince81 I would say that the title is already inside the dialog. Or probably I've understood you wrong. Could you please check?

**Comment by JuliaKirschenheuter** [comment]
> * if a field exists, set the tab there directly

I've checked the usage of NcModal through our apps and i've seen the first focus goes to the first input. 
@Pytal could you please go thought Files and make a double-check? Thank you!

**Comment by Pytal** [comment]
NcModal handles focus trapping itself https://github.com/nextcloud/nextcloud-vue/blob/556642f23177563da62afdfc798837380e82c04e/src/components/NcModal/NcModal.vue#L543-L547 so seems good @JuliaKirschenheuter

**Comment by JuliaKirschenheuter** [comment]
seems to be right for now
