### ISSUE TITLE
Close an AppNavigationItem's PopoverMenu

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-vue#309]
If some of your app's `AppNavigationItem`s have at least two actions, they are shown in a `PopoverMenu`. Currently, it is not possible to close that menu automatically after triggering the action, since the respective switch is encapsulated in the  `AppNavigationItem` component. I'm not sure about which is the best solution to fix this. I see two possibilities:

1. Provide an interface to close the menu from outside the component. Unfortunately, there is no good way in Vue for calling a component's method from outside of that component.
2. Let `AppNavigationItem` close the `PopoverMenu` directly after calling the action. For this, a modified list of actions could be passed to `PopoverMenu`, where the actions are extended with the call to close the menu.

Any ideas on this?

**Comment by skjnldsv** [comment]
Like this? https://github.com/nextcloud/nextcloud-vue/pull/278

**Comment by korelstar** [comment]
Hmm. Yes, I think that should be appropriate. As a drawback, everybody has to manage closing by themselves. But it's a flexible approach.

**Comment by skjnldsv** [comment]
@korelstar no, since we use a local state, it is still managed locally, so if you don't use the close option from the item, then it should be fine :)
