### ISSUE TITLE
Netlify needs update

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/nextcloud-vue#3107]
>DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
>
>The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
>All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
>To avoid service disruption, please select a newer build image at the following link:
>https://app.netlify.com/sites/nextcloud-vue-components/settings/deploys#build-image-selection

>Unsupported engine {
>  package: '@nextcloud/vue@6.0.0-beta.4',
>   required: { node: '^16.0.0', npm: '^7.0.0 || ^8.0.0' },
>   current: { node: 'v14.20.0', npm: '7.24.2' }
>}

Just saw these two on a netlify build. Seems like i can't do anything there, thus just as an issue here. :wink: 
@skjnldsv @'Whoelse?

**Comment by skjnldsv** [comment]
I enabled 20.04, let's see if it works

**Comment by skjnldsv** [comment]
Seems ok, https://app.netlify.com/sites/nextcloud-vue-components/deploys/630a0ab94e7d966b71f34f5e
