### ISSUE TITLE
Actions in ListItem are not styled like in AppNavigationItem

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#3109]
ListItem | AppNavigationItem
---|---
Talk conversation list | Mail inbox settings
short rounded corners | pill style corners, etc.
![Bildschirmfoto vom 2022-08-26 12-34-19](https://user-images.githubusercontent.com/213943/186885714-178c6744-437f-43ee-94a3-6d65ad5a0fed.png) | ![Bildschirmfoto vom 2022-08-26 12-34-36](https://user-images.githubusercontent.com/213943/186885719-0ea23422-5b5a-4bca-b519-842169e1f06f.png)
![Bildschirmfoto vom 2022-08-26 12-35-07](https://user-images.githubusercontent.com/213943/186885830-5df84ba8-5b8c-4316-aa28-6c64a68b73ef.png) | ![Bildschirmfoto vom 2022-08-26 12-35-20](https://user-images.githubusercontent.com/213943/186885838-c012eb4c-df0c-4e3a-bc3d-882931ab9009.png)

**Comment by jotoeri** [comment]
Probably an issue within talk somewhere?
Forms is using a ListItem but also shows the round corners:

![grafik](https://user-images.githubusercontent.com/47433654/185758018-5aee38fc-7952-43f6-9149-29992480347c.png)

**Comment by nickvergessen** [comment]
Well as you can see in the CSS screenshot it's only about the order of the assigned rules. I think the components should be save guarded against that by specifying a longer match for the rule or having a dedicated class.
