### ISSUE TITLE
Invalid CSS for NcModel

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3123]
This line of CSS is invalid:
https://github.com/nextcloud/nextcloud-vue/blob/c73eb5852dc2641115d524012dad8f14bf8a0f78/src/components/NcModal/NcModal.vue#L859

But since I don't know what is intended here, I just summon @Pytal, @skjnldsv and @PVince81 since you touched it last :see_no_evil:

**Comment by skjnldsv** [comment]
It's part of the rule above
```
transition: opacity 250ms,
		visibility 250ms
```

**Comment by raimund-schluessler** [comment]
Ah, damn it. Of course. Sorry I didn't realize this. But it explains why the linter complained about a missing tab there, but not about invalid CSS. 🙈
I will send a PR to get the tab fixed 😄

**Comment by skjnldsv** [comment]
:hugs:
