### ISSUE TITLE
NcAppNavigation Action menu is not fully shown v6.0.0-beta.6

### ISSUE THREAD

**Issue by tacruc** [nextcloud/nextcloud-vue#3146]
Hi Together,
I hope that the screenshots visualize my Issue. After megration to v6.0.0 the Action menus is cuttoff.

![image](https://user-images.githubusercontent.com/402891/187910961-5da12b96-b3a9-44e2-a571-eb8e8c78d5fb.png)
![image](https://user-images.githubusercontent.com/402891/187911155-7883d388-e1f9-48ef-904c-bddf0fd16385.png)

**Comment by raimund-schluessler** [comment]
Can confirm this. I think I first saw this after https://github.com/nextcloud/nextcloud-vue/pull/3061 was merged.

**Comment by raimund-schluessler** [comment]
Fixed with https://github.com/nextcloud/nextcloud-vue/pull/3157.
