### ISSUE TITLE
Styleguide isn't scrollable anymore

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#3181]
The main section of https://nextcloud-vue-components.netlify.app/ is no more scrollable.

Tested in Firefox and Chrome.

**Comment by raimund-schluessler** [comment]
This is a regression of https://github.com/nextcloud/nextcloud-vue/pull/3139 caused by pulling styles from server.
This line makes scrolling impossible:
https://github.com/nextcloud/server/blob/master/core/css/server.css#L2883

@skjnldsv @CarlSchwan
