### ISSUE TITLE
NcAppNavigationItem:  Invalid prop: type check failed for prop "boundariesElement". Expected Element, got String with value "#content-vue"

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#3187]
Using v7 with Mail I get 

```
[Vue warn]: Invalid prop: type check failed for prop "boundariesElement". Expected Element, got String with value "#content-vue".

found in

---> <NcActions>
       <RouterLink>
         <NcAppNavigationItem>
           <NavigationAccount> at src/components/NavigationAccount.vue
             <NcAppNavigation>
               <Navigation> at src/components/Navigation.vue
                 <Content>
                   <Home> at src/views/Home.vue
                     <App> at src/App.vue
                       <Root> vue.runtime.esm.js:4573
```

## Steps to reproduce
1) Open Mail
2) Add an account
3) Open the account's actions menu in the navigation

**Comment by ChristophWurst** [comment]
Regression of https://github.com/nextcloud/nextcloud-vue/pull/1352 I guess

**Comment by ChristophWurst** [comment]
Not sure how this should be fixed. We could have a computed prop in `NcAppNavigationItem` that returns the DOM element for `#content-vue` if it can be found.

**Comment by raimund-schluessler** [comment]
Yeah, this was broken in https://github.com/nextcloud/nextcloud-vue/pull/3157 where we now set the boundaries-element. Doing as you proposed should do the trick.
