### ISSUE TITLE
color-text-maxcontrast needs to use darker value in new left navigation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#3198]
Since the new left navigation is slightly transparent, we need to use a slightly darker `--color-text-maxcontrast` value when it’s used in there.

To be clear: Only for the usage in there, we should **not** increase the value of the variable overall, as then it will reduce the contrast/difference to `--color-main-text`.

Of course there are different backgrounds, but let’s start out by making sure it works for the default background.

With current `#767676` (maxcontrast) for subline | With better `#646464`
-|-
![image](https://user-images.githubusercontent.com/925062/189121169-29d195cf-3f42-4676-a08c-3f4068c05a11.png)|![image](https://user-images.githubusercontent.com/925062/189122098-ec3eaf99-2214-4e99-8db6-85551b083137.png)
![image](https://user-images.githubusercontent.com/925062/189122340-c08f27cf-12aa-495c-929e-351ca24db3a9.png)|![image](https://user-images.githubusercontent.com/925062/189122252-26d814a3-7a26-4336-9ea2-1095c927b7f2.png)

----

Also, `.line-two__subtitle` uses the outdated variable `var(--color-text-lighter)` – we only use `--color-main-text` and `--color-text-maxcontrast`, as per the design guidelines: https://docs.nextcloud.com/server/latest/developer_manual/design/foundations.html#text-color

**Comment by jancborchardt** [comment]
@juliushaertl @CarlSchwan we should ideally fix this for the release as it relates to the accessibility of a very prominent element. What do you think of the proposal?

**Comment by AndyScherzinger** [comment]
Sounds good to me 👍 
Also the change is very subtle - thus not impacting screenshots

**Comment by Pytal** [comment]
This uses server-side calculated color variables so splitting up calculations with new client-side logic wouldn't be an option, seems that adding a new variable would be the way to go then @skjnldsv?

Would mean replacing `--color-text-lighter` in `NcListItem` with the new variable

**Comment by jancborchardt** [comment]
@Pytal yep, sounds good! Note that `--color-text-lighter` and `--color-text-light` are actually not recommended to use. We use:
- `--color-main-text`
- `--color-text-maxcontrast`

So we could introduce a new `--color-text-maxcontrast-more` or something like that, but it would even be better if we just say that on certain backgrounds (like the one in the navigation), the maxcontrast is just upped a little. That way developers don’t have to specifically set it, and also sometimes the background of the navigation might not be transparent, like on mobile.

**Comment by Pytal** [comment]
We can only increase the contrast by darkening the variable server-side with `$this->util->darken($colorTextMaxcontrast, 7)` (`#767676` -> `#646464`) as CSS does not allow you to darken a color variable at runtime and we have to scope it to maxcontrast text within AppNavigation with a light theme applied

Fix in https://github.com/nextcloud/nextcloud-vue/pull/3307 and https://github.com/nextcloud/server/pull/34299
