### ISSUE TITLE
Warning when opening a NcPopover

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/nextcloud-vue#3199]
I tried it with NcActions in NcAppNavigationItem and NcAvatar, we get this when the NcPopover is rendered or opened:

![image](https://user-images.githubusercontent.com/11291457/189123047-125f9dac-38c2-4166-a235-befbb5f145d8.png)

Also, with NcAvatar, the popover is displayed the first time it's opened but it can't be opened anymore after that.

@raimund-schluessler Any clue?

**Comment by raimund-schluessler** [comment]
I see this when using a development build with `npm link`. Try copying the dist folder into your app and use a production build or check the nc/vue version from npm with npm run build your app.

**Comment by raimund-schluessler** [comment]
See https://github.com/nextcloud/nextcloud-vue/issues/3281.
