### ISSUE TITLE
Update related resources panel design

### ISSUE THREAD

**Issue by Pytal** [nextcloud/nextcloud-vue#3220]
More details and mockup in https://github.com/nextcloud/server/issues/28320

@jancborchardt anything else in addition to the updates below?

<details>
<summary>Current design</summary>

Shared items tab in Talk
![image](https://user-images.githubusercontent.com/24800714/186301728-cf30677a-799a-4acd-8987-4ca5aa161ecb.png)

</details>

**Comment by Pytal** [comment]
### Updates

- [ ] https://github.com/nextcloud/nextcloud-vue/pull/3236
- [ ] https://github.com/nextcloud/server/pull/34043

**Comment by jancborchardt** [comment]
Left a comment in the review of the PR – anything left over please make sure to paste in here. :)

**Comment by Pytal** [comment]
PRs updated :)
