### ISSUE TITLE
Is the old 0.5.x branch compatible with NC 25?

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/nextcloud-vue#3243]
The new version 7.x.x is requiring NC core version25 according to the [changelog entry](https://github.com/nextcloud/nextcloud-vue/blob/master/CHANGELOG.md#boom-breaking-changes).

As an app developer, I am asking myself if the previous releases (5.x.x and 6.x.x) are compatible with all current NC core versions. What would be the way to go to not force our users to the very latest version? Is there some sort of best practice? This might be communicated, eventually.

**Comment by nickvergessen** [comment]
I think it's close to impossible.

25 comes with huge UI changes and using any older version will make the app look odd and out of place. Additionally scrolling might be broken and more things.
My personal take is: cut your app and create a "before 25" branch that uses the latest 5 or 6 of the lib and master/main which has Nextcloud 25 as minimum requirement uses Vue lib 7.

For some more details see https://github.com/nextcloud/server/issues/32117

**Comment by christianlupus** [comment]
OK, thank you. I will prepare things accordingly.
