### ISSUE TITLE
NcRichContentEditable can not handle HTML a like input

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#3264]
Open the sample
https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable

Enter `3 < 4` and check the posted content below and in the other form

![Bildschirmfoto vom 2022-09-16 16-15-55](https://user-images.githubusercontent.com/213943/190660160-28f4fd73-3e25-4168-ae47-80bb0ba15a7a.png)

Also the case for comments on the files app and talk descriptions (as reported in https://github.com/nextcloud/spreed/issues/7309 )

**Comment by knowasaritra** [comment]
can i work on this ?

**Comment by Antreesy** [comment]
@julien-nc , could it be the problem?
https://github.com/nextcloud/nextcloud-vue/blob/72cb053c5802b8511379fa1a13e8a87facbe37c2/src/mixins/richEditor/index.js#L88

When we type `<`, it replaces with `&amp;lt;` and in mentioned function only ampersand is changed, which resulted in `&lt;`

**Comment by julien-nc** [comment]
@Antreesy No idea. This line was last modified by @skjnldsv.

**Comment by nickvergessen** [comment]
stable25 Talk code that could serve as a sample: https://github.com/nextcloud/spreed/blob/209fd101b58ec133cf22362e859227d4aa15244d/src/components/NewMessageForm/NewMessageForm.vue#L518-L520
