### ISSUE TITLE
[7.0.0-beta.4] Cannot copy text to clipboard via NcActionButton anymore, if NcAction adds NcPopover

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#3275]
With more than one NcActionButton in NcActions, a contained action, which should copy text to the clipboard will not work anymore. **vue-clipboard2** is used here. With a single NcActionButton it works.

![grafik](https://user-images.githubusercontent.com/26707476/191274100-199bc145-38b5-451a-8110-ddd7ecc278a3.png)

Any more information needed?

Example code:

```html
<NcActions>
	<NcActionButton @click="copyText({ text: 'Text to be copied to clipboard'})">
		<template #icon>
			<Clipboard />
		</template>
		Copy link to clipboard
	</NcActionButton>
	<NcActionButton @click="copyText({ text: 'Text to be copied to clipboard'})">
		<template #icon>
			<ClippyIcon />
		</template>
			Copy link to clipboard
	</NcActionButton>
</NcActions>
```
[...]

```js
methods: {
	copyText(payload) {
		try {
			this.$copyText(payload.text)
			showSuccess('Text copied to clipboard')
		} catch {
			showError('Error while copying text to clipboard')
		}
	},
}
```

**Comment by nickvergessen** [comment]
Also an issue in talk:
https://github.com/nextcloud/spreed/issues/7909

Glad to hear it's a generic issue

**Comment by raimund-schluessler** [comment]
Could be an issue with the focusTrap of the Popover which might prevent vue-clipboard2 from copying the data. Could be tested by disabling the focusTrap.

**Comment by raimund-schluessler** [comment]
I think the best solution to this is to not use `vue-clipboard2` anymore, but the native browser API `navigator.clipboard`. The compatibility seems to be very good, given that we dropped IE:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard#browser_compatibility

I have an example PR for Tasks here https://github.com/nextcloud/tasks/pull/2115 that fixes the issue and works just fine.

**Comment by dartcafe** [comment]
omg. Such an easy solution. 😉  Thanks for the hint.
