### ISSUE TITLE
Error spam "$attrs is readonly" and "$listeners is readonly" in console with current master

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#3281]
Open Talk with 7beta4:
* ✨ 

Open Talk with master what is going to be 7beta5:
* 💥 Huge error log for each conversation in your left sidebar
```
[Vue warn]: $attrs is readonly.

found in

---> <VPopperContent>
       <VPopper>
         <VDropdown>
           <NcPopover>
             <NcActions>
               <RouterLink>
                 <NcListItem>
                   <Conversation> at src/components/LeftSidebar/ConversationsList/Conversation.vue
                     <ConversationsList> at src/components/LeftSidebar/ConversationsList/ConversationsList.vue
                       <NcAppNavigation>
                         <LeftSidebar> at src/components/LeftSidebar/LeftSidebar.vue
                           <NcContent>
                             <App> at src/App.vue
                               <Root> vue.runtime.esm.js:4568
[Vue warn]: $listeners is readonly.

found in

---> <VPopperContent>
       <VPopper>
         <VDropdown>
           <NcPopover>
             <NcActions>
               <RouterLink>
                 <NcListItem>
                   <Conversation> at src/components/LeftSidebar/ConversationsList/Conversation.vue
                     <ConversationsList> at src/components/LeftSidebar/ConversationsList/ConversationsList.vue
                       <NcAppNavigation>
                         <LeftSidebar> at src/components/LeftSidebar/LeftSidebar.vue
                           <NcContent>
                             <App> at src/App.vue
                               <Root>
```

**Comment by raimund-schluessler** [comment]
Could you try this approach: https://github.com/nextcloud/nextcloud-vue/pull/3268#issuecomment-1254941633

**Comment by raimund-schluessler** [comment]
The problem is a duplication of the vue dependency which causes this warning. Adding this
```js
webpackConfig.resolve.alias = {
    "vue$": path.resolve('./node_modules/vue')
}
```
to my webpack config, e.g. in Tasks fixes the issue and even reduces the bundle size, indicating the duplication is gone.
Maybe we should put this in the common webpack configuration. It seems to be necessary for vue3 anyway, see here:
https://github.com/nextcloud/webpack-vue-config/blob/800d666f1117523481f519d7b6a15e4fe49576fc/webpack.config.js#L117-L119

@skjnldsv @marcoambrosini @vinicius73 for opinions.

**Comment by vinicius73** [comment]
This is a good trick.
Although it not solves the root cause, it will work in the main scenarios.

**Comment by raimund-schluessler** [comment]
> Although it not solves the root cause, it will work in the main scenarios.

The question is what is the root cause. One package probably imports in a different way than simply using `import Vue from 'vue'` but finding which one it is, might be a pain.

**Comment by skjnldsv** [comment]
Is this still happening?

**Comment by raimund-schluessler** [comment]
> Is this still happening?

I don't know, to be honest. I didn't see it for a while, and if I remember correctly, it only happened when mixing development builds with production builds.

But the workaround to prevent this is still necessary for the vue3 branch in my case:
```js
webpackConfig.resolve.alias = {
    "vue$": path.resolve('./node_modules/vue')
}
```

**Comment by skjnldsv** [comment]
> But the workaround to prevent this is still necessary for the vue3 branch in my case:
> 
> ```js
> webpackConfig.resolve.alias = {
>     "vue$": path.resolve('./node_modules/vue')
> }
> ```

Seems I also encountered this and this is the way. On the app side, not this library ofc.

**Comment by raimund-schluessler** [comment]
PR is in https://github.com/nextcloud/webpack-vue-config/pull/432.
