### ISSUE TITLE
AppNavigation `ul` & `__list` rule creates unwanted white space to the right of the scrollbar

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/nextcloud-vue#3287]
I think we should remove 
https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcAppNavigation/NcAppNavigation.vue#L181
cc @juliushaertl since you recently added it

Talk before removing: | ...And after
---|---
<img width="352" alt="Screenshot 2022-09-22 at 17 09 21" src="https://user-images.githubusercontent.com/26852655/191785222-9c8da12b-8aff-4a6d-ba93-53f217169734.png"> | <img width="352" alt="Screenshot 2022-09-22 at 17 09 25" src="https://user-images.githubusercontent.com/26852655/191785283-05ec592d-2ba4-4b38-bb2b-123943dae17d.png">

also cc @jancborchardt and @nimishavijay since this came up in a recent design review

**Comment by juliushaertl** [comment]
Spacing seems fine on deck for example:

<img width="345" alt="Screenshot 2022-09-22 at 21 21 26" src="https://user-images.githubusercontent.com/3404133/191833303-94961e06-ca75-4c39-a7ec-742d13a68b3b.png">


Not sure how standard the usage of talk is with the scroller, but maybe we should just limit it to direct children of `.app-navigation`

<img width="802" alt="Screenshot 2022-09-22 at 21 22 16" src="https://user-images.githubusercontent.com/3404133/191833565-60d3f1c7-58b1-4a15-9918-860fa989a51e.png">

**Comment by CarlSchwan** [comment]
Possible fix in nc-vue https://github.com/nextcloud/nextcloud-vue/pull/3303

**Comment by marcoambrosini** [comment]
fixed
