### ISSUE TITLE
right sidebar moves up and down while resizing the window

### ISSUE THREAD

**Issue by schiessle** [nextcloud/nextcloud-vue#3289]
Tested on c.nc.com with NC25RC1

When I resize the window the right sidebar (chat) starts to move around.

![grafik](https://user-images.githubusercontent.com/1589737/191934188-08d7e018-16f2-4650-b4cb-120e0bb84971.png)

Sometimes I can't even access the chat input field.

**Comment by raimund-schluessler** [comment]
Removing `position`, `top` and `right` here solves the issue for me:
https://github.com/nextcloud/nextcloud-vue/blob/f1095a644651656ed3a56fddcf760f2b402b3cb0/src/components/NcAppSidebar/NcAppSidebar.vue#L629-L633

**Comment by dartcafe** [comment]
At least removing top solves it for me. See #3222

**Comment by nickvergessen** [comment]
Deck is not updated with the latest Vue lib yet, so that's expected
