### ISSUE TITLE
Slow menu opening since nc 7

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#3300]
![image](https://user-images.githubusercontent.com/14975046/192544946-73f6516f-e97a-4f71-bafb-dd9568b6bc6d.png)

400ms to open a menu is not acceptable, debugging the profiler gives the above culprit.
Something must have changed.

It request an animation frame and block the browser whch drop my fps to `2`. 
I have 45GB of free ram and 4 full cpu core available (intel i5, so hardware is not an issue)

@raimund-schluessler @marcoambrosini

**Comment by raimund-schluessler** [comment]
There is not really any difference of `NcActions` between stable6 and master:
https://github.com/nextcloud/nextcloud-vue/compare/stable6#diff-a09afa053a2a82c8e733f6d785927c30bcb3f0969d82f5ccfda36861a4af553d

**Comment by raimund-schluessler** [comment]
@skjnldsv Maybe this is related to the focus-trap issue https://github.com/nextcloud/nextcloud-vue/issues/3154#issuecomment-1259603481

**Comment by skjnldsv** [comment]
Might be! :shrug:

**Comment by raimund-schluessler** [comment]
@skjnldsv @vinicius73 Is this fixed with https://github.com/nextcloud/nextcloud-vue/pull/3347?

**Comment by skjnldsv** [comment]
Should be yes

**Comment by skjnldsv** [comment]
But this wasnot included in 7.0.0 :(

**Comment by raimund-schluessler** [comment]
> But this wasnot included in 7.0.0 :(

Looks like 7.0.1 needs to come soon.
