### ISSUE TITLE
[7.0.0-beta.6] Selected Items in multiselect not recognizable

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#3306]
One Item is already selected. In the open state, it is not possible to tell, which item is already selectd and can be deselected.

## Polls app config
|initial state | opened | previous presentation (NC24) |
|-|-|-|
|![grafik](https://user-images.githubusercontent.com/26707476/192620377-e3e1727f-0ce0-403c-8408-3ddc55f6ae42.png)|![grafik](https://user-images.githubusercontent.com/26707476/192620606-e1842f40-e8af-46b5-a1c9-49ab6fc79b16.png)|![grafik](https://user-images.githubusercontent.com/26707476/192622014-2dd65bc2-eba5-4453-ab91-f666f3ff1bbb.png)|

## Contacts app
|initial state | opened | previous presentation (NC24) |
|-|-|-|
|![grafik](https://user-images.githubusercontent.com/26707476/192620834-8d13e523-90c8-42a1-b2ed-6d12f2f46639.png)|![grafik](https://user-images.githubusercontent.com/26707476/192620844-f101b570-49c8-40ef-b17b-9687946c8114.png)|![grafik](https://user-images.githubusercontent.com/26707476/192622229-e7753417-e6d6-4313-987e-0abfc56f1ac2.png)|

possibly related #820

**Comment by miaulalala** [comment]
Can confirm. Group selection in Contacts and Category selection in Calendar have this issue.

**Comment by GretaD** [comment]
when i try to inspect this, looks like the icon on mail.scss is undefined

![Screenshot from 2022-10-18 16-46-31](https://user-images.githubusercontent.com/12728974/196465751-d2741965-4475-49dc-bf07-6413dd6d68e8.png)

but on documentation this is shown correctly. Does migrating to material design has anything to do with this @raimund-schluessler ?

**Comment by skjnldsv** [comment]
Yep
https://github.com/nextcloud/nextcloud-vue/pull/3513
