### ISSUE TITLE
Cypress tests broken due external changes to server repo

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3325]
Probably due to #3139 the visual regression tests now get the server CSS live from the server repo. This randomly breaks the visual regression tests here.

Imho this is not a good idea, since  then unrelated changes randomly make the cypress tests fails and can't get merged, see e.g. #3323. Furthermore, we then don't know if it was a change here, or in the server that makes the tests fail.

@skjnldsv @CarlSchwan @vinicius73

**Comment by skjnldsv** [comment]
> Probably due to #3139 the visual regression tests now get the server CSS live from the server repo. This randomly breaks the visual regression tests here.
> 
> Imho this is not a good idea, since then unrelated changes randomly make the cypress tests fails and can't get merged, see e.g. #3323. Furthermore, we then don't know if it was a change here, or in the server that makes the tests fail.
> 
> @skjnldsv @CarlSchwan @vinicius73

Either way there is a downside.
But I will suggest something else, sure :)
