### ISSUE TITLE
Deprecation warning about tag prop of router-link

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/nextcloud-vue#3331]
I saw a deprecation warning in Forms stating `[vue-router] <router-link>'s tag prop is deprecated and has been removed in Vue Router 4. Use the v-slot API to remove this warning.`

https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link.

I think that this might originate from this part of the code:

https://github.com/nextcloud/nextcloud-vue/blob/ff44f28493c5505973bba3d44965dd0f9cfebe29/src/components/NcAppNavigationItem/NcAppNavigationItem.vue#L471-L483

**Comment by raimund-schluessler** [comment]
Fix is in https://github.com/nextcloud/nextcloud-vue/pull/3775. Please test and review if possible.
