### ISSUE TITLE
[7.0.1] "too much recursion" when opening NcModal and NcAppSettingsDialog

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#3386]
When opening NcModal, it opens slowly and the following errors are thrown in  the JS console:

Test it with https://nextcloud-vue-components.netlify.app/#/Components/NcModal

![grafik](https://user-images.githubusercontent.com/26707476/197141941-31737efe-4e16-443d-a888-61dd09fdd773.png)

**Comment by ChristophWurst** [comment]
Can confirm when I link `master` against Mail and open a settings modal

![Bildschirmfoto vom 2022-10-21 15-53-30](https://user-images.githubusercontent.com/1374172/197212510-2b17850d-d722-4305-85b8-60824a8fcd9d.png)

:eyes: @vinicius73

**Comment by ChristophWurst** [comment]
Tracked in https://github.com/nextcloud/nextcloud-focus-trap/issues/2

**Comment by dartcafe** [comment]
🎉
