### ISSUE TITLE
ActionInput date ignores given value when using strings

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-vue#3403]
### Steps

1. Edit NcActionInput.vue
2. Search for the "Please pick a date"
3. Add `value="2022-10-31 00:00:00"` in the row
4. `npm run styleguide` and test it
5. Open the actions input

### Expected result
The date picker field uses the given value.

### Actual result
Always empty.

### Notes

I tried with other formats like "2022-10-31" and "10/31/2022" but the value is always ignored.

This is a regression as it used to work before, see https://github.com/nextcloud/server/issues/34695#issuecomment-1295236260

Tested with nextcloud-vue master and also v7.0.1.
Unsure if v6 is broken.

**Comment by PVince81** [comment]
@Pytal can you investigate ?

**Comment by PVince81** [comment]
still not working on server: https://github.com/nextcloud/server/issues/34926#issuecomment-1316649298

not sure what's different from the style guide

**Comment by PVince81** [comment]
it's not working, tested with my steps above

maybe this got closed too early or as a mistake ?

**Comment by PVince81** [comment]
need to be careful because it seems we're now using the NcDateTimePickerNative so not sure if it needs fixing too

**Comment by PVince81** [comment]
after analysis we found that the native date picker only accepts `Date` objects and not `String`, so we might need to parse strings to keep compatible with the old NcDateTimePicker implementation

**Comment by skjnldsv** [comment]
> I see that the example is using `v-model` instead of the `value` property. is it now required that everyone switches to `v-model` ?

v-model is like value. But with both get and set.
Also like `:value.sync=""` but it will listen to input or change depending on the html element.

**Comment by PVince81** [comment]
so regarding "value" we saw that one needs to pass in a `Date` object, should we move forward and remove the `String` type from the implementation to make sure Vue will display warnings when used improperly ? @skjnldsv

**Comment by skjnldsv** [comment]
Yes, removing should be enough to not mislead :)
