### ISSUE TITLE
app-navigation-toggle icon

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-vue#346]
The `app-navigation-toggle` was a hamburger icon before (in nextcloud/server). Since #339, it is a three-dot icon. For me, the hamburger icon is more clear since it's emulates the navigation items. But at least, it should be the same as in non-vue apps.

**Comment by skjnldsv** [comment]
Ooh, that is an error, I copied the wrong file! :see_no_evil:

**Comment by skjnldsv** [comment]
Hum, wait a second, it is not a three dot on my dev setup: https://github.com/nextcloud/nextcloud-vue/blob/7230fc7458adddd277af8b599c42a95169047b34/src/assets/iconfont/menu.svg
I did push the correct file! :grin:

**Comment by korelstar** [comment]
Yes, but which icon do you see in an app using this stuff?

**Comment by skjnldsv** [comment]
![Capture d’écran_2019-04-11_17-11-50](https://user-images.githubusercontent.com/14975046/55968749-e8073f80-5c7c-11e9-87d8-6774dc10cf0f.png)

**Comment by korelstar** [comment]
Hmm. That's strange. I will try to investigate ...

**Comment by skjnldsv** [comment]
@korelstar clear cache?

**Comment by korelstar** [comment]
No, it's on all my browsers (Firefox and Chromium). Is there a server-side cache for this?

**Comment by skjnldsv** [comment]
@korelstar just compiling the vue components :grimacing:

**Comment by korelstar** [comment]
Did that again and again ...

**Comment by skjnldsv** [comment]
I really don't get it!
https://github.com/nextcloud/nextcloud-vue/pull/339/files#diff-8eefefb47af0b6de4f968b480786f2f7R55

**Comment by skjnldsv** [comment]
![Capture d’écran_2019-04-15_12-48-06](https://user-images.githubusercontent.com/14975046/56127115-bf34c200-5f7c-11e9-98c7-33d7af59a259.png)

Still good after 0.10 and contacts integration :man_shrugging:

**Comment by korelstar** [comment]
With release 0.10 I don't have any problems anymore.
