### ISSUE TITLE
[7.x] NcAppSidebarTabs prevents conditional NcAppSidebarTab

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#3461]
If the server responses for the store are delayed, the sidebar tabs will not load anymore, because they seem to be discarded as invalid children. 

I noticed that effect before, but it only occurred ometimes and I did not analyze that until now. Since moving all backend calls to a centralized api layer, this happens regulary (unless the server responds fast enough, as it seems). 

Static loading with `v-show=` does not solve this problem, as far as I could see (tested it, same effect). Not sure, if the static loading is the cause or `v-if=`.

Static loading causes the tabs to load, but because of `v-show`, they stay empty.
![grafik](https://user-images.githubusercontent.com/26707476/201035563-1c893114-ce35-48ac-a66e-851173533cf4.png)

Any idea how to prevent that? **This is a blocker for polls!**

**Wanted Behavior:** 
NcAppSidebarTab is not discarded as invalid child, whan loaded conditionally.

Affected code (partly): 
https://github.com/nextcloud/polls/blob/97509e53a1a487ae3985170061d26df9287b551b/src/js/views/SideBar.vue#L24-L36

https://github.com/nextcloud/polls/blob/97509e53a1a487ae3985170061d26df9287b551b/src/js/views/SideBar.vue#L89-L97

```
Ignoring invalid tab 
Object { tag: "vue-component-67-NcAppSidebarTab", data: {…}, children: undefined, text: undefined, elm: section#tab-comments.app-sidebar__tab, ns: undefined, context: {…}, fnContext: undefined, fnOptions: undefined, fnScopeId: undefined, … }
​asyncFactory: undefined
​asyncMeta: undefined
​children: undefined
​componentInstance: Object { _uid: 117, _isVue: true, __v_skip: true, … }
​componentOptions: Object { Ctor: VueComponent(options)
, propsData: {…}, tag: "NcAppSidebarTab", … }
​context: Object { _uid: 77, _isVue: true, __v_skip: true, … }
​data: Object { attrs: {}, scopedSlots: {…}, on: undefined, … }
​elm: <section id="tab-comments" class="app-sidebar__tab" data-v-268dd44a="" aria-labelledby="comments" tabindex="0" role="tabpanel" data-v-7339f406="" aria-hidden="true">
​fnContext: undefined
​fnOptions: undefined
​fnScopeId: undefined
​isAsyncPlaceholder: false
​isCloned: false
​isComment: false
​isOnce: false
​isRootInsert: true
​isStatic: false
​key: undefined
​ns: undefined
​parent: undefined
​raw: false
​tag: "vue-component-67-NcAppSidebarTab"
text: undefined
​<prototype>: Object { … }
```

```
[Vue warn]: Mixing tabs and non-tab-content is not possible. [vue.runtime.common.dev.js:4511](webpack:///polls/node_modules\vue\dist\vue.runtime.common.dev.js)
    warn VueJS
    updateTabs node_modules\@nextcloud\vue\dist\index.module.js:2
    children node_modules\@nextcloud\vue\dist\index.module.js:2
    VueJS 11
    set src\js\store\modules\appSettings.js:69
    set src\js\store\modules\appSettings.js:68
    wrappedMutationHandler node_modules\vuex\dist\vuex.esm.js:844
    commitIterator node_modules\vuex\dist\vuex.esm.js:466
    commit node_modules\vuex\dist\vuex.esm.js:465
    _withCommit node_modules\vuex\dist\vuex.esm.js:624
    commit node_modules\vuex\dist\vuex.esm.js:464
    boundCommit node_modules\vuex\dist\vuex.esm.js:409
    commit node_modules\vuex\dist\vuex.esm.js:796
    _callee$ src\js\store\modules\appSettings.js:86
    tryCatch src\js\store\modules\appSettings.js:2
    _invoke src\js\store\modules\appSettings.js:2
    defineIteratorMethods src\js\store\modules\appSettings.js:2
    asyncGeneratorStep src\js\store\modules\appSettings.js:3
    _next src\js\store\modules\appSettings.js:4
    (Async: promise callback)
    asyncGeneratorStep src\js\store\modules\appSettings.js:3
    _next src\js\store\modules\appSettings.js:4
    _asyncToGenerator src\js\store\modules\appSettings.js:4
    _asyncToGenerator src\js\store\modules\appSettings.js:4
    get src\js\store\modules\appSettings.js:98
    wrappedActionHandler node_modules\vuex\dist\vuex.esm.js:851
    dispatch node_modules\vuex\dist\vuex.esm.js:516
    boundDispatch node_modules\vuex\dist\vuex.esm.js:406
    _callee2$ src\js\mixins\watchPolls.js:169
    tryCatch src\js\mixins\watchPolls.js:8
    _invoke src\js\mixins\watchPolls.js:8
    defineIteratorMethods src\js\mixins\watchPolls.js:8
    asyncGeneratorStep src\js\mixins\watchPolls.js:9
    _next src\js\mixins\watchPolls.js:10
    _asyncToGenerator src\js\mixins\watchPolls.js:10
    _asyncToGenerator src\js\mixins\watchPolls.js:10
    fetchUpdates src\js\mixins\watchPolls.js:187
    _callee$ src\js\mixins\watchPolls.js:113
    tryCatch src\js\mixins\watchPolls.js:8
    _invoke src\js\mixins\watchPolls.js:8
    defineIteratorMethods src\js\mixins\watchPolls.js:8
    asyncGeneratorStep src\js\mixins\watchPolls.js:9
    _next src\js\mixins\watchPolls.js:10
    _asyncToGenerator src\js\mixins\watchPolls.js:10
    _asyncToGenerator src\js\mixins\watchPolls.js:10
    watchPolls src\js\mixins\watchPolls.js:153
    $route src\js\App.vue:67
    invokeWithErrorHandling VueJS
```

**Comment by raimund-schluessler** [comment]
A tab is recognized as invalid if
- it is no component at all
- it does not have the `name` prop set
- it does not have the `id` prop set
- and if it is missing the icon (either slot or prop)

see here:
https://github.com/nextcloud/nextcloud-vue/blob/75d490b9eaee5948d62d9e8bd7d801bff0114928/src/components/NcAppSidebar/NcAppSidebarTabs.vue#L247-L249

So one of the conditions seems to not be met. My guess would be the icon, but this would need to be debugged.
Could you maybe reproduce this with an example in the docs, so it would be easier to debug?

I use it very similarly to you in the Tasks app, just without async loading and it works just fine here:
https://github.com/nextcloud/tasks/blob/145f3f5da27b12e163cb523e3e87cbae37a9b0bc/src/views/AppSidebar.vue#L201-L213

Also, this doesn't need to be a prop, by the way:
https://github.com/nextcloud/polls/blob/97509e53a1a487ae3985170061d26df9287b551b/src/js/views/SideBar.vue#L28
you can just use
```vue
id="configuration"
```
instead, although I don't think it solves your issue, but who knows.

**Comment by dartcafe** [comment]
And now the situation by using `v-if`

```html
<NcAppSidebarTab v-if="acl.allowEdit"
	:id="'configuration'"
	:order="1"
	:name="t('polls', 'Configuration')">
	<template #icon>
		<SidebarConfigurationIcon />
	</template>
	<SideBarTabConfiguration />
</NcAppSidebarTab>
```
Description | Screen
-|-
The initial state is `acl.allowEdit=false`, but after loading the acl, it is `true`. Luckily in this example all tabs got loaded (how it should be): | ![grafik](https://user-images.githubusercontent.com/26707476/201192420-d87c1b67-f69f-4fbf-9e22-78c647a521a8.png)
Then setting `acl.allowEdit=false`; All tabs get removed (What is correct, at least Comments should stay). | ![grafik](https://user-images.githubusercontent.com/26707476/201193216-08c72586-e8c5-41de-af58-186111b50bed.png)
Switching back to `acl.allowEdit=true` loads just 4 out of 5 tabs. (Configuration is missing)|![grafik](https://user-images.githubusercontent.com/26707476/201193412-435f519d-e6ff-4474-930e-10b6ba0e1b57.png)
The expanded debug log entry |![grafik](https://user-images.githubusercontent.com/26707476/201194191-a9d46faa-e384-43fd-b4a5-f4c6a5ed96a7.png)

There seems to be something broken in the reactivity.

**Comment by dartcafe** [comment]
I have to come back to it, because it is really a problem. 

But it seems, I found a workaround by adding a senseless `icon` attribute to the NcSidebarTab.

I guess the check for an icon attribute fails if none is set and the icon slot is not fully mounted at this time. So it seems to work for the moment, but my fear is, it comes back when the icon attribute gets removed. 

On the other hand, I wonder if this check is really necessary, since the correct usage of the components should base on the responsibility of the programmer. 

@skjnldsv @raimund-schluessler

**Comment by skjnldsv** [comment]
> since the correct usage of the components should base on the responsibility of the programmer

We started going away from this more and more yep.
Initially having sanity checks for devs.

Nonetheless, you're experiencing something different.
We never designed the sidebar to have that reactive tabs. The tabs are defined on AppSidebar init and then the content can change reactively.

this is why you have v-if/show reactivity issues. We had that in the past.



> But it seems, I found a workaround by adding a senseless `icon` attribute to the NcSidebarTab.

I guess we should improve our icon slot detection from the `AppSidebar`.
Feel free to dive into that and put a watcher on `tab.$slots` to see if and when you can find another thing to watch for.
Maybe the fact that the tab is not rendered yet means the icon slot is undefined :shrug:

**Comment by raimund-schluessler** [comment]
@dartcafe could you please check whether #3874 fixes your issue? I moved `NcAppSidebarTabs` to use a render function and it behaves a lot more reactive now :wink:

**Comment by dartcafe** [comment]
As soon as possible. I am a little bit short of time atm.
