### ISSUE TITLE
Extend default text fields attributes programmatically instead of defining every. single. use case.

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#3479]
This is not vue's job to help you understand default html components

Props should be here to define specific data that we are actually manipulating or using (value for example)
Here we're reinventing the wheel and literally no one will be able to maintain such [a crazy amount of use-cases and documentation](https://github.com/nextcloud/nextcloud-vue/blob/543d72d1a7a25251400ec4f1857e44b89ac98899/src/components/NcTextField/NcTextField.vue#L159-L411)

My suggestions are:
- Extend from a typing POV an HTMLInputElement props (search online, vue supports it, typescript might be useful here)
- Or Bind `$attrs` too so we can use unknown/undocumented attributes

## Example
Example given, just trying to add `maxlength` and `minlength` makes the component non functional
![image](https://user-images.githubusercontent.com/14975046/201921217-129e6430-87a5-4974-8a23-c961206bfd54.png)

To fix this I would have to create a PR here, document, wait for a new release, upgrade server and finally be able to use `min`/`maxlength`
That's not an acceptable development flow if we want to be efficient.

## Conclusion
Let's not try to re-invent the wheel and lock ourselves in the process please :confused: 

cc  @marcoambrosini @nickvergessen @raimund-schluessler @ChristophWurst @artonge @CarlSchwan @dartcafe

**Comment by artonge** [comment]
I am fine with binding `$attrs`

**Comment by CarlSchwan** [comment]
Yes please, I lost so much time on the login page just because I had to do some changes first to nextcloud-vue. Also can we make NcInputField public, while at it?

**Comment by dartcafe** [comment]
Agree. 
That is the point:
> To fix this I would have to create a PR here, document, wait for a new release, upgrade server and finally be able to use ...

**Comment by skjnldsv** [comment]
> Also can we make NcInputField public, while at it?

Any reason behind this?
Is the `NcTextField` not enough?
