### ISSUE TITLE
Sidebar was turned into scrollable item which is a breaking change in 7.1.0 needs to bump to 8.0 or work differently

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#3533]
Making the whole sidebar scrollable is problematic when the sidebar is very tall. For example, in the Comments section of Files if there are a lot of comments, or in Talk during calls, when the chat is shown in the sidebar; in the case of Talk it is specially bad, as the newest messages are at the bottom. Due to this you need to scroll all the way down to see the messages, and you need to scroll all the way up to change to another tab (and besides being uncomfortable to use it also breaks scrolling because the older messages are loaded when you scroll to the top).

But even ignoring Talk the (in my opinion) usability concerns regarding excesive scrolling apply too to Files, for example.

Therefore I would suggest a different fix. Instead of removing `min-height: 0` it could be replaced by `height: 100%`. This way the tabs would get the height of the sidebar, so it would be scrollable if the header and the tab do not fit in the screen, but the general scrolling would end when the tab headers are at the top, at which point the internal scrolling of the tab contents would start. With this you will always be able to switch between tabs, and if you need to show the sidebar header again it would be just scrolling its own height rather than the full sidebar height.

With that fix Talk would still need some further work, because the "New message" area would be hidden and the user would need to scroll down until the tab is fully shown to see it. But even if we just end [setting `min-height: 0` for Talk for the time being](https://github.com/nextcloud/spreed/pull/8418) at least it should fix the issues in Files (I have not checked other apps, though).

However... please take all that with a pinch of salt, because my CSS is quite rusty and maybe that introduces more issues than it fixes ;-)

_Originally posted by @danxuliu in https://github.com/nextcloud/nextcloud-vue/issues/3444#issuecomment-1334229784_

**Comment by nickvergessen** [comment]
cc @Pytal @skjnldsv as reviews. Any thoughts from your side about a different fix possibility so it's not breaking?
But 7.1.0 is already out, so would need a quick 7.1.1

**Comment by Pytal** [comment]
@szaimen might know more?

**Comment by szaimen** [comment]
I'll check when I have time (currently busy with university).

My approach would be adding a prop that allows to enable/disable the behaviour.

**Comment by skjnldsv** [comment]
> So need to bump the major version?

Ah, not great indeed!
I would revert and release 7.1.1.
Then branch off and apply to master again

**Comment by szaimen** [comment]
Revert is here: https://github.com/nextcloud/nextcloud-vue/pull/3554

However this reintroduces https://github.com/nextcloud/server/issues/34777.

**Comment by nickvergessen** [comment]
Which can be fixed with a v-deep on the one place (but note it will make the activity and comments tab scroll away the header bar etc.
I think it should instead be fixed in another way, just don't know how exactly. Maybe a media query for the low height?

**Comment by szaimen** [comment]
> but note it will make the activity and comments tab scroll away the header bar etc.

Yes, this was the compromise that was discussed with @jancborchardt

**Comment by szaimen** [comment]
You can see this in https://github.com/nextcloud/server/issues/34777#issuecomment-1315762254

**Comment by szaimen** [comment]
PR is merged

**Comment by skjnldsv** [comment]
> release 7.1.1

Can you take care of this onetoo? :)

**Comment by szaimen** [comment]
> > release 7.1.1
> 
> Can you take care of this onetoo? :)

No, feel free to do it this time 👍
