### ISSUE TITLE
NcActions broken in docs

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3542]
The `NcActions` in the docs at https://nextcloud-vue-components.netlify.app/#/Components/NcActions currently look like this:

![Screenshot 2022-12-03 at 13-56-05 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/205442001-629ab1cd-e944-42ce-ba30-b00d41ca344f.png)

**Comment by raimund-schluessler** [comment]
Seems like this rule
https://github.com/nextcloud/nextcloud-vue/blob/7bd86179e9c5e866dc3986ddfb0117c2c5b1ee0c/styleguide/assets/server.css#L1461-L1474
now targets the button in the Action entries.

**Comment by raimund-schluessler** [comment]
Turns out it's this commit ee4d2403824fbb6c6d4af2a6f78fb2b330696d96 belonging to this PR https://github.com/nextcloud/nextcloud-vue/pull/3435.
@Pytal could you maybe have a look here? Adding `:not([class^=vs__])` to the button CSS classes somehow messes with the Actions component (but I don't really understand why, though).

**Comment by Pytal** [comment]
Fixed in https://github.com/nextcloud/server/pull/35165 @raimund-schluessler and tested the styleguide with the generated server.css

Will be fixed here with the next automated styling update from server PR

**Comment by raimund-schluessler** [comment]
Thanks for checking. Looking forward to the fix.
