### ISSUE TITLE
NcActions: Can not assign `data-` attribute to submenu item

### ISSUE THREAD

**Issue by susnux** [nextcloud/nextcloud-vue#3547]
I have a menu like the following on:

```html
<NcActions data-foo-actions="header">                        <!-- works: data is assigned -->
    <NcActions :inline="3" data-foo-actions="align-header">  <!-- works: data is assigned -->
         <NcActionButton data-foo-action="align-left" ...>   <!-- does not work: data is NOT assigned -->
         <NcActionButton data-foo-action="align-center" ...> <!-- does not work: data is NOT assigned -->
         <NcActionButton data-foo-action="align-right" ...>  <!-- does not work: data is NOT assigned -->
    </NcActions>
    <NcActionButton data-foo-action="..." >                  <!-- works: data is assigned -->
    <!-- ... -->
</NcActions>
```

The menu works as expected, but the `data-...` attributes are not assigned to the most inner NcActionButtons, while assigning classes works I would expect that all additional attributes I add to those actions will be rendered as well.

* Using `@nextcloud/vue` version `7.1.0`

**Comment by skjnldsv** [comment]
@susnux you have an NcActions WITHIN another NcActions ??

**Comment by susnux** [comment]
> you have an `NcActions` WITHIN another `NcActions` ??

Yes e.g. for submenu.
Is this not supported? I could not find anything about it but thought that would be the simplest way.

**Comment by skjnldsv** [comment]
> Is this not supported?

Not at all :sweat_smile: 
I'm actually surprised it worked. If it's not documented (seeing the great docs the `Actions` component have), it means it's not supported :+1: 

We don't do submenus at Nc, those are bad for accessibility per design :/
In which app are you doing that?

If you want to do submenus, you can change the context and change the entire actions list with an additional "back" icon at the top entry.
![image](https://user-images.githubusercontent.com/14975046/206439682-c6e56ebe-cb3c-4c35-940e-e7aa418c85a8.png)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/text/pull/3530

**Comment by susnux** [comment]
I think this can be closed as *not planned* / *wont fix*?
