### ISSUE TITLE
[BITV]: Add title prop to components for native tooltips

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/nextcloud-vue#3550]
Part of https://github.com/nextcloud/nextcloud-vue/issues/2503

  - [ ] NC Vue components: (extend functionality)
      -  NcActionTextEditable (not needed for files && files_sharing)
      -  NcActionInput (not needed for files && files_sharing)
      -  NcButton
      -  NcAvatar
      -  NcAppSidebar
      - NcActions
      - NcActionLink

**Comment by ChristophWurst** [comment]
Items moved into https://github.com/nextcloud/server/issues/35770 and https://github.com/nextcloud/server/issues/35654 respectively.
