### ISSUE TITLE
Make it possible to have a disabled action

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#356]
This is something to add once @skjnldsv finished the action components rework. It would be great if actions with a callback could have a disabled state, e.g. because the operation is not allowed or something is still being loaded. It might also make sense for inputs like texts and checkboxes.

**Comment by jancborchardt** [comment]
@jenniferpiperek and I were talking about this among other things and she proposed that when we show all items in full opacity, we can use opacity for disabled states. :)

Of course there should also still be notices on why something is disabled, e.g. as tooltip which will show on hover or on tap.

**Comment by skjnldsv** [comment]
Hum, we use the .5/.7/1 opacity on a lot of others places on nextcloud.
I would keep the disabled state to no hover feedback + .5 opacity. :)

And with default cursor :)

**Comment by jancborchardt** [comment]
Yes, and the idea of Jenni was that (I'm thinking except in the header bar) we don't use transparency so much anymore.

For example if you check out the conversations list in the Talk app navigation, all the chatd except the selected one look disabled in a way.

Similarly for the app-content-list component we don't use opacity but the full row background, which makes it much easier to see what is active. :)

**Comment by ma12-co** [comment]
What about the blue border on the left, are we getting rid of it as well for disabled actions? 

![Screenshot_20190826_170147](https://user-images.githubusercontent.com/26852655/63700481-46dfe680-c823-11e9-8cf8-87051b600ec0.png)

**Comment by skjnldsv** [comment]
Well, there should not be a blue border if there is no focusable class in an action. Like ActionText. It doesn't have a .focusable class, so the focus manager method in Actions don't apply any blue border to it :)

**Comment by ma12-co** [comment]
Right, but toggling the `focusable` class doesn't affect the hover behavior, you still get the blue shadow on hover even if you don't have apply it. Should we add this to the focus manager in the `Actions` component?

**Comment by skjnldsv** [comment]
Ah, I thought I removed it, well.
Since the mouse is also managing the focus, we shouldn't nee the hover state anymore :)

**Comment by ma12-co** [comment]
working on this here  #550

**Comment by ma12-co** [comment]
@nextcloud/vue @jancborchardt Of all the actions, which ones do you think should have the possibility to be disabled? (grayed out / not clickable / no hover feedback / tooltip)?

**Comment by skjnldsv** [comment]
@ma12-co all of them except the text only one?

**Comment by ma12-co** [comment]
Ok!

**Comment by ma12-co** [comment]
#551

**Comment by skjnldsv** [comment]
Fixed in 551
