### ISSUE TITLE
NcInputField possible regression: Text box border no longer visible

### ISSUE THREAD

**Issue by calvinrw** [nextcloud/nextcloud-vue#3576]
After upgrading from 7.0.1 to 7.2.0, `NcInputField` text boxes no longer have a visible border. Expected, previous appearance:

![Screenshot_2022-12-17_18-57-18](https://user-images.githubusercontent.com/687129/208272028-856994a5-1138-4ad6-828b-2fc2adb70d10.png)

New, presumably incorrect appearance:

![Screenshot_2022-12-17_18-57-04](https://user-images.githubusercontent.com/687129/208272023-8c91865a-701c-4a06-be40-2e23a0c7a0c7.png)

I traced this change to 26b548572065e1b9302a264986945b1042ed2754, which set the input element's border color to use a different CSS variable. If I use Firefox's developer tools to manually override this and apply the original style, the border of the component's text box is visible, as expected.

So obviously reverting that commit fixes the issue, but I have to assume there was a reason behind the change in the first place. I have not tested under any unique theme / high-contrast scenario; I have only been using the default 'light' theme.

**Comment by raimund-schluessler** [comment]
Which version of Nextcloud do you use? `@nextcloud/vue 7.x` is only compatible with Nextcloud server 25 and above where the variable is defined.

**Comment by calvinrw** [comment]
Thanks for the reply. It turns out this wasn't a `@nextcloud/vue` issue after all. When I initially reported this issue, I was using Nextcloud 25.0.1. Upgrading to 25.0.4 has fixed it.
