### ISSUE TITLE
Allow customizing the title tag in empty content

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/nextcloud-vue#3672]
When visiting the collectives app there's the list of collectives on the left and empty content on the right.
It would be nice if the title in the empty content was an `h1` so that screen readers pick it as the main title of the page.
(see https://github.com/nextcloud/collectives/issues/513, https://github.com/nextcloud/collectives/issues/159#issuecomment-1381781103)

I see various ways of achieving this:
* wrap the title in a title slot that can be overwritten
* ~~add a `titleLevel` prop that defaults to `2` and determines the level of the heading~~
* ~~add a `titleTag` prop that defaults to `h2` and selects the tag to use in the title.~~

My preference would be the slot.

**Comment by raimund-schluessler** [comment]
If we do it, we should do it with a slot.
