### ISSUE TITLE
AppNavigationToggle component - changing icon on toggle

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/nextcloud-vue#3688]
## Problem
As a new member and a NextCloud user, I was confused by this sidebar toggle button, which (in open state) carries an incorrect message from the point of view of UX:
![image](https://user-images.githubusercontent.com/93392545/215119311-4b0eb10a-24c4-4ab6-8f98-0bbfab6db37e.png)
It looks like there is a menu or something else to open, when it actually closes sidebar.

## Proposal
There is a `MenuOpenIcon` in `vue-material-design-icons` library, which we can apply to the button in open state. Combination of 'hamburger' and 'chevron-left' in icon contains a message: 'You can slide it to the left', which i find more appropriate.

Closed | Open
---|---
![image](https://user-images.githubusercontent.com/93392545/215117705-1de25c6b-fcde-4fa6-be81-7d1fd77fb152.png) | ![image](https://user-images.githubusercontent.com/93392545/215117781-42cafbfb-76a8-461d-91d7-f8ac65ec7d88.png)

## Code implementation
Proposal can be achieved by replacing code mentioned below:
https://github.com/nextcloud/nextcloud-vue/blob/58b5c435979784c5143c1b539e52c9ada826981f/src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue#L33
with conditional rendering of icon:
```
	<MenuOpenIcon v-if="open" :size="20" />
	<MenuIcon v-else :size="20" />
```

**Comment by raimund-schluessler** [comment]
@jancborchardt @nimishavijay

**Comment by nimishavijay** [comment]
This icon is actually great! I'm thinking it could be more useful for the right sidebar, there were multiple issues about the icon for that being confusing, and this `MenuOpenIcon` sounds like a better fit there :)

**Comment by nimishavijay** [comment]
@jancborchardt alright! We can look for a different set of sidebar icons then :)
