### ISSUE TITLE
Netlify deploy preview build uses unsupported node version

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3705]
The netlify build outputs a unsupported engine warning:
```
11:40:54 AM: npm WARN EBADENGINE Unsupported engine {
11:40:54 AM: npm WARN EBADENGINE   package: '@nextcloud/vue@7.5.0',
11:40:54 AM: npm WARN EBADENGINE   required: { node: '^16.0.0', npm: '^7.0.0 || ^8.0.0' },
11:40:54 AM: npm WARN EBADENGINE   current: { node: 'v14.21.2', npm: '7.24.2' }
11:40:54 AM: npm WARN EBADENGINE }
```

Probably not a big deal, but bumping the node version might not be a bad thing. I just didn't find any config to do so.

@skjnldsv Do you have an idea where to do this?

**Comment by skjnldsv** [comment]
Done, you have to change that on netlify
https://app.netlify.com/sites/nextcloud-vue-components/settings/deploys

**Comment by skjnldsv** [comment]
![image](https://user-images.githubusercontent.com/14975046/216029132-3f7f1b16-8cab-4333-a52b-41f30dc1b404.png)
