### ISSUE TITLE
NcActions with `tertiary-no-background` has background when open

### ISSUE THREAD

**Issue by susnux** [nextcloud/nextcloud-vue#3720]
When using the type `tertiary-no-background` I would expect the actions toggle to never have a background assigned, but when the actions are toggled the button gets the default background assigned.

This looks a bit odd in my case:
![button with background overlays an input element](https://user-images.githubusercontent.com/1855448/216835479-79426a53-9f23-40d4-9dc9-453f52eb97f8.png)

**Comment by raimund-schluessler** [comment]
I took the liberty to create a PR, so one can check it out live: #3724.
