### ISSUE TITLE
`NcButton` tertiary-no-background should have opacity hover effect

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3727]
But seems like the `NcActions` component also doesn't have a hover state? There should be an explicit hover state indicated by, for eg. opacity of the icon :)

_Originally posted by @nimishavijay in https://github.com/nextcloud/nextcloud-vue/issues/3724#issuecomment-1419112045_

The `NcButton` component of type `tertiary-no-background` has no hover effect currently. As per the comment above, we should add an opacity effect for the icon/text.

**Comment by raimund-schluessler** [comment]
@nimishavijay Which effect should we use for this, opacity or color?
We could use one of them, which seem quite similar:
```css
color: var(--color-text-lighter);
opacity: .7;
```
The thing is just, I am not aware of any case where we do something similar, so a decision here would be very helpful 🙂

**Comment by nimishavijay** [comment]
We could use `--color-text-lighter` since it's already a variable, so more standard :)
`--color-text-maxcontrast` also has the same value (`#767676`) so that could also work? what do you think? cc @marcoambrosini who works with variables way more than I do

**Comment by marcoambrosini** [comment]
We removed it at some point because when these buttons were mixed with other elements there was a mismatch in colors, and the hover feedback could be barely appreciated since the area of the icon is so small. 

So the hover feedback for these buttons is the cursor change

**Comment by marcoambrosini** [comment]
https://user-images.githubusercontent.com/26852655/217545675-cbceef3d-e0c2-40a1-ad2b-ccc5acb25dca.mov

as an example, here the two tertiaries are used very close to each other. Lightnening the `no-background` one to add the hover effect would diminish contrast and the two buttons would look weird having two different icon colors.

**Comment by raimund-schluessler** [comment]
> We removed it at some point because when these buttons were mixed with other elements there was a mismatch in colors, and the hover feedback could be barely appreciated since the area of the icon is so small.
> 
> So the hover feedback for these buttons is the cursor change

Fine with me. Shall we close this then @nimishavijay?

**Comment by nimishavijay** [comment]
Yes, sounds good! Thanks for the clarification @marcoambrosini :)
