### ISSUE TITLE
Use `NcSelect` instead of `NcMultiselect` in the components

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3743]
Since `NcMultiselect` got deprecated, we should stop using it in the components itself and use `NcSelect` instead.

Means, we need to migrate here:
- [x] `NcActionInput` #3760
- [x] `NcTimezonePicker` #3781
- [x] `NcSettingsSelectGroup` #4120
https://github.com/nextcloud/nextcloud-vue/blob/4ac3029b10dc54f68a451f3496bbf6bef5272a37/src/components/NcSettingsSelectGroup/NcSettingsSelectGroup.vue#L25-L41
- [x] `NcSearch` #4247
https://github.com/nextcloud/nextcloud-vue/blob/026afe9a4c8959be853cccbef825fe7b6da8398e/src/components/NcRichText/NcReferencePicker/NcSearch.vue#L3-L10
- [x] `NcProviderList` #4247
https://github.com/nextcloud/nextcloud-vue/blob/026afe9a4c8959be853cccbef825fe7b6da8398e/src/components/NcRichText/NcReferencePicker/NcProviderList.vue#L3-L8

@Pytal @susnux Just for reference.

**Comment by Pytal** [comment]
`master` currently targets v7 major, so this breaking change will have to be done for v8

**Comment by raimund-schluessler** [comment]
> `master` currently targets v7 major, so this breaking change will have to be done for v8

I think it doesn't have to be a breaking change if we do it right.

**Comment by Pytal** [comment]
> I think it doesn't have to be a breaking change if we do it right.

Could review a non-breaking PR if you'd be so inclined then :)

**Comment by raimund-schluessler** [comment]
@mejo- or @julien-nc Would one of you have time to move `NcSearch` and `NcProviderList` to use `NcSelect` as well? I think that would be nice, as `NcSelect` is also more accessbile.

**Comment by julien-nc** [comment]
@raimund-schluessler Yes sure, done in #4247

**Comment by raimund-schluessler** [comment]
Closed with #4247.
