### ISSUE TITLE
AppNavigationItem extensions necessary for Talk

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#376]
* Counter should be possible to be String:
  - we use logic like `unreadMessages > 99 ? '99+' : unreadMessages` so it doesn't break with 3+ digit unread counts.
* Have multiple "counters":
  - Apart from the unread counter, we also have a counter `@` which signals that you were mentioned in a chat
* Counter should have assignable classes (at least primary, default grey, or none) (used for the @-mention to draw more attention to it)
* Separator in the actions
* iconUrl should be outside of the padding, just like the `icon` when it is using a CSS (see screenshot 2)
* Allow input as an option for the AppNavigationNew for search/filtering of the list as well as creating new entries
* Allow to have a favorite (generic icon) marker overlapping the `icon`/`iconUrl`

See screenshot for current example:
> ![Bildschirmfoto von 2019-05-02 15-22-24](https://user-images.githubusercontent.com/213943/57078348-65f3bf00-6cee-11e9-980f-d5d8ac51d958.png)

icon vs. iconUrl:
> ![Bildschirmfoto von 2019-05-02 12-33-00](https://user-images.githubusercontent.com/213943/57079274-4eb5d100-6cf0-11e9-9b6e-4158568b8eae.png)

**Comment by ma12-co** [comment]
@nickvergessen @skjnldsv  Everything but the multiple

**Comment by korelstar** [comment]
@ma12-co 
I like the separator between actions. As far as I can see, there is no official component for this? The current implementation looks more like a hack:

https://github.com/nextcloud/spreed/blob/935c84464527084eb8119d204b5c81d11dc6263f/src/components/Navigation/ConversationsList/Conversation.vue#L52

Shouldn't we make a `ActionSeparator` component from this?

**Comment by ma12-co** [comment]
> Shouldn't we make a ActionSeparator component from this?

@korelstar  it makes a lot of sense to me :)

**Comment by korelstar** [comment]
Please see #718 for a new ActionSeparator component.
