### ISSUE TITLE
`NcSelect` with `:no-wrap="true"` styling broken

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3808]
@susnux I just noticed that these lines
https://github.com/nextcloud/nextcloud-vue/blob/9dd000a8f8251dc8fa501f995326411497084bf6/src/components/NcSelect/NcSelect.vue#L1025-L1030
added in #3759 create issues when the `NcSelect` component has `:no-wrap="true"`set. See here:
![Screenshot 2023-02-22 at 12-45-19 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220611641-f2789437-48d1-4850-b4ee-cde8dc4339bd.png)

**Comment by mejo-** [comment]
To discuss this here rather than [in the closed PR](https://github.com/nextcloud/nextcloud-vue/pull/3759#discussion_r1114236353):

I think we should get this sorted out before releasing 7.7.0. @susnux would you prefer to look for a fix or to revert the PR for 7.7.0?

**Comment by susnux** [comment]
Is there a date 7.7.0 is scheduled for? Maybe I find some time today, but no later than tomorrow for looking into this.

**Comment by mejo-** [comment]
> Is there a date 7.7.0 is scheduled for? Maybe I find some time today, but no later than tomorrow for looking into this.

That's perfectly fine, thanks a lot @susnux. Releasing tomorrow should be alright.
