### ISSUE TITLE
`NcDatetimePicker`s do not match the consistent NcAction style

### ISSUE THREAD

**Issue by susnux** [nextcloud/nextcloud-vue#3809]
With #3784 (thanks to @raimund-schluessler ) almost all `NcAction...` have a consistent style , except the `DatePicker`.

![image](https://user-images.githubusercontent.com/1855448/220627577-d42d1029-11cd-42e2-9bf2-9abbb6a348bb.png)

* The default `NcDatetimePicker`
  * does not use a material icon so the icon stands out from the other actions.
  * does not have the same border style
  * the right margin of the icon looks smaller than the others (but might be only because of the different icon style)
* The native `NcDatetimePicker`
  * <del>looks like there is too much margin on the right side of the icon (compared to the other icons, like for password input or the submit on text inputs)</del> (not possible, see comments below)

**Comment by raimund-schluessler** [comment]
The icon for the native datepicker comes from the browser, and I couldn't figure out a way how to style it yet (or even just remove it to put a custom one).

**Comment by susnux** [comment]
> The icon for the native datepicker comes from the browser, and I couldn't figure out a way how to style it yet (or even just remove it to put a custom one).

Indeed, seems like only webkit browsers allow styling the icon.
