### ISSUE TITLE
Circular dependency between `@nextcloud/vue` and `@nextcloud/vue-richtext`

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#3812]
With https://github.com/nextcloud/nextcloud-vue/pull/3708 we got into the unfortunate situation of a circular dependency between `@nextcloud/vue` and `@nextcloud/vue-richtext`. `@nextcloud/vue` now requires `@nextcloud/vue-richtext` which requires `@nextcloud/vue` which requires `@nextcloud/vue-richtext` which ..., you see what I mean 🙈

As long as the two packages release only compatible minor/patch versions, this is not a critical problem. But it is already cumbersome, because where do you stop updating if one package releases an update?

However, this situation becomes a critically blocking dead-lock, if we aim for a breaking major release. This will be the case with the migration to vue3 in #3692. In order to release a vue3 compatible version of `@nextcloud/vue`, we need a vue3 compatible version of `@nextcloud/vue-richtext`, which needs a vue3 compatible version of `@nextcloud/vue`, which... oh well. This won't work.

So, I really think we need to resolve this circular dependency. My proposed solution is to merge `@nextcloud/vue-richtext` into `@nextcloud/vue`. Since they anyway pull in each other, there is not much won by maintaining two separate packages/repositories. So I think that's a good solution. Plus, it's less effort to maintain a single package over two packages. We went the same way with `@nextcloud/vue-dashboard` and it worked fine.

What do you think about that @nextcloud/vuejs and especially @julien-nc, @mejo- @juliushaertl @skjnldsv?

**Comment by mejo-** [comment]
Thanks for noticing @raimund-schluessler, good catch!

> My proposed solution is to merge `@nextcloud/vue-richtext` into `@nextcloud/vue`. Since they anyway pull in each other, there is not much won by maintaining two separate packages/repositories.

:+1: from me for that proposal.

**Comment by st3iny** [comment]
Sounds good to me. Maintaining one less library is always a great thing.

However, I'm not familiar with the vue-richtext library so I don't know if there might be a good reason for the split.

**Comment by juliushaertl** [comment]
I've actually also been thinking about moving `vue-richtext` to `@nextcloud/vue`with @julien-nc. In the beginning the package was generic so that it didn't have any nextcloud related code, that is why I started it as a separate one, but I think it might be the best to move the code over these days.

**Comment by raimund-schluessler** [comment]
Nice. I will have a look how to merge them.

**Comment by susnux** [comment]
From the user perspective (when developing NC apps) it also was not obvious why this are two different libraries.
So I think this also makes sense from that point.
