### ISSUE TITLE
`NcButton` fails to compile without direct text content in default slot

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/nextcloud-vue#3824]
Issue raised because of computed value `text()` in `NcButton`, which doesn't consider result of computed value `hasText()` properly

Template | Result
--- | ---
![image](https://user-images.githubusercontent.com/93392545/221511774-f6b613fa-7d50-4b6f-af43-18447925c720.png) | ---
![image](https://user-images.githubusercontent.com/93392545/221511717-6d001fc0-e557-4896-8b2a-68ee08d0c2c3.png) | ![image](https://user-images.githubusercontent.com/93392545/221511075-9e2d811e-5040-49fd-b0dd-5019d1546d3c.png)

### replace [line](https://github.com/nextcloud/nextcloud-vue/blob/2c949c5bde580dabf0acf7250185fa24d80b9cf7/src/components/NcButton/NcButton.vue#L313): 
```
const text = this.$slots.default?.[0]?.text.trim()
```
### with:
```
const text = this.$slots.default?.[0]?.text?.trim()
```

**Comment by raimund-schluessler** [comment]
@Antreesy Can you check if it works (better) with v7.6.0 for you? In https://github.com/nextcloud/nextcloud-vue/pull/3726, which is included in the 7.6.0 release, we moved to a render function, which doesn't anymore use the code you show.

In the docs https://nextcloud-vue-components.netlify.app/#/Components/NcButton wrapping the default slot text in a `<p>Text</p>` doesn't give a runtime error anymore (but also does not show the text, but I think that's expected).

**Comment by Antreesy** [comment]
> we moved to a render function, which doesn't anymore use the code you show.

Sorry, @raimund-schluessler, I made a reference from an old version, but in 7.7.1 runtime error still remains (updated example)

> (but also does not show the text, but I think that's expected)

Guess, it's the question to the NcButton behavior. I found it quite inconvenient to wrap a child component to `<template #icon>` and override icon styles, if I need to. Would like to use a default slot for that

**Comment by raimund-schluessler** [comment]
> > we moved to a render function, which doesn't anymore use the code you show.
> 
> Sorry, @raimund-schluessler, I made a reference from an old version, but in 7.7.1 runtime error still remains (updated example)

Alright, thanks for checking. I guess the warning is only shown in development mode and the docs run in production. Checking if text is undefined is a good idea, I think.

> > (but also does not show the text, but I think that's expected)
> 
> Guess, it's the question to the NcButton behavior. I found it quite inconvenient to wrap a child component to `<template #icon>` and override icon styles, if I need to. Would like to use a default slot for that

I think I don't really understand what you want to do. Can you show an example of what you intent to do, please? We generally try to keep everything consistent, so overwriting the style of a component should really only be done in edge cases, I would say.

**Comment by raimund-schluessler** [comment]
> > (but also does not show the text, but I think that's expected)
> 
> Guess, it's the question to the NcButton behavior. I found it quite inconvenient to wrap a child component to `<template #icon>` and override icon styles, if I need to. Would like to use a default slot for that

Ah, you mean to just put the content of the default slot where we currently put the text string? That would be fine with me, but I think it collides with the original intention of limiting the way the `NcButton` component can be used in order to keep things consistent. But that's a question to @marcoambrosini and @skjnldsv I would say.

Nevertheless, here is the fix for the first part of the issue: https://github.com/nextcloud/nextcloud-vue/pull/3827
