### ISSUE TITLE
`NcRichContenteditable` shows cursor at end of placeholder when not focused

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#3828]
Talk uses `NcRichContenteditable` for chat messages and as a user I do not expect to see a cursor at the end 

![Bildschirmfoto vom 2023-02-27 14-23-28](https://user-images.githubusercontent.com/1374172/221576102-a405e087-e301-4b0b-9955-d78ad3a338a5.png)

I expect it at the left. Just like when I focus the input.

**Comment by ShGKme** [comment]
I cannot reproduce...
Does the cursor always appears in the end of the placeholder the right for you? Or only after specific actions?
Any Web-Browser?

**Comment by ChristophWurst** [comment]
FF 110.0 (64-bit)

**Comment by ChristophWurst** [comment]
## Steps to reproduce
1. Load Talk ![Bildschirmfoto vom 2023-02-27 14-42-18](https://user-images.githubusercontent.com/1374172/221579251-861f3b6f-6d04-4ec7-92a9-fe05291057d3.png)
2. Enter some text ![Bildschirmfoto vom 2023-02-27 14-42-33](https://user-images.githubusercontent.com/1374172/221579247-28bb7f5f-11be-4331-b2e7-c270101f695c.png)
3. Remove the text ![Bildschirmfoto vom 2023-02-27 14-42-45](https://user-images.githubusercontent.com/1374172/221579242-d5b6f964-1b0f-4f62-a829-813a3d52975d.png)

**Comment by ShGKme** [comment]
Can reproduce on the Firefox on Windows.

Seems like adding absolute position fixes the problem.

**Comment by ChristophWurst** [comment]
Follow-up: https://github.com/nextcloud/nextcloud-vue/issues/3912
