### ISSUE TITLE
Text eating on shift+enter after pasting url (this twice) when post started with a mention

### ISSUE THREAD

**Issue by blizzz** [nextcloud/nextcloud-vue#3913]
When writing a chat message that starts with a mention, all written text apart of the mentions is being erased after twice pasting a URL AND hitting shift+enter. Please see this video for better understanding:

https://user-images.githubusercontent.com/2184312/226970275-5a2d93aa-5e97-4ae4-9869-aa26288d0018.mp4

You see after the pasting the second link and hitting shift+enter, the text disappeared, leaving only the mention.

cc @nickvergessen

**Comment by nickvergessen** [comment]
Cc @Antreesy

**Comment by Antreesy** [comment]
will take a look on it

**Comment by nickvergessen** [comment]
I can even reproduce on https://zurb.github.io/tribute/example/ -.-

**Comment by nickvergessen** [comment]
Fixed by https://github.com/nextcloud/nextcloud-vue/pull/3917

**Comment by nickvergessen** [comment]
Fixed by https://github.com/nextcloud/nextcloud-vue/pull/3937

**Comment by mejo-** [comment]
@nickvergessen can this issue be closed, given that it's fixed by #3937?

**Comment by nickvergessen** [comment]
I still sometimes have issues, but it's not this one.
But when copy pasting @ or mentions from other rooms or something alike some things go weird.
