### ISSUE TITLE
Missing spacing on long name ellipsis in multiselect

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#402]
nextcloud-vue v0.11.2.

With https://github.com/nextcloud/tasks/pull/412 there is a space missing in between the first and second part of the names in a multiselect, see
<img width="330" alt="multiselect_ellipsis" src="https://user-images.githubusercontent.com/2496460/57913647-5c8d5980-788d-11e9-9061-a540ec8af267.png">
("showfull" instead of "show full" and "hidethis" instead of "hide this").

~~This is because the space is cropped for these two entries, whereas it is correctly shown for the second string.~~

Edit: The string is split correctly, but the space ends up at the end of the first string, which is set to `white-space: nowrap;`, so the space is not shown there.

**Comment by raimund-schluessler** [comment]
https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Multiselect/EllipsisedOption.vue#L78

would need `white-space: pre;`.

**Comment by skjnldsv** [comment]
Fix in #403
