### ISSUE TITLE
Add info type to NcNoteCard

### ISSUE THREAD

**Issue by moan0s** [nextcloud/nextcloud-vue#4020]
As discussed in https://github.com/nextcloud/server/pull/37953 a info-type of NcNoteCard would be needed for certain types of communication to the user

As described by @nimishavijay we could use
 
- --color-primary for the icon and border
- --color-primary-light for the background

**Comment by susnux** [comment]
Fixed with https://github.com/nextcloud/nextcloud-vue/pull/4063
