### ISSUE TITLE
Action menu click outside does not close the menu with v7.10

### ISSUE THREAD

**Issue by GretaD** [nextcloud/nextcloud-vue#4030]
Tested on mail, the action menu on mail for threads and envelopes doesnt close when you click outside. You need to click the button again. The issue only happens when trying to upgrade on nc/vue 7.10.0

**Comment by ChristophWurst** [comment]
Not reproducible on https://nextcloud-vue-components.netlify.app/#/Components/NcActions?id=ncactions-1

**Comment by ChristophWurst** [comment]
Obsolete?
