### ISSUE TITLE
Not possible to mark text in any modal

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#4033]
In any of our modals, like settings in Talk or Contacts, or adding new properties in Tables or other apps, it is not possible to mark any text (except in input fields).

This makes it difficult to copy anything, e.g. if you want to search for a setting, or communicate with someone else about a thing they should enable/disable.

cc @marcoambrosini since you worked on the modal initially – in case this was intentional.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/nextcloud-vue/issues/1505
