### ISSUE TITLE
User Picker for @- mentions shows white circle for "invisible" status

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/nextcloud-vue#4042]
![image](https://user-images.githubusercontent.com/7427347/236443334-d9b37efa-ed4b-4a9a-bd19-6136e1535abd.png)

Also happens for comment field @- mentions, didn't check anywhere else.

Happens on c.nc.com.

**Comment by nickvergessen** [comment]
Not only invisible but also offline.

Taking a look
