### ISSUE TITLE
Invalid msgid in l10n/ru.pot

### ISSUE THREAD

**Issue by DmitriyStolyarsky** [nextcloud/nextcloud-vue#4051]
Need to change:
https://github.com/nextcloud/nextcloud-vue/blob/2783024e2cf3de9152785145075cfa13da4b01ce/l10n/ru.pot#L163
on:
`"Write message, use \"@\" to mention someone, use \":\" for emoji autocompletion …"`

**Comment by raimund-schluessler** [comment]
The translations are tracked on transifex. Please change the respective string there https://explore.transifex.com/nextcloud/nextcloud-vue/
