### ISSUE TITLE
Rename `title` props to `name`

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#4053]
Since we now use the `title` prop as the native html attribute, and for some components are about to deprecate its usage for specifying the name of an element with it in #4052, I wonder whether we should generally rename `title` props to `name` if they are not specifically meant for setting the native html attribute.

The benefit would be that its consistent between components and would prevent future migrations for when we want to set the native html title attribute for a component. The drawback is that it would introduce a relatively big migration effort for apps.

So I would like to know your opinion about that, before I possibly start to rename this prop.

**Comment by nickvergessen** [comment]
Sounds good I guess

**Comment by susnux** [comment]
> I wonder whether we should generally rename title props to name if they are not specifically meant for setting the native html attribute.

I agree. I think using `title` only for the native html title attribute as it is generally quite confusing if you reuse a property name which is already in use as a native html attribute.

**Comment by skjnldsv** [comment]
Also agree :+1:
