### ISSUE TITLE
Disabled multiselect has gray and white background

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#4069]
![image](https://github.com/nextcloud/nextcloud-vue/assets/1374172/7b4722fa-f75a-4a7e-af68-5573e44c8cd9)

https://nextcloud-vue-components.netlify.app/#/Components/NcMultiselect?id=ncmultiselect-1

**Comment by AndyScherzinger** [comment]
the grey "edges" on the borders as well as within the field should be light/dark matching the overall background.

**Comment by raimund-schluessler** [comment]
The optimum solution would be to migrate away from `NcMultiselect` as it is deprecated and hopefully gets removed with the next major.

**Comment by ChristophWurst** [comment]
Of course. But the apps currently being screenshotted and screencasted should not change a lot so I prefer a simple fix and then migrate for the next app release.
