### ISSUE TITLE
Action menu button should be hidden, when actions slot is empty

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#407]
Currently the actions menu button is also shown when the actions slot is empty. Clicking on the button then does not do anything (besides showing the tiny arrow below).

Code like this
```
<Modal v-if="modalOpen"
	@close="closeModal"
>
	<span>Modal content.</span>
</Modal>
```
leads to a Modal like this (see the three-dot actions menu button at the right top):
![Screenshot_2019-05-20 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/58000932-86878b80-7ada-11e9-8f49-68c08b36041e.png)

**Comment by skjnldsv** [comment]
Already fixed :)
https://github.com/nextcloud/nextcloud-vue/pull/391

**Comment by raimund-schluessler** [comment]
Sorry I didn’t find this.

**Comment by skjnldsv** [comment]
No worries ! :hugs:
