### ISSUE TITLE
Documentation is ahead of release

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#4177]
I stumbled about the deprecations for version 8 and wanted to prepare a little bit. But the docs lead to confusion (i.e. NcEmptyContent). The release version 7 still seems to use the `title` prop, but not the `name` prop. But the docs (generated from master I guess) say: "`title` is no more, use `name` instead."

Shouldn't there be a deprecation phase? Or at least a hint inside the documentation? 

Docs: https://nextcloud-vue-components.netlify.app/#/Components/NcEmptyContent
Current declaration: 
https://github.com/nextcloud/nextcloud-vue/blob/fa85aa7fb586404f5acec8ce787afcb4d9a63b3c/src/components/NcEmptyContent/NcEmptyContent.vue#LL110C1-L120C4

**Comment by szaimen** [comment]
cc @nextcloud/vuejs  I guess we would need to version the documentation...

**Comment by juliushaertl** [comment]
I just enabled building of the stable7 branch on netlify which should become available after the next push to the branch at https://stable7--nextcloud-vue-components.netlify.app/

I guess we should use that instead of the main one as a reference
