### ISSUE TITLE
Changing props of NcInputFiled resets value

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/nextcloud-vue#4191]
I am not sure, if it is a bug or by intention.

i.e. if the `success` prop or any other prop of the NcInputField changes, the input value gets reset to the bound value and the entered value gets lost.

Affects `NcActionInput` and other text fields.

**Comment by raimund-schluessler** [comment]
Could you provide an example, I cannot reproduce this in the docs, this works fine:
```vue
<template>
	<div class="wrapper">
		<NcButton @click="error=!error">Toggle error state</NcButton>
		<NcTextField :value.sync="text"
			label="Error state"
			:error="error">
		</NcTextField>
	</div>
</template>
<script>
export default {
	data() {
		return {
			text: 'error input',
			error: false,
		}
	},
}
</script>
```

**Comment by dartcafe** [comment]
Oh yes, I should have added some context. Sorry. 

The plan is to validate the input on update. But it seems, I was on the wrong trail. I used the input field without the sync modifier but the behavior is the same with a native input field. Obvious I need to go on with a temporary input value for this strategy. 

Nevermind. Thanks for your effort!
