### ISSUE TITLE
the colorpicker needs rounded corners

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-vue#4198]
As discussed with @jancborchardt and @nimishavijay, the colorpicker needs rounded corners.

See the following screenshot:
![image](https://raw.githubusercontent.com/nextcloud/documentation/02a3c92edab2984ef47758d0df8076fe3d4492c5/developer_manual/images/colour-picker.gif)

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue
