### ISSUE TITLE
Input field should always show the confirm arrow and not change its length while editing

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-vue#4201]
As discussed with @jancborchardt and @nimishavijay, the input field should always show the confirm arrow and not change its length while editing.

See this screenrecording: 
![image](https://raw.githubusercontent.com/nextcloud/documentation/02a3c92edab2984ef47758d0df8076fe3d4492c5/developer_manual/images/action-menu-new-item.gif)

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by susnux** [comment]
The placeholder issue is a separate issue and needs to be implemented on the mail app.

**Comment by ChristophWurst** [comment]
> The placeholder issue is a separate issue and needs to be implemented on the mail app.

https://github.com/nextcloud/mail/issues/8574
