### ISSUE TITLE
AppNavigation doesn't auto-close

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-vue#433]
## Steps to reproduce
1. Open an app which is **not** using `nextcloud-vue`, e.g. `files`.
2. Resize the browser window to a width of about 500 pixels.
3. See that the app-navigation hides automatically.
4. Open the app-navigation using the app-navigation-toggle.
5. Click on an item in the app-navigation, e.g. `All files` for `files` app.
6. See that the app-navigation hides automatically. :arrow_left: this is important!

7. Open an app using a current `nextcloud-vue` version, e.g. `vueexample` or `contacts`.
8. See that the app-navigation is hidden, since you browser width is still about 500 pixels.
9. Open the app-navigation using the app-navigation-toggle.
10. Click on an item in the app-navigation, e.g. `All contacts` for `contacts` app.

## What happens
The app-navigation is still open.

## What is expected
The app-navigation closes, just like in number 6.

## Background
This is executed on server in order to realize auto-close: https://github.com/nextcloud/server/blob/fd9ff581e2a92f65def3f5d3209c4328fb65416a/core/src/init.js#L235-L255

**Comment by skjnldsv** [comment]
So if I get this right, clicking an item on the navigation closes the appnavigation?

**Comment by korelstar** [comment]
Not when using `nextcloud-vue`. But it should - in mobile mode. See the linked JavaScript from server.

**Comment by skjnldsv** [comment]
I never realised this ^^
Thanks for notifying :)

**Comment by raimund-schluessler** [comment]
Superseded by https://github.com/nextcloud/nextcloud-vue/issues/2523, since the newer issue has images :tada: :wink:
