### ISSUE TITLE
OC.Dialogs.message

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#450]
There should be a Vue version of `OC.Dialogs.alert`, `OC.Dialogs.info`, `OC.Dialogs.confirm`, `OC.Dialogs.prompt`

Unlike in the current implementation, it should be possible to create custom button labels, so we stop using YES/NO modals.

**Comment by skjnldsv** [comment]
so https://github.com/nextcloud/nextcloud-vue/issues/408 ? :grin:

**Comment by georgehrke** [comment]
Oh yes, completely forgot about that one. sorry

**Comment by skjnldsv** [comment]
Go take your penitence by reviewing the pending vue prs ;)
