### ISSUE TITLE
New Slot in AppSidebar

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/nextcloud-vue#485]
Hi, 
I need a possibility to add some content on the yellow area:

![grafik](https://user-images.githubusercontent.com/24530680/61351681-a7b2f100-a86b-11e9-8c68-af76cc6d0fd0.png)

@juliushaertl 's answer:
Seems we need to extend the vue components for that. The best would be to add a dedicated slot for that here: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppSidebar/AppSidebar.vue#L70 Mind to open an issue over at the nextcloud-vue repo so we can discuss this?

**Comment by juliushaertl** [comment]
@jancborchardt Do you think it makes sense to allow apps to extend this with their own details? The use case here is that in deck we always show important card details no matter which tab is currently selected:

![image](https://user-images.githubusercontent.com/3404133/61352145-f0b77500-a86c-11e9-842a-351c9c5a5b33.png)

**Comment by jancborchardt** [comment]
Not really sure here, tend to say no. Allowing any app to add stuff here is making it too tempting to add unimportant stuff, like the issue we have for the action menus already.

For the card screenshot you show, the details like tags, due date and such are also debatably important? Participants sure, but there should be a tab for that?

@jakobroehrl what is your specific use case of adding things?



------

For the sidebar standardization we did go through ~8 of the main apps and their sidebars and analyzed them. There were some special things like the "Start call" button for Talk, but we should really try to keep things simple. We already have to wrestle with the amount of tabs and their content, which we should polish and unify before adding anything new.

**Comment by juliushaertl** [comment]
> @jakobroehrl what is your specific use case of adding things?

He is currently working on the deck vue migration, so the use case is the same ;)

> For the card screenshot you show, the details like tags, due date and such are also debatably important? Participants sure, but there should be a tab for that?

To me the three seem to be the most important ones. In any project management the attribution of when a task is due, who will handle it is the key part of a task (besides the actual task title)

But of course we could also rename the "Details" tab to "Details" and just put the 3 options into that. Since the first tab will be shown on open of the sidebar, they are still accessible as before.

**Comment by jakobroehrl** [comment]
> But of course we could also rename the "Details" tab to "Details" and just put the 3 options into that. Since the first tab will be shown on open of the sidebar, they are still accessible as before.

It would look like that:
![grafik](https://user-images.githubusercontent.com/24530680/61354545-b0f38c00-a872-11e9-9488-7294479f355c.png)

**Comment by jancborchardt** [comment]
Yep, and now the description should move into details below those 3 infos and it's already much nicer. :)
