### ISSUE TITLE
Settings input components

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#498]
In order to provide a unified settings experience we should have some components for common settings input fields as well as the general settings structure. 

We should add a set of the following components:

- SettingsSection (headline, optional info/hint text props and a slot for the content)
![image](https://user-images.githubusercontent.com/3404133/61696632-fb26b280-ad35-11e9-96b0-46fcb23ef5af.png)
- SettingsInputCheckbox
![image](https://user-images.githubusercontent.com/3404133/61696425-979c8500-ad35-11e9-87d8-a361642f41a9.png)
- SettingsInputRadioGroup
![image](https://user-images.githubusercontent.com/3404133/61696538-d0d4f500-ad35-11e9-8de0-976736c8d561.png)
- SettingsInputText
![image](https://user-images.githubusercontent.com/3404133/61696349-79cf2000-ad35-11e9-81ec-592e44463f18.png)
- SettingsSelectGroups
- SettingsSelectTags

Feel free to add other often used elements to the list

cc @nextcloud/vue

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/649
https://github.com/nextcloud/nextcloud-vue/pull/653
https://github.com/nextcloud/nextcloud-vue/pull/651
https://github.com/nextcloud/nextcloud-vue/pull/650

**Comment by raimund-schluessler** [comment]
These components exist now.
