### ISSUE TITLE
Blockquote broken on docs

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#518]
![Capture d’écran_2019-08-02_16-01-07](https://user-images.githubusercontent.com/14975046/62375563-e1a81680-b53e-11e9-9b20-e9aa762e1d39.png)
https://github.com/styleguidist/react-styleguidist/blob/7630f108aabb7fdcfb7ac5c36568328ac3a1a9d2/docs/Documenting.md#L5

This is how it is supposed to look.
But somehow we're missing some styling?
![Capture d’écran_2019-08-02_16-02-58](https://user-images.githubusercontent.com/14975046/62375652-0bf9d400-b53f-11e9-8dc1-ba8f3a44dfae.png)

https://vue-styleguidist.github.io/docs/Documenting.html#code-comments
![Capture d’écran_2019-08-02_16-03-04](https://user-images.githubusercontent.com/14975046/62375654-0c926a80-b53f-11e9-8806-c26f0da27c7b.png)

@juliushaertl ?

**Comment by juliushaertl** [comment]
I guess this is caused by the server styles added.

**Comment by raimund-schluessler** [comment]
Outdated.
