### ISSUE TITLE
Graphical glitch in active AppNavigationItem

### ISSUE THREAD

**Issue by LukeOwlclaw** [nextcloud/nextcloud-vue#547]
There is a tiny glitch (doubled blue highlight indicator) when I am opening the folders list (IMAP) in the Email addin in NC. 

![image](https://user-images.githubusercontent.com/2737900/62846422-6da10780-bcd0-11e9-8521-8a592225e90a.png)

@ChristophWurst [asked me to file an issue here](https://github.com/nextcloud/mail/issues/867).

**Comment by ChristophWurst** [comment]
thanks!

**Comment by raimund-schluessler** [comment]
This works now.
