### ISSUE TITLE
Docs with <template> tag do not show up in docs site

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/nextcloud-vue#560]
Steps: 
Include a `<template>` tag in the `<docs>` of a `.vue` file.

Expected behavior: 
The docs show up in the docs site.

Actual behavior:
The linter underlines as error the whole actual template of the `.vue` file and the documentation is not shown in the docs site. 

View the `AppNavigationItem` docs in PR  #486 and the docs build for that same PR: https://deploy-preview-486--nextcloud-vue-components.netlify.com/#/Components?id=appnavigationitem

**Comment by juliushaertl** [comment]
Are you referring to this one?

![image](https://user-images.githubusercontent.com/3404133/64013007-3085a380-cb1f-11e9-880c-87f513f9e82b.png)

Looks fine to me:
![image](https://user-images.githubusercontent.com/3404133/64013092-5ca12480-cb1f-11e9-8743-d9a2416edb39.png)


Otherwise some direct line hints would be helpful :wink:

**Comment by ma12-co** [comment]
>Are you referring to this one?

Yes!

>Looks fine to me:

Looks ok to me too now!

But the linter is still complaining!

**Comment by juliushaertl** [comment]
Do you have a link of the output? 

Looks all unrelated to me

```
> nextcloud-vue@0.12.2 lint /home/travis/build/nextcloud/nextcloud-vue
> eslint --ext .js,.vue src
/home/travis/build/nextcloud/nextcloud-vue/src/components/Multiselect/AvatarSelectOption.vue
  72:5  warning  'v-html' directive can lead to XSS attack  vue/no-v-html
  74:5  warning  'v-html' directive can lead to XSS attack  vue/no-v-html
/home/travis/build/nextcloud/nextcloud-vue/src/components/Multiselect/EllipsisedOption.vue
  25:35  warning  'v-html' directive can lead to XSS attack  vue/no-v-html
  26:47  warning  'v-html' directive can lead to XSS attack  vue/no-v-html
✖ 4 problems (0 errors, 4 warnings)
```

**Comment by skjnldsv** [comment]
@juliushaertl this is coming from our ide linter! :)

**Comment by ma12-co** [comment]
Here's what I get: 

![Screenshot_20190830_160910](https://user-images.githubusercontent.com/26852655/64027204-87e83b80-cb40-11e9-8d8a-30730b2384a3.png)

**Comment by raimund-schluessler** [comment]
Should be good now.
