### ISSUE TITLE
Create general purpose 'popover' component

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/nextcloud-vue#572]
It would be nice to have a general purpose popover component that we could use as a wrapper for Actions, DatetimePicker, ColorPicker, Contact search ?,  Settings?, Notifications?, ..

The behavior of these elements is pretty similar throughout so I think it would be nice to group the logic and not repeat ourselves, what  do you think?

**Comment by skjnldsv** [comment]
So todo:
- click-outside
- open state sync
- right-center-left alignment
- auto-shifting like the actions component

Anything else?

**Comment by juliushaertl** [comment]
Maybe we can just reuse our tooltip styles and wrap around the v-popover component of v-tooltip https://github.com/Akryum/v-tooltip#component

**Comment by skjnldsv** [comment]
@juliushaertl our tooltip style is already forked from our popovermenu ;)
