### ISSUE TITLE
Components rely on translate beeing bound to Vue.prototype.t

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#586]
With https://github.com/nextcloud/tasks/pull/586 and https://github.com/nextcloud/tasks/pull/601 I realised, that the vue-components rely on the app to bind `t` to `Vue.prototype.t` (and probably `n` to be bound to `Vue.prototype.n`).

First, as stated https://vuejs.org/v2/cookbook/adding-instance-properties.html#The-Importance-of-Scoping-Instance-Properties, instance properties should be scoped (so start with a `$`).

Second, I didn't find this in the Readme of the components, so this should either be added, or the vue-components should bind `t` to the correct prototype themself (don't know, whether this is possible).

Changing the instance properties to be scoped would be a breaking change in case the components cannot bind `t` themself.

**Comment by korelstar** [comment]
Please have a look at this discussion: https://github.com/nextcloud/nextcloud-vue/pull/439#discussion_r294136740 (unfortunately I did not found the time to do the PR I talked about).

Would that be a solution?

**Comment by skjnldsv** [comment]
Yep, it's because we want to remove it https://github.com/nextcloud/nextcloud-vue/issues/97

**Comment by skjnldsv** [comment]
@raimund-schluessler what do you suggest then in the meantime?
Importing nextcloud-l10n from the library here and use it?
With Vue.prototype.$t ?

**Comment by raimund-schluessler** [comment]
What is the plan here? Did I get it correctly that we should use
https://github.com/nextcloud/nextcloud-vue/blob/b46a4cb341bb6b90ce27daa1097ab54d6ab57fa7/src/l10n.js#L42
(or the mixin) now in every component and don't need the global OC.t and the binding to the Vue prototype anymore?
