### ISSUE TITLE
Add ActionColorpicker / show ColorPicker on ActionInput type="color"

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#607]
There should be an action to edit colours.
Would be happy to help implementing, but i'm not sure how to do it UI-wise.

**Comment by georgehrke** [comment]
cc @skjnldsv @ma12-co

**Comment by skjnldsv** [comment]
To be implemented with ActionInput and type="color" :)

**Comment by georgehrke** [comment]
@skjnldsv @ma12-co How should we proceed here? :)

**Comment by ma12-co** [comment]
I really don't like the idea of a popover opening on top of another popover. I think it's not a good design practice. Where would you need something like this @georgehrke?

**Comment by georgehrke** [comment]
> Where would you need something like this

For a calendar-picker for calendars, see #900 for example.

> I really don't like the idea of a popover opening on top of another popover. I think it's not a good design practice.

I agree that this is something we should use carefully and not too often, but we already do in other places as well. If you want to set a timeout for a share in files, you have to click the ActionsMenu to set it up and inside the ActionsMenu, it will open a DatePicker, which is also a popover.

**Comment by raimund-schluessler** [comment]
This was implemented with https://github.com/nextcloud/nextcloud-vue/pull/1662.
