### ISSUE TITLE
Allow to provide custom icon to be shown if more than one action inside Actions

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#618]
Currently, as soon as you have multiple `Action` components inside an `Actions` component, it shows the three-dot menu icon. There are scenarios ([like here in Jan's mockup](https://github.com/nextcloud/calendar/issues/1021#issue-393233730)) where you would like to replace that icon with another one.

@skjnldsv @ChristophWurst Are you fine with that change? 
In that case i will send a pull-request :)

**Comment by raimund-schluessler** [comment]
For Tasks I have a dropdown list to indicate and change the sort order which shows even two icons: the order criterium and the sort direction: https://github.com/nextcloud/tasks/blob/master/src/components/SortorderDropdown.vue#L27-L28.

![Screenshot_2019-10-02 Aufgaben - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/66025340-84a4ee80-e4f6-11e9-9198-af4c0624205e.png)


Could something like this also be considered?

PS: One of the Action components would probably also need to be adjusted to show the sort direction:

**Comment by georgehrke** [comment]
We could also replace the icon with a slot and you could just do whatever you like :)

**Comment by raimund-schluessler** [comment]
> Edit: But i think ideally you would merge those two icons into one icon.

I also thought about this, but I wondered if this would be big enough then. Will give it a try.

**Comment by skjnldsv** [comment]
> We could also replace the icon with a slot and you could just do whatever you like :)

No for this :)
Let's leave the icon as is.

Let's add a prop named `defaultIcon` or something that is set to icon-menu as default. Good enough?

@raimund-schluessler We should improve this menu, the icons set is not clear nor the  3 lines icon (which is supposed to represent the navigation menu in nextcloud)  Ideally each icons have proper visual that represent what they are, https://github.com/nextcloud/gallery/blob/master/img/dateasc.svg
https://github.com/nextcloud/gallery/blob/master/img/datedes.svg are rough examples :)
