### ISSUE TITLE
Color picker docs is broken

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#620]
![Capture d’écran_2019-10-02_12-30-54](https://user-images.githubusercontent.com/14975046/66037719-8ed3e680-e510-11e9-9d2e-1b702c2f6d7d.png)

cc @ma12-co  :)

**Comment by georgehrke** [comment]
This was fixed in https://github.com/nextcloud/nextcloud-vue/pull/638
