### ISSUE TITLE
New hover feedback for actions

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/nextcloud-vue#629]
The problem: 

Actions have a hover feedback circle that is very big and this forces us to either:
* make very tall/wide UI elements --> **uses a lot of space**;

![IMG_20191003_163522](https://user-images.githubusercontent.com/26852655/66137440-6249c880-e5fd-11e9-822e-8b9757feb85f.jpg)

* Use negative margins --> Allows smaller UI elements but **creates weird overlaps when hovered**;

![IMG_20191003_163600](https://user-images.githubusercontent.com/26852655/66137623-a6d56400-e5fd-11e9-8804-d7e842bab967.jpg)

Possible solution: 

I think that we can improve things a lot with by using this second option (negative margins), but slightly modifying the hover and focus behavior of our actions component. 
The full blown 44px circle is only necessary when navigating with the keyboard (focus state). In this case, it's more difficult to 'know where you are' in the page, and the big circle provides a nice guidance.
When we're navigating with the mouse on the other hand, we can sacrifice a bit of visibility in the hover feedback by just darkening the icon. The normal/hover/active/focus behaviors would look like this:

![IMG_20191003_165136](https://user-images.githubusercontent.com/26852655/66138054-4eeb2d00-e5fe-11e9-81c2-24e5820f3733.jpg)
This would allow us to have **decently sized UI elements and no unpleasing overlaps** (if we navigate with the mouse)

**Comment by ma12-co** [comment]
cc @jancborchardt @jenniferpiperek @skjnldsv @juliushaertl

**Comment by skjnldsv** [comment]
A bit of previous related discussion: https://github.com/nextcloud/nextcloud-vue/pull/398#issuecomment-493631525

**Comment by ma12-co** [comment]
@skjnldsv IMO it's simply not necessary to have that much feedback when hovering with the mouse, so I don't see the point in keeping it and invading other components

**Comment by skjnldsv** [comment]
Well, this is the first time it really create an issue :)
So far everything was fine. So currently it does not "invade other components"!

**Comment by ma12-co** [comment]
To me [this](https://github.com/nextcloud/nextcloud-vue/pull/398#issuecomment-493631525) is invading. Even if you try to dissimulate it and take out the border :)
I'm just suggesting we limit this to the focus behavior.. I don't know, maybe it's just a phobia I have but it just doesn't look right to me :laughing:

**Comment by skjnldsv** [comment]
Otherwise just decrease the circle for the componetn you're working on at 32px and call it a day.
Overall design looks fine and is easy to navigate with this big grey area.

> The full blown 44px circle is only necessary when navigating with the keyboard (focus state). In this case, it's more difficult to 'know where you are' in the page, and the big circle provides a nice guidance.

Also, I differ here. Anyone benefit from proper visual feedback, not only keyboards users, but any people with or without reading issues. Current feedback is noce, even on hover. It greatly help you know what you're about to do. The current size and display should NOT be changed.
