### ISSUE TITLE
@nextcloud/vue@v1.0.0

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#633]
Hello @nextcloud/vue :wave:,

now that we start releasing our new npm packages in the `@nextcloud` namespace I'm wondering when this lib is ready for a rename and/or a v1. IMO the API has been relatively stable in the last few weeks/months. And we use it for production code in server and apps.

Are we ready for `@nextcloud/vue@v1.0.0`? :)

**Comment by skjnldsv** [comment]
Good question here :)
Current master have breaking changes, meaning new minor (at least), and I keep releasing new fixes under 0.12.x. If we upgrade to this new package, it means we'll have no choice but to comply to the new appnavigation, which is quite some work. I'd like to postpone that :p

So I'd say maybe release 0.13 as 1.0.0 under @nextcloud/vue but we'd still releases fixes and patches on the old lib?

**Comment by ChristophWurst** [comment]
> but we'd still releases fixes and patches on the old lib?

Makes sense for fixes in stable releases of server :+1:

**Comment by georgehrke** [comment]
What is the status here? :) 

I would really really really like to get the vue branch merged in calendar this week and also have our  beta1. I already ported the app-navigation to the new model, so currently you have to npm link this repo. And it kind of feels wrong to publish a package where people can't just do `make` but have to do some `npm link` magic in between.

**Comment by skjnldsv** [comment]
@georgehrke let's release 1.0.0 then :)

**Comment by korelstar** [comment]
It would be nice if #577 is fixed before that release 😃

**Comment by skjnldsv** [comment]
@korelstar no time for me on this :(

**Comment by skjnldsv** [comment]
https://www.npmjs.com/package/@nextcloud/vue
