### ISSUE TITLE
Multiselect placeholder needs left padding when not focussed

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#66]
As discovered in https://github.com/nextcloud/server/pull/11765#issuecomment-429752724.

**Comment by ChristophWurst** [comment]
@MorrisJobke what browser did you test this with? On FF and Chrome this looks fine here.

**Comment by skjnldsv** [comment]
@ChristophWurst make sure this is not a conflict of scoped. Theoritecally `.multiselect` on nextcloud referes to another library we used on jQuery. You need the vue-multiselect class to force apply the theme to the vue-multiselect component. Once our package is scoped we won't need it anymore :) 
https://github.com/nextcloud/contacts/blob/226e44d7a612cd3a4d5ed0f025e50caebfb7858b/src/components/Settings/SettingsImportContacts.vue#L36

**Comment by MorrisJobke** [comment]
> @MorrisJobke what browser did you test this with? On FF and Chrome this looks fine here.

Safari

**Comment by skjnldsv** [comment]
Coming from: https://github.com/shentao/vue-multiselect/blob/28dd68a7c4b4e34346a5ede79fdc328727136dc7/src/Multiselect.vue#L330

**Comment by skjnldsv** [comment]
Fixed in https://github.com/nextcloud/nextcloud-vue/commit/02727e98ccf5f4b52f5d672d62134d319fe791b5
