### ISSUE TITLE
Some issues in right sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#680]
Initially opened these in Calendar as part of **Design polishing of right sidebar https://github.com/nextcloud/calendar/issues/1576** but @georgehrke asked me to open it here:

- [ ] Event title seems rather small and un-emphasized. In the event popover it’s 20 px, here only 16. We also played around with bolding it @ma12-co @skjnldsv, which improves this a lot?
- [ ] The menu button by default has a grey circle, which is too much emphasis. This should only happen on hover or focus.
- [x] The "x days ago" subline is not a heading so should not be `h4` but simply a `p`

What do you think?

**Comment by skjnldsv** [comment]
> * The menu button by default has a grey circle, which is too much emphasis. This should only happen on hover or focus.

You asked me to do it ^^
https://github.com/nextcloud/nextcloud-vue/pull/340
I think it's good for now, was very poorly noticeable before and it's quite an important part of the sidebar :)




> * [ ]  Event title seems rather small and un-emphasized. In the event popover it’s 20 px, here only 16. We also played around with bolding it @ma12-co @skjnldsv, which improves this a lot?
> * [ ]  The "x days ago" subline is not a heading so should not be `h4` but simply a `p`

Sure! :)
Have a look your self and post some screenshots ;)

**Comment by raimund-schluessler** [comment]
I think most of this is fixed / outdated. If you find some glitches still persist, please open a separate issue.
