### ISSUE TITLE
Ability to open actions menu upwards

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#685]
For the Mail app composer rewrite (https://github.com/nextcloud/mail/pull/2131 ) we have sticky bottom elements which include the "Send" button and next to it an actions menu.

Since it is sticky, it should of course open to the top instead of the bottom, but it doesn’t do that automatically and there also doesn’t seem to be an option for this in the documentation.

cc @ChristophWurst @juliushaertl?

**Comment by skjnldsv** [comment]
Easiest would be to use our new POpover component in the Actions, right @ma12-co ?

**Comment by ma12-co** [comment]
Yes, this will most likely be solved by #641

**Comment by skjnldsv** [comment]
See #715
