### ISSUE TITLE
ColorPicker doesn't support dark-mode

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#702]
![28997045-9E01-4E05-9084-BD1C3A0FCF3B](https://user-images.githubusercontent.com/1250540/67775091-b6aa6180-fa5e-11e9-837d-feee1410c2aa.png)

@ma12-co Any chance you have some free time to look into this? :)

**Comment by ma12-co** [comment]
@georgehrke after the checkbox? xD

**Comment by raimund-schluessler** [comment]
Looks fine for me now:
![Screenshot 2023-01-27 at 12-59-32 Woche 4 aus 2023 - Kalender - Nextcloud](https://user-images.githubusercontent.com/2496460/215081403-1bfbaadd-6756-44c9-a926-b93d8e183434.png)
