### ISSUE TITLE
Add ability to tweak the modal backdrop color 

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/nextcloud-vue#748]
Right now the modal casts this very dark backdrop on the whole page. I think that is good for photo viewing but very aggressive for anything else, as it almost completely hides the UI underneath.

![Screenshot_20191126_104549](https://user-images.githubusercontent.com/26852655/69618374-171ac780-103a-11ea-8fa8-d126be367e2a.png)

I think it would make sense to have at least 2 options: this very dark one, and a more clear one, as per material design specs: https://material.io/components/dialogs/#anatomy

What do you think @nextcloud/designers?

**Comment by skjnldsv** [comment]
do it in css? ^^

**Comment by skjnldsv** [comment]
> at least 2 options: this very dark one, and a more clear one

ah right, that would be cleaner indeed :)
please do! :rocket: :heart:

**Comment by ma12-co** [comment]
Actually IMO we should make the dark option completely black, as the UI behind the current one is so dark that it's kinda useless and it seems almost an error/unwanted.

**Comment by jancborchardt** [comment]
Yes, I thought we agreed on only using this very dark one only for picture viewing? e.g. the First run wizard and all the normal modals should use a rather light backdrop.

This does not need to be configurable. Basically the default is a light backdrop, and Viewer simply uses a very dark backdrop.

**Comment by skjnldsv** [comment]
@jancborchardt so a toggle between the viewer mode and the first run wizard?

**Comment by jancborchardt** [comment]
> @jancborchardt so a toggle between the viewer mode and the first run wizard?

No, as said above:

> This does not need to be configurable. Basically the default is a light backdrop, and Viewer simply uses a very dark backdrop.

So everyone uses the default, which is a lighter backdrop. Viewer force overrides it. If we see that any other app needs it, we can make the Viewer backdrop style available to others as well.

**Comment by jancborchardt** [comment]
Nevermind, https://github.com/nextcloud/nextcloud-vue/pull/750 seems good :)
