### ISSUE TITLE
ActionInput: add Multisect

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-vue#774]
It would be nice if we could provide a drop-down list for the `ActionInput` component (see https://github.com/nextcloud/notes/issues/413#issuecomment-565825366). Therefore, I propose to add the existing `Multiselect` component to `ActionInput`. It could be used instead of the default HTML input field if the new optional prop `options` is set. All other props would be passed, so further customization would be possible.

Any doubts on this? I would try to provide a PR otherwise.

**Comment by ma12-co** [comment]
@korelstar I don't think we should allow opening a drop-down menu on top of the action menu, It can be very confusing.

**Comment by korelstar** [comment]
@ma12-co But that's what's already done with the date picker when you have `type=date` in `ActionInput`. Where is the difference?

**Comment by ma12-co** [comment]
@korelstar that shouldn't happen either In my opinion.. I know it's technically possible right now but are you aware of a datepicker opened from an action menu in Nextcloud atm?

cc @skjnldsv

**Comment by korelstar** [comment]
This was implemented by @skjnldsv - maybe he can tell ...

**Comment by skjnldsv** [comment]
We had this behaviour for the sharing section of the files sidebar, so this was implemented to avoid regression, but this is a fair discussion.
If anyone have a better idea, it's fine :)
I'll let Jan decide what is best here! :wink:

**Comment by korelstar** [comment]
@jancborchardt What do you think about this? Can we enhance the `ActionInput` component by providing suggestions using the `Multiselect` component?

**Comment by jancborchardt** [comment]
I don’t see an issue with opening a dropdown in the actions menu, especially when it’s about suggestions for an element in there. It’s totally necessary. :)

**Comment by skjnldsv** [comment]
Anyone can take over this issue then :)
