### ISSUE TITLE
ActionInput of type date requires String values but DatetimePicker only works with numbers

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/nextcloud-vue#793]
The ActionInput requires [its `value` property to be a String](https://github.com/nextcloud/nextcloud-vue/blob/4c36a4edbd7259838682f5dc3c67e05fa42cefd0/src/components/ActionInput/ActionInput.vue#L122), but the DatetimePicker does not work with String values, only numbers. See the following examples:
```
<template>
	<Actions>
		<ActionInput icon="icon-edit" type="date" :value="timestampNumber">Please pick a date</ActionInput>
		<ActionInput icon="icon-edit" type="date" :value="timestampString">Please pick a date</ActionInput>
	</Actions>
</template>
<script>
export default {
	data() {
		return {
			timestampNumber: 1095869760000,
			timestampString: '1095869760000',
		}
	},
}
</script>
```

```
<template>
	<div>
		<DatetimePicker :value="timestampNumber" />
	    	<DatetimePicker :value="timestampString" />
	</div>
</template>
<script>
export default {
	data() {
		return {
			timestampNumber: 1095869760000,
			timestampString: '1095869760000',
		}
	},
}
</script>
```

Thus, although the ActionInput of type date works with a number value it shows an error in the browser console due to the failed type validation.

The reason is that the value property passed to the DatetimePicker component needs to be a number, as vue2-datepicker internally uses `new Date(value)` to [validate](https://github.com/mengxiong10/vue2-datepicker/blob/v2.10.0/src/utils/index.js#L15) and [transform](https://github.com/mengxiong10/vue2-datepicker/blob/v2.10.0/src/utils/transform.js#L3-L12) it.

This could be fixed by changing the type of the value property of ActionInput to accept numbers too or, even better, to adjust the DatetimePicker component to transform under the hood a String value to a number value.

Note that the vue2-datepicker component in 2.10 [provided a way to customize how the value was transformed](https://github.com/mengxiong10/vue2-datepicker/tree/v2.10.0#value-type), but [that seems to be gone in the 3.x versions](https://github.com/mengxiong10/vue2-datepicker/tree/v3.0.0#value-type), so to ease a future update to the 3.x versions it might be better to just use a computed property in DatetimePicker that transforms the given value to a number before passing it to the vue2-datepicker.

**Comment by raimund-schluessler** [comment]
`NcActionInput` allows numbers now as well:
https://github.com/nextcloud/nextcloud-vue/blob/ebf538c3b1458ca0558faf13226d0e4ba031ef5d/src/components/NcActionInput/NcActionInput.vue#L323-L329
