### ISSUE TITLE
Breadcrumb component

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#800]
Would it be of interest to have a component for the breadcrumb bar? I currently use a breadcrumb bar in one of my apps and wonder whether other apps might also need it.

**Comment by skjnldsv** [comment]
Does it make sense for other apps?
I think we only use it in files, so not sure this should be a standard :thinking: cc @jancborchardt

**Comment by raimund-schluessler** [comment]
At least three apps I am aware of use a breadcrumb:

Files:
![files](https://user-images.githubusercontent.com/2496460/72146656-30cf5e80-339d-11ea-925b-aadbecf5cb36.png)

Gallery:
![galery](https://user-images.githubusercontent.com/2496460/72146665-34fb7c00-339d-11ea-9887-6261f9ee9a7f.png)

Deck:
![deck](https://user-images.githubusercontent.com/2496460/72146679-3af15d00-339d-11ea-8255-7315c82e6fee.png)

**Comment by skjnldsv** [comment]
I think Deck is supposed to be changed (I remember a conversation somewhere where Jan wanted to remove this)
And Gallery is killed for 18 :eyes:

**Comment by raimund-schluessler** [comment]
Ah, so it is Files only 😄

**Comment by skjnldsv** [comment]
> (I remember a conversation somewhere where Jan wanted to remove this)

https://github.com/nextcloud/deck/issues/372 I think

**Comment by skjnldsv** [comment]
But anyway, if we do the files to vue, it's always a good habit to properly design components so they can be extracted independently from the app they're used.
So we could still create a breadcrumb component after it's done for files and move it there :thinking:

**Comment by jancborchardt** [comment]
Yeah – so on one hand it can be in a component to have it made properly.

On the other hand we could then just kind of leave it out of the docs because we discourage using it. Because as we see, apps will use a component even if it makes no sense, and breadcrumbs really only make sense for files. :)

**Comment by raimund-schluessler** [comment]
I wrote a breadcrumb component for an app i work on. It resizes with the available space and shows hidden folders in a dropdown. I think it works quite well, even better than the breadcrumb in the files app which is sometimes behaving a bit odd.

The version in the files app sometimes hides folder for one viewport width and shows them for narrower sizes.
Wide:
![Screenshot_2020-03-10 Long long long long Test - Files - Nextcloud](https://user-images.githubusercontent.com/2496460/76398156-a85d4200-637c-11ea-93b1-9f3843963988.png)

Narrow:
![Screenshot_2020-03-10 Long long long long Test - Files - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/76398173-b27f4080-637c-11ea-8073-479865a11bc1.png)

This doesn't happen with the vue component:
![Screenshot_2020-03-10 Inventar - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/76398229-d04ca580-637c-11ea-9e56-7f1149907bbc.png)

![Screenshot_2020-03-11 Inventar - Nextcloud](https://user-images.githubusercontent.com/2496460/76398376-0f7af680-637d-11ea-9044-2a96672e3fe6.png)

The code would probably need some adjustments to be used as a general component, but I am quite sure it could be used as a starting point for a version used in the files app.

Let me know if you are interested in the code.

**Comment by skjnldsv** [comment]
> Let me know if you are interested in the code.

Could you open a pr for this component? :)

**Comment by raimund-schluessler** [comment]
> Could you open a pr for this component? :)

PR is in #913
