### ISSUE TITLE
AppsNavigation Avatar Popover Z-Index issue

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#801]
In calendar, we are using an avatar in the AppsNavigation, showing the owner for a shared calendar. When opening the Contacts-menu, parts of it are hidden behind the Content.

__Expected behaviour:__ Contacts-menu should be visible completely

![image](https://user-images.githubusercontent.com/1250540/72149671-f3ba9a80-33a3-11ea-8bb3-6bae0697b0a8.png)

**Comment by skjnldsv** [comment]
Most likely also fixed by #641

**Comment by raimund-schluessler** [comment]
Not an issue anymore.
