### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#802]
nextcloud/vue@1.2.5 requires nextcloud/event-bus@1.1.0 which is not on npm anymore. Hence, the build all all my tests fail. @ChristophWurst 

```npm
npm ERR! missing: @nextcloud/vue@1.2.5, required by inventory@0.0.1
npm ERR! missing: @nextcloud/axios@1.3.0, required by @nextcloud/vue@1.2.5
npm ERR! missing: @nextcloud/auth@1.2.0, required by @nextcloud/axios@1.3.0
npm ERR! missing: @nextcloud/event-bus@1.1.0, required by @nextcloud/auth@1.2.0
```

I guess we have to update the dependency nextcloud/axios to 1.3.1.

**Comment by raimund-schluessler** [comment]
Closed with #811

**Comment by ChristophWurst** [comment]
My bad. The release was so borked I deleted it so nobody runs into trouble. Didn't know Dependabot picked up the change so quickly. Next time I'll deprecate instead.

**Comment by raimund-schluessler** [comment]
> My bad. The release was so borked I deleted it so nobody runs into trouble. Didn't know Dependabot picked up the change so quickly. Next time I'll deprecate instead.

Don't worry, it's fine. Would just be cool to have a working 1.2.6. @skjnldsv 😉

**Comment by skjnldsv** [comment]
@raimund-schluessler you can do it yourself, just properly tag a release and push it (`npm version patch`)
Then fill the new release with a proper changelog on github :)

**Comment by raimund-schluessler** [comment]
Hm, I never did this before. I guess I can try that. Does this also publish the release to npm?

**Comment by skjnldsv** [comment]
Automatically yes ;)
