### ISSUE TITLE
ActionInput is reset when a class or tooltip is added

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#804]
The `ActionInput` component gets reset (loses its current value) whenever you add a class or show a tooltip on the `ActionInput`. I don't really understand why this happens tbh.

Background:

I want to create an action menu to add a folder like in the files app. For this, I would like to check whether the provided name fulfills certain rules (not empty, no '/') and add an `error` class and show a tooltip in case it does not. Hence, I created the following component:

```vue

<template>
	<Actions default-icon="icon-add" @close="addingFolder = false">
		<ActionButton
			icon="icon-add"
		>
			Other action
		</ActionButton>
		<ActionButton v-if="!addingFolder"
			icon="icon-folder" @click.prevent.stop="openFolderInput()"
		>
			New Folder
		</ActionButton>
		<ActionInput v-if="addingFolder"
			:class="{ 'error': folderNameError }"
			v-tooltip="{
				show: folderNameError,
				content: errorString,
				trigger: 'manual',
			}"
			icon="icon-folder"
			@submit="addFolder"
			@input="checkFoldername"
		>
			New Folder
		</ActionInput>
	</Actions>
</template>

<script>
import { Actions } from '@nextcloud/vue/dist/Components/Actions'
import { ActionInput } from '@nextcloud/vue/dist/Components/ActionInput'
import { ActionButton } from '@nextcloud/vue/dist/Components/ActionButton'

export default {
	components: {
		Actions,
		ActionInput,
		ActionButton,
	},
	data: function() {
		return {
			addingFolder: false,
			errorString: null,
			folderNameError: false,
		}
	},
	methods: {
		openFolderInput() {
			this.addingFolder = !this.addingFolder
		},

		addFolder(event) {
			const newName = event.target.querySelector('input[type=text]').value
		},

		checkFoldername(event) {
			const newName = event.target.value
			if (newName === '') {
				this.folderNameError = true
				this.errorString = 'Folder name cannot be empty.'
			} else if (newName.includes('/')) {
				this.folderNameError = true
				this.errorString = '"/" is not allowed inside a folder name.'
			} else {
				this.folderNameError = false
				this.errorString = null
			}
		},
	},
}
</script>
```

Now, whenever you type something like "asdf/" which triggers the rule to not include "/" the input is reset to an empty string. When you then type something else, like "a" (so no tooltip is shown and the error class is removed), the typed character gets lost, because the input was again reset.

Any hint or if I do something wrong would be appreciated @nextcloud/vuejs

**Comment by ChristophWurst** [comment]
Couldn't find anything obvious in https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/ActionInput/ActionInput.vue. Are you still having this problem?

**Comment by raimund-schluessler** [comment]
Turns out it was an implementation problem on my side. Using `:value.sync="inputtesxt"` on the `NcActionInput` and computed instead of methods for the error values fixes the issue.
