### ISSUE TITLE
Hover over navigationItem in dark mode returns black triangle

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-vue#830]
### What is going wrong?
**Describe the bug**
when hovering over the left sidebar items, the current icon kind of hides, because it gets dark?

**To Reproduce**
1. activate dark mode
2. hover over the items in the left sidebar
3. the icon of the current item hides (gets dark?)

**Expected behavior**
the icon of the current item should stay visible

**Screenshots**

![image](https://user-images.githubusercontent.com/42591237/72761189-8563ac80-3bdb-11ea-9f16-7d842e79ec97.png)

### Information about your polls installation
**Polls version?** (see apps page)
1.0

**Fresh installation or update from a prior version (from which one)?**
upgrade from prior version

**How did you install this version?(Appstore or describe installation)**
appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
nextcloud

**Which Version?**
17.0.2

**Comment by dartcafe** [comment]
Is that am issue in nextcloud-vue or does it belong to the dark mode?

**Comment by skjnldsv** [comment]
Most likely the vue components?

**Comment by szaimen** [comment]
@dartcafe strangely enough the same feature works in nextcloud maps, so I would guess it is noth the vue component but the implementation in your app?
Here is a screenshot from the maps app:
![image](https://user-images.githubusercontent.com/42591237/72977548-0afe7c80-3dd5-11ea-9f29-d1b8ed0c1eec.png)

**Comment by dartcafe** [comment]
@szaimen As far as I can see, maps doesn't use the nextcloud-vue components.
https://github.com/nextcloud/maps/blob/master/package.json

**Comment by skjnldsv** [comment]
Easy fix https://github.com/nextcloud/nextcloud-vue/blob/89fab6ea8e63592d65519479ac9650cb59343927/src/components/AppNavigationItem/AppNavigationIconCollapsible.vue#L65
