### ISSUE TITLE
AppNavigationSettings automatically close on "click outside"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#862]
In Talk we use the app navigation setting to selec tthe attachment folder.
Unluckily clicking anything in the filepicker will close the settings menu.
This feels very weird and we need a way to prevent this.

> ![Peek 2020-02-19 13-50](https://user-images.githubusercontent.com/213943/74836128-0e771c00-531f-11ea-8ab5-7f6044aa267a.gif)

**Comment by skjnldsv** [comment]
Yep, hard to manage :/
Anyone have an idea for a fix?

**Comment by georgehrke** [comment]
Related to https://github.com/nextcloud/nextcloud-vue/issues/834

**Comment by georgehrke** [comment]
I see two options here:
1. Either #843 and watch for changes of open, if it changes change it back to keep it open (feels a little hacky)
2. Allow to override the v-click-outside handler (something we do nowhere else)

**Comment by georgehrke** [comment]
@skjnldsv @nickvergessen Any preference on a solution? :)

**Comment by nickvergessen** [comment]
Not my level of expertise

**Comment by skjnldsv** [comment]
> * Allow to override the v-click-outside handler (something we do nowhere else)

I would maybe go for something like this.
I faced the same issue recently. v-click-outside allows to register a middleware, which we can fit to have specific exclude rules

My take would be either a class or a data-exclude-click-outside or something. SO we can have a target and define areas that will be excluded. Of course I would let the dev implement the target, but for the example of the modal, we could pass an id to the modal and pass it as a prop to the settings to make sure this si excluded from outside?

**Comment by georgehrke** [comment]
@skjnldsv Do you mean something like this? 
https://github.com/nextcloud/nextcloud-vue/pull/983/files

**Comment by skjnldsv** [comment]
I don't know, can you give an example of code on the pr? :)
