### ISSUE TITLE
Summary of essential components

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#9]
This is just a collection of what might be a good starting point for components. 

- [x] AppNavigation **Implemented**
- [x] PopoverMenu **Implemented**
- [x] Sidebar #340 
- [x] Action https://github.com/nextcloud/vue-components/issues/12
- [ ] ContentList https://docs.nextcloud.com/server/14/developer_manual/design/list.html
- [x] Avatar **Implemented**
- [x] Dialog #212 
- [x] Tooltip https://github.com/Akryum/v-tooltip
- [x] Datepicker **Implemented**
- [x] Timepicker **Implemented**
- [ ] Relative timestamp (like moment.js) https://github.com/nextcloud/vue-components/issues/13

@skjnldsv @ChristophWurst

**Comment by ChristophWurst** [comment]
> ContentList https://docs.nextcloud.com/server/14/developer_manual/design/list.html

In this context we should think about a refresh/reload mechanism that might be used by some apps (e.g. load new messages in Mail, pull in synced contacts in Contacts).

**Comment by skjnldsv** [comment]
ContentList: https://github.com/nextcloud/contacts/blob/6713a73479c9cb054034e3466ffa2167a9f74055/src/components/ContentList.vue
https://github.com/nextcloud/contacts/blob/6713a73479c9cb054034e3466ffa2167a9f74055/src/components/ContentList/ContentListItem.vue

**Comment by dartcafe** [comment]
I would add a date and a time picker to get rid of using jQuery with vue.

**Comment by ChristophWurst** [comment]
Something that came up in Mail: a moment-js-like timestamp, like `x seconds ago`.

**Comment by juliushaertl** [comment]
> Something that came up in Mail: a moment-js-like timestamp, like x seconds ago.

https://github.com/brockpetrie/vue-moment looks good for that. Should we just keep a list of recommended vue libs for small stuff like that? I don't think it is worth to add a wrapper for it to the nextcloud vue components.

**Comment by georgehrke** [comment]
Will Dialog also cover in-dialog input fields like here?
![7cf052e6-f939-4061-bc67-3a64de33fdf0](https://user-images.githubusercontent.com/1250540/44627167-5c2ce700-a929-11e8-93d9-b952b3eadc12.jpg)

**Comment by skjnldsv** [comment]
@georgehrke the idea is to support the same features as the designer guide :)

**Comment by ChristophWurst** [comment]
> https://github.com/egoist/vue-timeago looks good for that.

Works :+1:, but l10n is pain to use as it requires you to load the translations from another package: https://github.com/egoist/vue-timeago#usage.

**Comment by skjnldsv** [comment]
Any good datepicker? :)

**Comment by georgehrke** [comment]
An autocomplete component would be highly appreciated :) 
with label, value, and avatar / icon / plain color.

**Comment by skjnldsv** [comment]
@georgehrke with dropdown?
vue-multiselect is already here for that :)

**Comment by dartcafe** [comment]
What about vuetify? OK, it could start a new discussion about using material design, but it has many useful components.

**Comment by skjnldsv** [comment]
@dartcafe the idea is not to port other components into nextcloud. Let's keep our simplified and unified design. :)
If you find any other reusable components we use on nc or associated apps then let's add them on this list ;)

**Comment by skjnldsv** [comment]
Date-time picker? https://mengxiong10.github.io/vue2-datepicker/demo/index.html
That's the only one I found that seems to fit our need :/

**Comment by skjnldsv** [comment]
@jancborchardt I'm not sure. The idea is small individuals components that are simple and reusable everywhere. Big lists or stuff like that can be standardised for the html/css but will be far too complicated fot a vue component.

**Comment by jancborchardt** [comment]
Hm – I would say it’s very comparable to the ContentList component though? https://docs.nextcloud.com/server/14/developer_manual/design/list.html

And of course "grid view" is a bit of a big part. But a component would be a "tiled element", or "preview component with a title component below and action menu right next to it".

**Comment by skjnldsv** [comment]
Content list is very simple, you have like 5 différents options, tops.
The file list is crazy complicated. And having everything in a single component would greatly lower down the possibilities of working with all the vue features.

Remember, that for those components, you cannot edit the inner data or structure. You just give it an object ant vue does the rest. This exclude all custom ideas you might want to add into your app or other complex methods.

**Comment by skjnldsv** [comment]
> And of course "grid view" is a bit of a big part. But a component would be a "tiled element", or "preview component with a title component below and action menu right next to it".

But small stuff like that, yes definitely :grimacing: :+1: :100:

**Comment by dartcafe** [comment]
Did we mention a sharing component?

**Comment by splitt3r** [comment]
Sidebar with SidebarTab would be nice too.

**Comment by skjnldsv** [comment]
@splitt3r again, complicated components. 
Let's only focus on simple and reusable ones.

@dartcafe what do you mean?

**Comment by splitt3r** [comment]
Ok :+1:

**Comment by skjnldsv** [comment]
@splitt3r though, we have a pending discussion to standardise the sidebar ;) 
https://github.com/nextcloud/server/issues/10289

**Comment by dartcafe** [comment]
This one:
![grafik](https://user-images.githubusercontent.com/26707476/45204033-58c92200-b27e-11e8-8b53-3850426b20a8.png)

I think it would be helpful to have this componement to select users from a list.

**Comment by ChristophWurst** [comment]
Also, we can just have separate tickets for these kinds of components that would be nice to have, but are not essential right now? I mean we're happy for all feedback and I'm sure the number of components will grow over time, so there's nothing wrong with proposing (exotic) ones right now :wink:

**Comment by skjnldsv** [comment]
@ChristophWurst Yes! If the component is not something that is used by almost all of the apps, then please create a new issue :)

**Comment by juliushaertl** [comment]
I think we could still provide a basic tab component with slots for the content. So devs at least don't need to mess with the tab switching for example.

**Comment by skjnldsv** [comment]
@juliushaertl yes for the tabs, seems simple enough :)

**Comment by skjnldsv** [comment]
About some external components, like the date-time picker for example : https://github.com/mengxiong10/vue2-datepicker

How should we handle theming?
Should we create a component that just forward everything to this component? Should we fork it?
I like the idea of just creating a "fake" component that provide all the data from the datepicker and we just add our css on top and ship it like it is our component. We'd still have to update the datepicker from the origin repo once in a while, but dependabot sure can manage that? :)

**Comment by ChristophWurst** [comment]
> I like the idea of just creating a "fake" component that provide all the data from the datepicker and we just add our css on top and ship it like it is our component. We'd still have to update the datepicker from the origin repo once in a while, but dependabot sure can manage that

:+1: on that. Let's try to reuse as much as possible without forking/duplicating.

**Comment by skjnldsv** [comment]
Implemented :)
![capture d ecran_2018-09-11_10-15-55](https://user-images.githubusercontent.com/14975046/45347242-e1f89580-b5ab-11e8-880b-8f8e2c592bc7.png)

**Comment by jancborchardt** [comment]
@skjnldsv the datepicker look different from the one in core, like top bar arrows are different, week day names are too present? The design should at least start out with the way it currently is. :slightly_smiling_face: 
![screenshot from 2018-10-02 19-36-30](https://user-images.githubusercontent.com/925062/46366073-82594b80-c67a-11e8-836b-72c50c3e5b9a.png)

**Comment by skjnldsv** [comment]
@jancborchardt I used most of the design we had on the one we added on server, but there was a lot of part missing (year pick, month pick)!
But I really feel like it fit our current design and it's a nice improvement. I find this one far cleaner and easy to use compare to the jQuery one ;)
Could you do a review of it and create a new issue here to follow what we can do to improve it? :)
You can try this datepicker in the new contacts alpha if you want :)

**Comment by skjnldsv** [comment]
Closing now, most of them have their own issue or already exists :)
