### ISSUE TITLE
Actions aria not compliant

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#950]
Because [we now use v-if for the actions](https://github.com/nextcloud/nextcloud-vue/pull/569), we became non-compliant because the menu containing the id doesn't exist on the page.

![image](https://user-images.githubusercontent.com/14975046/77780457-51ca5600-7054-11ea-83c4-7ce31851f6bc.png)

![image](https://user-images.githubusercontent.com/14975046/77780435-4aa34800-7054-11ea-980f-e8235bef561c.png)

@nextcloud/accessibility

**Comment by skjnldsv** [comment]
@korelstar because we discussed this initially.
Maybe hiding the slot instead?

**Comment by korelstar** [comment]
> Maybe hiding the slot instead?

Yep, that's a good solution. I just did a performance test, and this approach is negligibly slower than now, but significantly faster than using `v-show` only.

Since I already changed the code for the performance test, I will create a PR for this.

**Comment by skjnldsv** [comment]
> I just did a performance test, and this approach is negligibly slower than now, but significantly faster than using `v-show` only.

How big a difference was that?
Also one of the issue can be the amount of displayed node on the browser.
But to be honest with that much data (rows, navigation) a dev shall most likely implement virtual scroll at this point :)

**Comment by korelstar** [comment]
#951 is about 3% slower than `master`.
Using `v-show` without `v-if` on the slot (like in #951) is about 185% slower than `master`.

Therefore, if #951 fixes the aria issue, I don't see any problems against using this solution.

**Comment by skjnldsv** [comment]
Thanks for the pr!! :hugs:
