### ISSUE TITLE
Multiselect fixes

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#99]
- [ ] Pre-translate the error messages so that users doesn't have to do it?
- [x] Fix slots not working since we do not forward them to the select component
- [x] Fix design of the `checkbox` icon on single select (maybe use an arrow instead, the checkbox is confusing on single select)

**Comment by dartcafe** [comment]
Question: Is the fixed width of 160px with intend?

**Comment by skjnldsv** [comment]
@dartcafe good question. 😜
That's the style I designed when imolemnying it on server 6 months ago. Of course everything is up to discussion. If you think we should do something else let's do it 👍🤗

**Comment by skjnldsv** [comment]
@dartcafe we removed the width property in favour of a min-width.
It should ease the compatibility with other apps :)

**Comment by skjnldsv** [comment]
Closing as what's left is #97
