### ISSUE TITLE
Mobile users cannot view photos, only download

### ISSUE THREAD

**Issue by smacz42** [nextcloud/nextcloud-vue#992]
Hello all,

I recently updated to NC 18, and found that `gallery` was deprecated. On desktop, it seems that Photos works just fine, but on any kind of mobile browser, recipients of a public link with no app have no choice other than to download files.

Is there a way for mobile users who do not have this app (literally anyone that I share a link with) to view the images without downloading them one-by-one-in-a-horrific-attempt-to-peruse-the-gallery-that-I-gave-them-to-look-at?

**Comment by skjnldsv** [comment]
Please have a look at the existing issues.
You also commented on #270 which list exactly the issue you're referring to.
Please make sure to search before posting, that saves me lots of time answering duplicates :/

Have a nice day! Stay safe!

**Comment by skjnldsv** [comment]
Also, this is completely the wrong repository
